\set ON_ERROR_STOP on

-- Disposable PostgreSQL contract test for the production-like security boundary.
-- The CI service database is ephemeral; no Supabase project is modified.

create role anon nologin;
create role authenticated nologin;

create schema auth;
grant usage on schema auth to anon, authenticated;

create or replace function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
grant execute on function auth.uid() to anon, authenticated;

create table public.books (
  id integer primary key,
  title text not null
);
insert into public.books (id, title) values (1, 'Livro de teste');
grant all privileges on table public.books to anon, authenticated;

create table public.profiles (
  id uuid primary key,
  name text
);
alter table public.profiles enable row level security;
grant all privileges on table public.profiles to authenticated;
create policy "Usuário acessa apenas seu próprio perfil"
on public.profiles
for all
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create table public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  book_id integer
);
alter table public.user_progress enable row level security;
grant all privileges on table public.user_progress to authenticated;
grant usage, select on sequence public.user_progress_id_seq to authenticated;
create policy "Usuário acessa apenas seu próprio progresso"
on public.user_progress
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table public.reading_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  book_id integer,
  section_id integer,
  read_at date,
  duration_s integer
);
alter table public.reading_sessions enable row level security;
grant all privileges on table public.reading_sessions to authenticated;
grant usage, select on sequence public.reading_sessions_id_seq to authenticated;
create policy "Usuário acessa apenas suas próprias sessões"
on public.reading_sessions
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null
);
alter table public.push_subscriptions enable row level security;
grant all privileges on table public.push_subscriptions to authenticated;
grant usage, select on sequence public.push_subscriptions_id_seq to authenticated;
create policy "Users can manage own subscriptions"
on public.push_subscriptions
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  return new;
end;
$$;

grant execute on function public.handle_new_user() to anon, authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  return new;
end;
$$;

grant execute on function public.set_updated_at() to anon, authenticated;

create or replace function public.get_streak(p_user_id uuid)
returns integer
language sql
stable
as $$
  select 0;
$$;

grant execute on function public.get_streak(uuid) to anon, authenticated;

create or replace function public.get_reading_minutes_last_7_days(p_user_id uuid)
returns integer
language sql
stable
as $$
  select 0;
$$;

grant execute on function public.get_reading_minutes_last_7_days(uuid) to anon, authenticated;

\i supabase/migrations/20260828060000_public_database_security_hardening.sql

-- Catalog remains readable, but browser roles cannot mutate it.
do $$
begin
  if not (select relrowsecurity from pg_class where oid = 'public.books'::regclass) then
    raise exception 'books RLS was not enabled';
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'books'
      and policyname = 'Leitura pública dos livros'
      and cmd = 'SELECT'
  ) then
    raise exception 'public book read policy missing';
  end if;

  if not has_table_privilege('anon', 'public.books', 'SELECT')
     or not has_table_privilege('authenticated', 'public.books', 'SELECT') then
    raise exception 'book SELECT privilege was not preserved';
  end if;

  if has_table_privilege('anon', 'public.books', 'INSERT')
     or has_table_privilege('anon', 'public.books', 'UPDATE')
     or has_table_privilege('anon', 'public.books', 'DELETE')
     or has_table_privilege('authenticated', 'public.books', 'INSERT')
     or has_table_privilege('authenticated', 'public.books', 'UPDATE')
     or has_table_privilege('authenticated', 'public.books', 'DELETE') then
    raise exception 'browser mutation privilege remains on books';
  end if;
end;
$$;

-- Trigger-only functions are no longer callable by browser roles.
do $$
begin
  if has_function_privilege('anon', 'public.handle_new_user()', 'EXECUTE')
     or has_function_privilege('authenticated', 'public.handle_new_user()', 'EXECUTE')
     or has_function_privilege('anon', 'public.set_updated_at()', 'EXECUTE')
     or has_function_privilege('authenticated', 'public.set_updated_at()', 'EXECUTE') then
    raise exception 'trigger-only function remains browser executable';
  end if;

  if has_function_privilege('anon', 'public.get_streak(uuid)', 'EXECUTE')
     or not has_function_privilege('authenticated', 'public.get_streak(uuid)', 'EXECUTE')
     or has_function_privilege('anon', 'public.get_reading_minutes_last_7_days(uuid)', 'EXECUTE')
     or not has_function_privilege('authenticated', 'public.get_reading_minutes_last_7_days(uuid)', 'EXECUTE') then
    raise exception 'reading helper RPC privileges are incorrect';
  end if;
end;
$$;

-- All hardened functions have a fixed public search_path.
do $$
declare
  fn record;
begin
  for fn in
    select p.proname, p.proconfig
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in ('handle_new_user', 'set_updated_at', 'get_streak', 'get_reading_minutes_last_7_days')
  loop
    if fn.proconfig is null or not ('search_path=public' = any(fn.proconfig)) then
      raise exception 'function % does not pin search_path=public', fn.proname;
    end if;
  end loop;
end;
$$;

-- Owner-only RLS semantics still work after replacing auth.uid() with a cached subquery.
insert into public.profiles (id, name) values
  ('11111111-1111-1111-1111-111111111111', 'User one'),
  ('22222222-2222-2222-2222-222222222222', 'User two');

insert into public.user_progress (user_id, book_id) values
  ('11111111-1111-1111-1111-111111111111', 1),
  ('22222222-2222-2222-2222-222222222222', 1);

insert into public.reading_sessions (user_id, book_id, section_id, read_at, duration_s) values
  ('11111111-1111-1111-1111-111111111111', 1, 1, current_date, 60),
  ('22222222-2222-2222-2222-222222222222', 1, 1, current_date, 60);

insert into public.push_subscriptions (user_id) values
  ('11111111-1111-1111-1111-111111111111'),
  ('22222222-2222-2222-2222-222222222222');

set role authenticated;
set request.jwt.claim.sub = '11111111-1111-1111-1111-111111111111';

do $$
begin
  if (select count(*) from public.books) <> 1 then
    raise exception 'authenticated catalog read failed';
  end if;
  if (select count(*) from public.profiles) <> 1 then
    raise exception 'profile RLS no longer isolates current user';
  end if;
  if (select count(*) from public.user_progress) <> 1 then
    raise exception 'progress RLS no longer isolates current user';
  end if;
  if (select count(*) from public.reading_sessions) <> 1 then
    raise exception 'reading session RLS no longer isolates current user';
  end if;
  if (select count(*) from public.push_subscriptions) <> 1 then
    raise exception 'push subscription RLS no longer isolates current user';
  end if;
end;
$$;

reset role;
reset request.jwt.claim.sub;

set role anon;
do $$
begin
  if (select count(*) from public.books) <> 1 then
    raise exception 'anonymous public catalog read failed';
  end if;
end;
$$;
reset role;

select 'public database security hardening runtime contract passed' as result;
