import { describe,expect,it } from 'vitest'
import { readFile } from 'node:fs/promises'
import { canonicalJsonSha256FromValue } from '../../scripts/content_pipeline/hash_utils.mjs'
import { build,deriveContentIntegrity } from '../../scripts/content_pipeline/build_reviewed_boundary_content_integrity.mjs'
import { validate } from '../../scripts/content_pipeline/validate_reviewed_boundary_content_integrity.mjs'
import { paths } from '../../scripts/content_pipeline/reviewed_boundary_content_integrity_constants.mjs'
describe('PR-0056 content-integrity package',()=>{
 it('reconstructs 74 unique status-only targets',async()=>{const a=await deriveContentIntegrity(),r=a.targets.records;expect(r).toHaveLength(74);expect(new Set(r.map(x=>x.decision_id)).size).toBe(74);expect(new Set(r.map(x=>`${x.run_id}:${x.book_id}:${x.segment_key}`)).size).toBe(74);expect(r.every(x=>x.current_approval_status==='boundary-review'&&x.intended_resulting_approval_status==='content-review')).toBe(true)})
 it('hashes identity canonically and never hashes an insufficient baseline',async()=>{const r=(await deriveContentIntegrity()).targets.records[0];expect(r.identity_sha256).toBe(canonicalJsonSha256FromValue(r.identity_projection));expect(r.boundary_sha256).toBeNull();expect(r.content_sha256).toBeNull();expect(r.full_pre_application_sha256).toBeNull()})
 it('orders targets and inventories rollback',async()=>{const a=await deriveContentIntegrity(),ids=a.targets.records.map(r=>r.decision_id);expect(ids).toEqual([...ids].sort());expect(a.rollback.records).toHaveLength(74);expect(a.rollback.records.every(r=>r.original_approval_status&&r.identity_sha256&&!r.rollback_baseline_complete)).toBe(true)})
 it('defines required drift detection',async()=>{const d=(await deriveContentIntegrity()).drift;for(const c of ['MATCH','STATUS_ALREADY_APPLIED','STATUS_UNEXPECTED','IDENTITY_MISSING','BOUNDARY_DRIFT','CONTENT_DRIFT','METADATA_DRIFT','SOURCE_HASH_DRIFT','DUPLICATE_TARGET','UNAUTHORIZED_TARGET','INSUFFICIENT_BASELINE'])expect(d.classifications[c]).toBeDefined();expect(d.classifications.BOUNDARY_DRIFT.blocks_execution).toBe(true);expect(d.classifications.CONTENT_DRIFT.blocks_execution).toBe(true)})
 it('is PR-0055 compatible',async()=>{const c=(await deriveContentIntegrity()).compatibility;expect(c.complete_identity_input_count).toBe(74);expect(c.application_event_keys_unique).toBe(true);expect(c.application_rollback_keys_distinct).toBe(true);expect(c.identity_derivation_unchanged).toBe(true)})
 it('fails closed without row/database authority',async()=>{const a=await deriveContentIntegrity();expect(a.missing.missing_target_count).toBe(74);for(const k of ['source_snapshot_complete','source_snapshot_verified','application_preflight_ready','rollback_baseline_ready','content_integrity_authority_approved'])expect(a.evidence[k]).toBe(false)})
 it('leaks no content, secrets, URL, or mutation SQL',async()=>{const a=await deriveContentIntegrity(),s=JSON.stringify(a).toLowerCase();expect(a.targets.records.every(r=>!Object.hasOwn(r,'content'))).toBe(true);expect(s).not.toMatch(/https?:\/\//);expect(s).not.toMatch(/(service_role_key|password|update content_staging\.reading_segments)/)})
 it('builds twice without a diff and validates independently',async()=>{await build();const first=await readFile(paths.manifest,'utf8');await build();expect(await readFile(paths.manifest,'utf8')).toBe(first);await expect(validate()).resolves.toMatchObject({valid:true,target_count:74})})
})
