import { describe, it, expect } from 'vitest'
import { readFile } from 'node:fs/promises'
import { validate, reconstructPreMigrationAuditSchema, parseProposedMigration, deriveEventKey, eventKeyMaterial, classifyEventState, normalizedTextSha256FromText } from '../../scripts/content_pipeline/validate_reviewed_boundary_audit_identity.mjs'
import { migrationPath, eventActions, eventPackage, conflictTargetPredicate, eventKeyAlgorithm, workflowPath, dbTestScriptPath, roleFixturePath, requiredSupabaseRoles, foundationMigrationPath, foundationMigrationSha256 } from '../../scripts/content_pipeline/reviewed_boundary_audit_identity_constants.mjs'
import { reconstructAuditSchema as reconstructPr54AuditSchema } from '../../scripts/content_pipeline/validate_reviewed_boundary_execution_authority.mjs'
import { discoverReadingSegmentMigrations } from '../../scripts/content_pipeline/validate_reviewed_boundary_consolidated_application_package.mjs'
const baseCreate=`create table if not exists content_staging.migration_audit_events (id bigint generated always as identity primary key, run_id uuid not null references content_staging.migration_runs(id) on delete cascade, event_type text not null, details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'), created_at timestamptz not null default now());`

describe('PR-0055 audit identity authority',()=>{
  it('reconstructs pre-migration schema and lexical ordering independently',async()=>{const s=await reconstructPreMigrationAuditSchema({files:{'002.sql':'select 1;','001.sql':baseCreate}}); expect(s.migrations_scanned).toEqual(['001.sql','002.sql']); expect(s.columns).toEqual(['id','run_id','event_type','details','created_at']); await expect(reconstructPreMigrationAuditSchema({files:{'001.sql':'select 1;'}})).rejects.toThrow(/missing audit table/); await expect(reconstructPreMigrationAuditSchema({files:{'001.sql':baseCreate,'002.sql':baseCreate}})).rejects.toThrow(/conflicting/); await expect(reconstructPreMigrationAuditSchema({files:{'001.sql':baseCreate,'002.sql':'alter table content_staging.migration_audit_events add column x text;'}})).rejects.toThrow(/unsupported later alter/)})
  it('parses proposed migration and rejects unsafe schema drift',async()=>{const sql=await readFile(migrationPath,'utf8'); const p=parseProposedMigration(sql); expect(p.added.map(c=>c.name)).toEqual(['package_id','event_version','decision_id','book_id','segment_key','event_action','event_key']); expect(p.index).toContain(eventPackage); expect(p.index).toContain(conflictTargetPredicate.split(' and ')[0]); await expect(validate({migrationSql:sql.replace('event_key text','event_key uuid')})).rejects.toThrow(/wrong type/); await expect(validate({migrationSql:sql.replace('create extension if not exists pgcrypto with schema extensions;','')})).rejects.toThrow(/pgcrypto/); await expect(validate({migrationSql:sql.replace('extensions.digest','digest')})).rejects.toThrow(/event_key/); await expect(validate({migrationSql:sql.replace("where package_id = 'reading-segment-reviewed-boundary-execution'",'where true')})).rejects.toThrow(/wrong uniqueness scope/); await expect(validate({migrationSql:sql+'\ninsert into content_staging.migration_audit_events(run_id,event_type) values (gen_random_uuid(),\'x\');'})).rejects.toThrow(/INSERT/)})
  it('proves SQL conflict target and partial-index semantics statically',async()=>{const conflict=JSON.parse(await readFile('content/migration/reading-segment-reviewed-boundary-audit-conflict-contract.json','utf8')); expect(conflict.conflict_target).toBe(`ON CONFLICT (event_key) WHERE ${conflictTargetPredicate} DO NOTHING`); expect(conflict.duplicate_behavior).toContain('DO NOTHING alone never proves equality'); const sql=await readFile(migrationPath,'utf8'); expect(sql).toContain('create extension if not exists pgcrypto with schema extensions'); expect(sql).toContain('extensions.digest'); expect(sql).toContain("event_type = 'reading-segment-reviewed-boundary.' || event_action"); expect(sql).toContain('create unique index if not exists migration_audit_events_reviewed_boundary_event_key_uidx'); expect(sql).toContain("where package_id = 'reading-segment-reviewed-boundary-execution'"); expect(sql).toContain("event_action in ('status-advanced', 'status-rollback')"); expect(sql).toContain('event_version = 1'); await expect(validate({artifacts:{'content/migration/reading-segment-reviewed-boundary-audit-conflict-contract.json':{...conflict,conflict_target:'ON CONFLICT (event_key) DO NOTHING'}}})).rejects.toThrow(/conflict target/)})
  it('derives unambiguous stable identities and rejects unsafe artifact identity drift',async()=>{const common={run_id:'run',decision_id:'dec',book_id:1,segment_key:'a'.repeat(20)}; expect(eventKeyMaterial({...common,event_action:eventActions.application})).toContain(eventKeyAlgorithm); expect(deriveEventKey({...common,event_action:eventActions.application})).toMatch(/^[a-f0-9]{64}$/); expect(deriveEventKey({...common,event_action:eventActions.application})).not.toEqual(deriveEventKey({...common,event_action:eventActions.rollback})); expect(deriveEventKey({...common,event_action:eventActions.application,decision_id:'d1'})).not.toEqual(deriveEventKey({...common,event_action:eventActions.application,decision_id:'d2'})); expect(deriveEventKey({...common,event_action:eventActions.application,run_id:'r1'})).not.toEqual(deriveEventKey({...common,event_action:eventActions.application,run_id:'r2'})); expect(deriveEventKey({...common,event_action:eventActions.application,segment_key:'b'.repeat(20)})).not.toEqual(deriveEventKey({...common,event_action:eventActions.application,segment_key:'c'.repeat(20)})); const identity=JSON.parse(await readFile('content/migration/reading-segment-reviewed-boundary-audit-event-identity-contract.json','utf8')); await expect(validate({artifacts:{'content/migration/reading-segment-reviewed-boundary-audit-event-identity-contract.json':{...identity,logical_identity:['id']}}})).rejects.toThrow(/identity/); await expect(validate({artifacts:{'content/migration/reading-segment-reviewed-boundary-audit-event-identity-contract.json':{...identity,event_type_relationship:{application:'wrong',rollback:'wrong'}}}})).rejects.toThrow(/identity/)})
  it('validates payload, duplicate conflict, compatibility, and hashing semantics',async()=>{expect(classifyEventState({eventCount:0,statusCount:0})).toBe('first-run'); expect(classifyEventState({eventCount:74,statusCount:74})).toBe('complete-repeat'); expect(classifyEventState({eventCount:73,statusCount:74})).toBe('partial-state-conflict'); const payload=JSON.parse(await readFile('content/migration/reading-segment-reviewed-boundary-audit-event-payload-contract.json','utf8')); await expect(validate({artifacts:{'content/migration/reading-segment-reviewed-boundary-audit-event-payload-contract.json':{...payload,details_jsonb_required_fields:payload.details_jsonb_required_fields.filter(f=>f!=='package_hash')}}})).rejects.toThrow(/payload missing/); const conflict=JSON.parse(await readFile('content/migration/reading-segment-reviewed-boundary-audit-conflict-contract.json','utf8')); await expect(validate({artifacts:{'content/migration/reading-segment-reviewed-boundary-audit-conflict-contract.json':{...conflict,conflicting_duplicate:'allowed'}}})).rejects.toThrow(/conflict contract/); const sql=await readFile(migrationPath,'utf8'); expect(normalizedTextSha256FromText(sql.replace(/\n/g,'\r\n'))).toEqual(normalizedTextSha256FromText(sql))})

  it('validates GitHub Actions database workflow and runner safety',async()=>{const workflow=await readFile(workflowPath,'utf8'); expect(workflow).toContain('Reviewed Boundary Audit Database Validation'); expect(workflow).toContain('image: postgres:15'); expect(workflow).toContain('POSTGRES_DB: vereda_test'); expect(workflow).toContain('workflow_dispatch'); expect(workflow).toContain('pull_request'); expect(workflow).toContain('if: always()'); expect(workflow).toContain(roleFixturePath); expect(workflow).not.toMatch(/secrets\.|supabase\.co|service_role/i); const script=await readFile(dbTestScriptPath,'utf8'); expect(script).toContain('allowedHosts'); expect(script).toContain('role_bootstrap'); expect(script).toContain('extensions.digest'); expect(script).toContain('persistent_reviewed_boundary_row_count_after_cleanup'); expect(script).toContain('conflict_target_result'); expect(script).toContain('duplicate_verification')})
  it('validates test-only Supabase role fixture and historical foundation preservation',async()=>{const fixture=await readFile(roleFixturePath,'utf8'); for (const role of requiredSupabaseRoles) expect(fixture).toMatch(new RegExp(`create role ${role} nologin nosuperuser nocreatedb nocreaterole noreplication inherit`,'i')); expect(roleFixturePath.startsWith('supabase/migrations/')).toBe(false); expect(fixture.replace(/nosuperuser|nocreatedb|nocreaterole|noreplication|nologin/gi,'')).not.toMatch(/login\s+password|superuser|createdb|createrole|replication|supabase\.co|postgres:\/\//i); const foundation=await readFile(foundationMigrationPath,'utf8'); expect(normalizedTextSha256FromText(foundation)).toBe(foundationMigrationSha256); expect(foundation).toContain('from public, anon, authenticated'); expect(foundation).toContain('to service_role')})

  it('rejects fabricated database evidence and static-only approval',async()=>{const db=JSON.parse(await readFile('content/migration/reading-segment-reviewed-boundary-audit-database-validation-evidence.json','utf8')); await expect(validate({artifacts:{'content/migration/reading-segment-reviewed-boundary-audit-database-validation-evidence.json':{...db,migration_success:true}}})).rejects.toThrow(/database validation/); const policy=JSON.parse(await readFile('content/migration/reading-segment-reviewed-boundary-audit-identity-policy.json','utf8')); await expect(validate({artifacts:{'content/migration/reading-segment-reviewed-boundary-audit-identity-policy.json':{...policy,audit_identity_authority_approved:true}}})).rejects.toThrow(/approval/)} )
  it('records triage base failure unchanged without mutating consumed files',async()=>{const t=JSON.parse(await readFile('content/migration/reading-segment-reviewed-boundary-audit-triage-baseline-evidence.json','utf8')); expect(t.classification).toMatch(/pre-existing base failure/); expect(t.pr0055_changes_consumed_files).toBe(false); expect(t.consumed_files.every(f=>f.modified_by_pr0055===false)).toBe(true); const q=t.consumed_files.find(f=>f.path.endsWith('reading-segment-review-queue.json')); const tri=t.consumed_files.find(f=>f.path.endsWith('reading-segment-review-triage.json')); expect(q.actual_checksum).toBe('3045ca47395bfa47fb883eddaaa6a0b048a4a68e9e80897e2bdba48bb7f3d505'); expect(tri.expected_review_queue_checksum).toBe('06d53501303eaca9aa8a1ba9f81aa10fed02801996eba90ba38f9e15b3440b66')})
  it('preserves historical validator cutoffs without hiding in-boundary drift',async()=>{const pr54=await reconstructPr54AuditSchema({files:{'001.sql':baseCreate,'20260805005500_reviewed_boundary_audit_identity.sql':'alter table content_staging.migration_audit_events add column package_id text;'}}); expect(pr54.migrations_scanned).toEqual(['001.sql','20260805005500_reviewed_boundary_audit_identity.sql']); expect(pr54.columns.map(c=>c.name)).toEqual(['id','run_id','event_type','details','created_at']); await expect(reconstructPr54AuditSchema({files:{'001.sql':baseCreate,'002.sql':'alter table content_staging.migration_audit_events add column x text;'}})).resolves.toMatchObject({unsupported_later_schema_changes:true}); const d=await discoverReadingSegmentMigrations(); expect(d.matching_migrations).not.toContain('supabase/migrations/20260805005500_reviewed_boundary_audit_identity.sql')})
  it('passes full independent validator',async()=>{await expect(validate()).resolves.toMatchObject({audit_identity_authority_approved:false,validator_imports_builder_functions:false})})
})
