import {describe,it,expect} from 'vitest';import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';import {build} from '../../scripts/content_pipeline/build_reviewed_boundary_staging_execution.mjs';import {validate} from '../../scripts/content_pipeline/validate_reviewed_boundary_staging_execution.mjs';import {validatePreconnection,tokenReceipt,persistEvidence} from '../../scripts/content_pipeline/reviewed_boundary_staging_execution.mjs';import {validateEvidence} from '../../scripts/content_pipeline/validate_reviewed_boundary_staging_execution_evidence.mjs';import {classifications,modes,outcomes,evidencePath} from '../../scripts/content_pipeline/reviewed_boundary_staging_execution_constants.mjs';import {canonicalJsonSha256} from '../../scripts/content_pipeline/hash_utils.mjs'
const fixture=async(overrides={})=>{const dir=await mkdtemp(join(tmpdir(),'pr0060-'));const value={fixture_authority:true,environment_class:'fixture',fingerprint_sha256:'a'.repeat(64),attestation_sha256:'b'.repeat(64),decision_sha256:'c'.repeat(64),execution_token_sha256:'d'.repeat(64)};const keys=['admitted-evidence','database-attestation','collector-attestation','technical-reviewer-attestation','execution-authorizer-attestation','authorization-decision','execution-token','application-manifest','runtime-manifest','staging-authorization-manifest','expected-database-identity'];const args={mode:'fixture-apply','execution-identifier':'fixture-0060','operator-confirmation':'synthetic-fixture-only'};for(const k of keys){const p=join(dir,`${k}.json`);await writeFile(p,JSON.stringify({...value,...overrides[k]}));args[k]=p}return {dir,args}}
describe('PR-0060 guarded staging execution',()=>{
 it('is blocked by default before importing a database client',async()=>await expect(validatePreconnection({})).rejects.toThrow(/blocked default/))
 it.each(['production-apply','production-reconcile'])('rejects %s',async mode=>await expect(validatePreconnection({mode})).rejects.toThrow(/production/))
 it('defines the complete explicit mode, classification and outcome worlds',()=>{expect(modes).toHaveLength(7);expect(classifications).toHaveLength(22);expect(outcomes).toHaveLength(10)})
 it('requires every authority artifact before connection',async()=>await expect(validatePreconnection({mode:'fixture-apply','execution-identifier':'fixture-0060','operator-confirmation':'synthetic-fixture-only'})).rejects.toThrow(/missing authority/))
 it('accepts explicit synthetic fixture authority without connecting',async()=>{const x=await fixture();try{expect((await validatePreconnection(x.args)).operations).toHaveLength(74)}finally{await rm(x.dir,{recursive:true})}})
 it('rejects fixture/staging identity conflict',async()=>{const x=await fixture({'expected-database-identity':{environment_class:'staging'}});try{await expect(validatePreconnection(x.args)).rejects.toThrow(/fixture database identity/)}finally{await rm(x.dir,{recursive:true})}})
 it('hashes a closed token-consumption receipt',()=>{const r=tokenReceipt({execution_identifier:'fixture-0060',database_identity_sha256:'a'.repeat(64),authorization_decision_sha256:'b'.repeat(64),target_set_sha256:'c'.repeat(64),transaction_outcome:'COMMITTED',audit_reconciliation_result:'COMPLETE'});expect(r.token_state).toBe('consumed');expect(r.token_consumption_receipt_sha256).toMatch(/^[a-f0-9]{64}$/)})
 it('validates successful evidence and rejects corruption/leakage',async()=>{const e=await persistEvidence({execution_evidence_version:'pr0060-execution-evidence-v1',execution_mode:'fixture-apply',execution_identifier:'fixture-0060',redacted_database_identity:{environment_class:'fixture'},postgresql_version:'150000',source_hashes:{},evidence_admission_hash:null,attestation_hashes:{},authorization_decision_hash:'a'.repeat(64),execution_token_hash:'b'.repeat(64),expected_target_count:74,observed_target_count:74,preflight_classification_counts:{MATCH:74},rows_updated:74,idempotent_noop_count:0,audit_events_inserted:74,postflight_result:'PASS',token_consumption_result:'CONSUMED',transaction_outcome:'COMMITTED',unauthorized_row_count:0,unauthorized_column_count:0,application_mutation_count:74,rollback_mutation_count:0,full_content_persisted:false,cleanup_result:'COMPLETE',reconciliation_state:'STAGING_EXECUTION_COMMITTED'});expect((await validateEvidence(e)).rows_updated).toBe(74);await expect(validateEvidence({...e,rows_updated:73})).rejects.toThrow(/hash/);const leaked={...e,redacted_database_identity:{password:'x'}};delete leaked.execution_evidence_sha256;const {canonicalJsonSha256FromValue}=await import('../../scripts/content_pipeline/hash_utils.mjs');leaked.execution_evidence_sha256=canonicalJsonSha256FromValue(leaked);await expect(validateEvidence(leaked)).rejects.toThrow(/leakage/);await rm(evidencePath,{force:true})})
 it('generates deterministically and validates all upstream hashes',async()=>{await build();const one=await canonicalJsonSha256('content/migration/reading-segment-reviewed-boundary-staging-execution-manifest.json');await build();expect(await canonicalJsonSha256('content/migration/reading-segment-reviewed-boundary-staging-execution-manifest.json')).toBe(one);expect((await validate()).expected_target_count).toBe(74)})
 it('bare execute and reconcile fail before connection',()=>{for(const p of ['execute_reviewed_boundary_staging_application.mjs','reconcile_reviewed_boundary_staging_application.mjs']){const r=spawnSync(process.execPath,[`scripts/content_pipeline/${p}`],{encoding:'utf8'});expect(r.status).not.toBe(0);expect(r.stderr).toMatch(/blocked default/)}})
 it('declares deterministic locking, status-only SQL and rollback separation',async()=>{const tx=await readFile('content/migration/reading-segment-reviewed-boundary-staging-execution-transaction-contract.json','utf8');const lock=await readFile('content/migration/reading-segment-reviewed-boundary-staging-execution-locking-contract.json','utf8');const code=await readFile('scripts/content_pipeline/execute_reviewed_boundary_staging_application.mjs','utf8');expect(tx).toMatch(/all_or_nothing/);expect(lock).toMatch(/FOR UPDATE/);expect(code).toMatch(/SET approval_status=\$1/);expect(code).not.toMatch(/SET updated_at|SET content|SET start_locator/);expect(await readFile('content/migration/reading-segment-reviewed-boundary-staging-execution-rollback-distinction-contract.json','utf8')).toMatch(/future_distinct_token/)} )
})
