import {describe,it,expect} from 'vitest'
import {readFile} from 'node:fs/promises'
import {execFileSync} from 'node:child_process'
import {createHash} from 'node:crypto'
import {validate} from '../../scripts/content_pipeline/validate_reviewed_boundary_application_rollback.mjs'
const load=async n=>JSON.parse(await readFile(`content/migration/reading-segment-reviewed-boundary-application-rollback-${n}.json`,'utf8'))
const eventKey=x=>{const f=[['package_id',x.package_id],['event_action',x.event_action],['run_id',x.run_id],['decision_id',x.decision_id],['book_id',String(x.book_id)],['segment_key',x.segment_key],['event_version',String(x.event_version)]];return createHash('sha256').update('sha256-v1-length-delimited-reviewed-boundary-event-key'+f.map(([k,v])=>`|${k}=${String(v).length}:${v}`).join('')).digest('hex')}
describe('PR-0057 guarded application and rollback',()=>{
 it('independently validates the closed world',async()=>expect(await validate()).toMatchObject({valid:true,authorized_decisions:74,duplicate_targets:0}))
 it('contains exactly 74 symmetric operations and unique, distinct keys',async()=>{const a=(await load('application-operations')).operations,r=(await load('rollback-operations')).operations;expect(a).toHaveLength(74);expect(r).toHaveLength(74);expect(new Set(a.map(x=>x.event_key)).size).toBe(74);expect(new Set(r.map(x=>x.rollback_event_key)).size).toBe(74);a.forEach((x,i)=>{expect(x.event_key).toBe(eventKey(x));expect(r[i].rollback_event_key).toBe(eventKey({...x,event_action:'status-rollback'}));expect(x.event_key).not.toBe(r[i].rollback_event_key);expect(r[i].application_event_key).toBe(x.event_key)})})
 it('permits approval_status only and rejects incomplete authority',async()=>{const p=await load('policy'),g=await load('execution-gate'),ready=await load('application-readiness-evidence');expect(p.only_permitted_mutation).toEqual(['approval_status']);expect(g.application_execution_authorized).toBe(false);expect(g.rollback_execution_authorized).toBe(false);expect(ready).toMatchObject({source_snapshot_complete:false,source_snapshot_verified:false,application_preflight_ready:false,rollback_baseline_ready:false})})
 it('defines blocking drift, inconsistent retry, atomic abort and postflight',async()=>{const pre=await load('preflight-contract'),idem=await load('idempotency-contract'),tx=await load('transaction-contract'),post=await load('postflight-contract');for(const c of ['BOUNDARY_DRIFT','CONTENT_DRIFT','STORED_CONTENT_DIGEST_MISMATCH','SOURCE_HASH_DRIFT','DUPLICATE_TARGET','UNAUTHORIZED_TARGET','INSUFFICIENT_BASELINE','AUDIT_EVENT_CONFLICT'])expect(pre.classifications[c].transaction_must_abort).toBe(true);expect(idem.inconsistent_states).toHaveLength(6);expect(tx.atomicity).toContain('all-or-nothing');expect(post.failure).toContain('abort')})
 it('generates deterministically with no database connection or mutation',async()=>{execFileSync(process.execPath,['scripts/content_pipeline/build_reviewed_boundary_application_rollback.mjs']);const before=execFileSync('git',['diff','--','content/migration/reading-segment-reviewed-boundary-application-rollback-*.json']).toString();execFileSync(process.execPath,['scripts/content_pipeline/build_reviewed_boundary_application_rollback.mjs']);const after=execFileSync('git',['diff','--','content/migration/reading-segment-reviewed-boundary-application-rollback-*.json']).toString();expect(after).toBe(before)})
})
