import {describe,it,expect} from 'vitest';import {readFile} from 'node:fs/promises';import {normalizeReviewedBoundaryContent,recomputeNormalizedContentSha256} from '../../scripts/content_pipeline/reviewed_boundary_content_normalization.mjs';import {validateMode,reconstructRow,classifyTarget,reconcileAudit,evidenceHash,containsForbidden} from '../../scripts/content_pipeline/reviewed_boundary_runtime_integrity.mjs'
const hash='a'.repeat(64),expected={run_id:'00000000-0000-0000-0000-000000000001',book_id:1,segment_key:'a'.repeat(20),segment_order:1,current_approval_status:'boundary-review',intended_resulting_approval_status:'content-review'};const content='Café text\n';const digest=recomputeNormalizedContentSha256(content);const row={...expected,source_key:'b'.repeat(16),segment_index:1,segment_count:1,boundary_version:1,start_locator:{p:1},end_locator:{p:2},display_title:'Title',content,word_count:2,normalized_content_sha256:digest,approval_status:'boundary-review',created_at:'x',updated_at:'y'}
describe('runtime mode gate',()=>{it('defaults blocked',()=>expect(()=>validateMode({})).toThrow('RUNTIME_MODE_BLOCKED'));it('accepts fixture explicitly',()=>expect(validateMode({mode:'fixture',environment:'fixture',operatorConfirmation:'yes',packageManifestHash:hash})).toBe(true));it('accepts staging contract',()=>expect(validateMode({mode:'staging-readonly',environment:'staging',operatorConfirmation:'yes',packageManifestHash:hash})).toBe(true));it('rejects production',()=>expect(()=>validateMode({mode:'production-readonly',environment:'production',operatorConfirmation:'yes',packageManifestHash:hash})).toThrow('production'));it('requires confirmation and hash',()=>{expect(()=>validateMode({mode:'fixture',environment:'fixture',packageManifestHash:hash})).toThrow('confirmation');expect(()=>validateMode({mode:'fixture',environment:'fixture',operatorConfirmation:'yes'})).toThrow('manifest')});it('rejects identity mismatch',()=>expect(()=>validateMode({mode:'staging-readonly',environment:'production',operatorConfirmation:'yes',packageManifestHash:hash})).toThrow('DATABASE_IDENTITY_MISMATCH'))})
describe('normalization and classification',()=>{it.each([['LF/CRLF','a\r\nb','a\nb'],['NFC','Cafe\u0301','Café'],['NBSP','a\u00a0b','a b'],['whitespace',' a  \t b  ','a b'],['blank lines','\n\na\n\n\n\nb\n','a\n\nb']])('%s equivalence',(_,a,b)=>expect(normalizeReviewedBoundaryContent(a)).toBe(normalizeReviewedBoundaryContent(b)));it('detects same length and same word count content change',()=>expect(recomputeNormalizedContentSha256('one two')).not.toBe(recomputeNormalizedContentSha256('one six')));it('reconstructs actual content without persisting it',()=>{const x=reconstructRow(row,expected);expect(x.recomputed_normalized_content_sha256).toBe(digest);expect(x.recomputed_word_count).toBe(2);expect(x.content).toBeUndefined();expect(classifyTarget(x,expected)).toBe('MATCH')});it('classifies drift and status',()=>{const x=reconstructRow(row,expected);expect(classifyTarget({...x,stored_digest_matches_recomputed:false},expected)).toBe('STORED_CONTENT_DIGEST_MISMATCH');expect(classifyTarget({...x,segment_order:2},expected)).toBe('BOUNDARY_DRIFT');expect(classifyTarget({...x,observed_approval_status:'content-review'},expected)).toBe('STATUS_ALREADY_APPLIED');expect(classifyTarget({...x,observed_approval_status:'draft'},expected)).toBe('STATUS_UNEXPECTED');expect(classifyTarget(null,expected)).toBe('IDENTITY_MISSING')})})
describe('audit and evidence safety',()=>{it('reconciles audit states',()=>{expect(reconcileAudit([],'boundary-review')).toBe('NO_APPLICATION_EVENT');expect(reconcileAudit([{event_action:'status-advanced'}],'content-review')).toBe('MATCHING_APPLICATION_EVENT');expect(reconcileAudit([{event_action:'status-advanced'}],'boundary-review')).toBe('APPLICATION_EVENT_STATUS_NOT_APPLIED');expect(reconcileAudit([],'content-review')).toBe('APPLIED_STATUS_EVENT_ABSENT');expect(reconcileAudit([{event_action:'status-advanced',conflict:true}],'content-review')).toBe('CONFLICTING_APPLICATION_EVENT');expect(reconcileAudit([{event_action:'status-rollback'}],'boundary-review')).toBe('UNEXPECTED_ROLLBACK_EVENT')});it('rejects secret/full content shapes',()=>{expect(containsForbidden({password:'x'})).toBe(true);expect(containsForbidden({content:'full'})).toBe(true);expect(containsForbidden({safe:'x'})).toBe(false)});it('hash is deterministic',()=>{const e={x:1};expect(evidenceHash(e)).toBe(evidenceHash(e))});it('collector declares read only and safe parameterization',async()=>{const s=await readFile('scripts/content_pipeline/collect_reviewed_boundary_runtime_integrity.mjs','utf8');expect(s).toContain("client.query('BEGIN TRANSACTION READ ONLY')");expect(s).not.toMatch(/FOR UPDATE/i);expect(s).toContain('params');expect(s).not.toMatch(/UPDATE content_staging\.reading_segments|INSERT INTO content_staging\.migration_audit_events/i)})})

import {beforeAll} from 'vitest'
import {canonicalJsonSha256} from '../../scripts/content_pipeline/hash_utils.mjs'
import {finalizeEvidence} from '../../scripts/content_pipeline/reviewed_boundary_runtime_integrity.mjs'
import {validateEvidence,recomputeEvidenceHash} from '../../scripts/content_pipeline/validate_reviewed_boundary_runtime_integrity_evidence.mjs'
import {paths,classes,evidenceHashContract} from '../../scripts/content_pipeline/reviewed_boundary_runtime_integrity_constants.mjs'
let validEvidence
const clone=value=>structuredClone(value)
beforeAll(async()=>{const manifest=JSON.parse(await readFile(paths.manifest,'utf8'));const targetDoc=JSON.parse(await readFile('content/migration/reading-segment-reviewed-boundary-content-integrity-targets.json','utf8'));const counts=Object.fromEntries(classes.map(x=>[x,x==='MATCH'?74:0]));validEvidence=finalizeEvidence({evidence_schema_version:'pr0058-runtime-evidence-v1',evidence_hash_contract:evidenceHashContract,package_id:'reading-segment-reviewed-boundary-runtime-integrity-pr0058',package_version:'1.0.0',runtime_execution_identifier:'unit-fixture',collector_mode:'fixture',environment_name:'fixture',redacted_database_identity:{fingerprint_sha256:'1'.repeat(64),database_name_sha256:'2'.repeat(64)},postgresql_version:'15.0',schema_fingerprint:'fixture-schema',package_manifest_hash:await canonicalJsonSha256(paths.manifest),source_input_hashes:manifest.source_hashes,expected_target_count:74,observed_target_count:74,missing_target_count:0,duplicate_target_count:0,unauthorized_target_count:0,classification_counts:counts,complete_integrity_baseline_count:74,digest_match_count:74,digest_mismatch_count:0,boundary_drift_count:0,content_drift_count:0,status_match_count:74,already_applied_count:0,unexpected_status_count:0,audit_consistency_counts:{NO_APPLICATION_EVENT:74},package_preflight_result:'STAGING_PREFLIGHT_MATCHED',read_only_transaction_result:'READ_ONLY_ROLLED_BACK',application_mutation_count:0,rollback_mutation_count:0,audit_insertion_count:0,full_content_persisted:false,unauthorized_mutation_count:0,cleanup_result:'COMPLETE',targets:targetDoc.records.map(x=>({decision_id:x.decision_id,run_id:x.run_id,book_id:x.book_id,segment_key:x.segment_key,created_at:null,updated_at:'2026-08-06T00:00:00.000Z'}))})})
const fails=async mutate=>{const e=clone(validEvidence);mutate(e);await expect(validateEvidence(e)).rejects.toThrow()}
describe('canonical runtime evidence hashing',()=>{
 it('accepts a valid independently verified hash',async()=>expect(await validateEvidence(validEvidence)).toBe(true))
 it('excludes only evidence_sha256 from self-hashing',()=>{const e=clone(validEvidence);e.evidence_sha256='0'.repeat(64);expect(recomputeEvidenceHash(e)).toBe(validEvidence.evidence_sha256)})
 it('detects changed scalar, nested, timestamp, execution id, and cleanup fields',async()=>{await fails(e=>e.postgresql_version='15.1');await fails(e=>e.redacted_database_identity.fingerprint_sha256='3'.repeat(64));await fails(e=>e.targets[0].updated_at='2026-08-07T00:00:00.000Z');await fails(e=>e.runtime_execution_identifier='changed');await fails(e=>e.cleanup_result='FAILED')})
 it('preserves meaningful array order',async()=>fails(e=>e.targets.reverse()))
 it('ignores object insertion order',()=>{const e=Object.fromEntries(Object.entries(validEvidence).reverse());expect(recomputeEvidenceHash(e)).toBe(validEvidence.evidence_sha256)})
 it('keeps null hash-significant',async()=>fails(e=>e.targets[0].created_at='not-null'))
 it('rejects omitted and extra fields',async()=>{await fails(e=>delete e.cleanup_result);await fails(e=>e.alternate_projection='forbidden')})
 it('rejects stale, uppercase, and malformed digests',async()=>{await fails(e=>e.evidence_sha256='0'.repeat(64));await fails(e=>e.evidence_sha256=e.evidence_sha256.toUpperCase());await fails(e=>e.evidence_sha256='abc')})
 it('detects mutation after hashing and unrelated manifest refresh',async()=>{await fails(e=>e.status_match_count=73);await fails(e=>{e.package_manifest_hash='f'.repeat(64);e.targets[0].updated_at='corrupt'})})
 it('is unaffected by LF or CRLF JSON formatting',()=>{const lf=JSON.stringify(validEvidence,null,2)+'\n';const crlf=lf.replace(/\n/g,'\r\n');expect(recomputeEvidenceHash(JSON.parse(lf))).toBe(recomputeEvidenceHash(JSON.parse(crlf)))})
 it('generates deterministic evidence twice',()=>{const projection=clone(validEvidence);delete projection.evidence_sha256;expect(finalizeEvidence(projection).evidence_sha256).toBe(finalizeEvidence(clone(projection)).evidence_sha256)})
 it('rejects secrets, full content, nonzero mutations, and missing read-only result',async()=>{await fails(e=>e.targets[0].password='x');await fails(e=>e.targets[0].content='full');await fails(e=>e.application_mutation_count=1);await fails(e=>e.rollback_mutation_count=1);await fails(e=>e.audit_insertion_count=1);await fails(e=>e.unauthorized_mutation_count=1);await fails(e=>delete e.read_only_transaction_result)})
})
