import { describe, it, expect } from 'vitest'
import { readFile } from 'node:fs/promises'
import { build } from '../../scripts/content_pipeline/build_reviewed_boundary_execution_authority.mjs'
import { validate, reconstructAuditSchema } from '../../scripts/content_pipeline/validate_reviewed_boundary_execution_authority.mjs'
import { artifactPaths, historicalPaths } from '../../scripts/content_pipeline/reviewed_boundary_execution_authority_constants.mjs'
const j=async p=>JSON.parse(await readFile(p,'utf8'))
const arts=async()=>Object.fromEntries(await Promise.all(Object.entries(artifactPaths).filter(([,p])=>p.endsWith('.json')).map(async([k,p])=>[k,await j(p)])))
const hist=async p=>JSON.parse(await readFile(p,'utf8'))
const createSql=`create table if not exists content_staging.migration_audit_events (id bigint generated always as identity primary key, run_id uuid not null references content_staging.migration_runs(id) on delete cascade, event_type text not null, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());`

describe('PR-0054 builder determinism',()=>{it('builds deterministically',async()=>expect(await build()).toEqual(await build()))})
describe('PR-0054 independent validator',()=>{
 it('validates independently without PR-0054 builder imports',async()=>await expect(validate()).resolves.toMatchObject({public_decisions:144,authorized_targets:74,excluded_decisions:70,validator_imports_builder_functions:false}))
 it('resists shared count/approval defects',async()=>{const a=await arts(); a.policy.authorized_target_count=73; a.evidence.totals.authorized_status_only_decisions=73; await expect(validate({artifacts:a})).rejects.toThrow(/authorized|evidence|policy/); a.policy.execution_authority_approved=true; a.manifest.execution_authority_approved=true; await expect(validate({artifacts:a})).rejects.toThrow(/approval|policy/)})
 it('resists shared omitted target and fabricated hash defects',async()=>{const a=await arts(); a.baselinePlan.records.pop(); a.baselineEvidence.records.pop(); await expect(validate({artifacts:a})).rejects.toThrow(/baseline target count/); const b=await arts(); b.baselinePlan.records[0].expected_stored_hash='0'.repeat(64); await expect(validate({artifacts:b})).rejects.toThrow(/fabricated/)})
 it('resists invented audit uniqueness, conflict, timestamp, and payload authority',async()=>{const a=await arts(); a.schema.unique_constraints.push(['run_id','event_type']); a.audit.uniqueness_rule='unique'; await expect(validate({artifacts:a})).rejects.toThrow(/schema artifact drift|unique/); const b=await arts(); b.audit.conflict_behavior='ON CONFLICT DO NOTHING'; await expect(validate({artifacts:b})).rejects.toThrow(/audit contract/); const c=await arts(); c.audit.timestamp_behavior='caller supplied'; await expect(validate({artifacts:c})).rejects.toThrow(/audit contract/); const d=await arts(); d.audit.payload_schema.details.actor='text'; await expect(validate({artifacts:d})).rejects.toThrow(/payload/)})
 it('resists rollback gate invention and approval drift',async()=>{const a=await arts(); a.gate.repository_mechanism_found=true; a.rollback.approved=true; await expect(validate({artifacts:a})).rejects.toThrow(/rollback/)})
 it('detects historical authority drift',async()=>{const h={}; h[historicalPaths.statusPlan]=await hist(historicalPaths.statusPlan); h[historicalPaths.statusPlan].authorized_decisions.pop(); await expect(validate({historical:h})).rejects.toThrow(/PR-0049/); const p={}; p[historicalPaths.pr0053Plan]=await hist(historicalPaths.pr0053Plan); p[historicalPaths.pr0053Plan].application_records.pop(); await expect(validate({historical:p})).rejects.toThrow(/PR-0053/); const r={}; r[historicalPaths.pr0053Plan]=await hist(historicalPaths.pr0053Plan); r[historicalPaths.pr0053Plan].application_records[0].expected_run_id='00000000-0000-0000-0000-000000000000'; await expect(validate({historical:r})).rejects.toThrow(/run ID/); const t={}; t[historicalPaths.pr0053Plan]=await hist(historicalPaths.pr0053Plan); t[historicalPaths.pr0053Plan].application_records[0].authorized_replacement_approval_status='approved'; await expect(validate({historical:t})).rejects.toThrow(/transition/)})
 it('detects duplicate public decisions and exclusion union gaps',async()=>{const p='content/migration/reading-segment-source-review-pilot-decisions.json'; const h={}; h[p]=await hist(p); h[p].decisions[1].decision_id=h[p].decisions[0].decision_id; await expect(validate({historical:h})).rejects.toThrow(/duplicate public/); const e={}; e[historicalPaths.pr0053Exclusions]=await hist(historicalPaths.pr0053Exclusions); e[historicalPaths.pr0053Exclusions].exclusions.pop(); await expect(validate({historical:e})).rejects.toThrow(/PR-0053/)})
 it('reconstructs audit migration operations in lexical order',async()=>{const files={'002.sql':'alter table content_staging.migration_audit_events add column x text;','001.sql':createSql,'003.sql':'create unique index ux on content_staging.migration_audit_events(run_id); create trigger tr after insert on content_staging.migration_audit_events execute function f(); create or replace function f() returns trigger language plpgsql as $$ begin return new; end $$;','000.sql':'select 1;'}; const s=await reconstructAuditSchema({files}); expect(s.migrations_scanned).toEqual(['000.sql','001.sql','002.sql','003.sql']); expect(s.migrations_relevant).toEqual(['001.sql','002.sql','003.sql']); expect(s.later_schema_operations).toHaveLength(1); expect(s.indexes[0].unique).toBe(true); expect(s.triggers).toHaveLength(1); expect(s.trigger_functions).toHaveLength(1)})
 it('fails on conflicting or missing audit create-table authority',async()=>{await expect(reconstructAuditSchema({files:{'001.sql':createSql,'002.sql':createSql}})).rejects.toThrow(/conflicting/); await expect(reconstructAuditSchema({files:{'001.sql':'select 1;'}})).rejects.toThrow(/missing/)})
 it('rejects duplicate/missing/extra baseline and coverage/leakage defects',async()=>{const a=await arts(); a.baselinePlan.records.push(a.baselinePlan.records[0]); await expect(validate({artifacts:a})).rejects.toThrow(/baseline/); const b=await arts(); b.baselinePlan.target_count=73; await expect(validate({artifacts:b})).rejects.toThrow(/baseline|hash/); const c=await arts(); c.evidence.content_integrity.stored_hashes=1; await expect(validate({artifacts:c})).rejects.toThrow(/evidence/); const d=await arts(); d.evidence.connection='postgres://secret'; await expect(validate({artifacts:d})).rejects.toThrow(/forbidden/)})
 it('rejects manifest and safety defects',async()=>{const a=await arts(); delete a.manifest.artifact_hashes.policy_sha256; await expect(validate({artifacts:a})).rejects.toThrow(/manifest/); const b=await arts(); b.manifest.artifact_hashes.extra_sha256='x'; await expect(validate({artifacts:b})).rejects.toThrow(/manifest/); const c=await arts(); c.evidence.historical_hashes.pr0053_plan='x'; await expect(validate({artifacts:c})).rejects.toThrow(/historical|evidence/); const d=await arts(); d.policy.safety_assertions.sql_executed=true; await expect(validate({artifacts:d})).rejects.toThrow(/sql_executed/)})
})
