import { mkdir, writeFile, readFile, readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { join } from 'node:path'
import { canonicalJsonSha256, canonicalJsonSha256FromValue } from './hash_utils.mjs'
import { artifactPaths as paths, historicalPaths, migrationsDir, packageIds, hashAlgorithms, safetyKeys, statuses, targetIdentityColumns, changedColumns } from './reviewed_boundary_execution_authority_constants.mjs'

const safety=Object.fromEntries(safetyKeys.map(k=>[k,false]))
const readJson=async p=>JSON.parse(await readFile(p,'utf8'))
const textSha=async p=>createHash('sha256').update((await readFile(p,'utf8')).replace(/\r\n?/g,'\n'),'utf8').digest('hex')
const dist=(xs,k)=>xs.reduce((a,x)=>((a[x[k]]=(a[x[k]]??0)+1),a),{})
const bodyOf=(sql,re)=>{const i=sql.search(re); if(i<0)return null; const open=sql.indexOf('(',i); let d=0; for(let p=open;p<sql.length;p++){ if(sql[p]==='(')d++; if(sql[p]===')'&&--d===0)return sql.slice(open+1,p)} return null}
const splitTop=s=>{const out=[]; let d=0,q=false,cur=''; for(const ch of s){ if(ch==="'")q=!q; if(!q&&ch==='(')d++; if(!q&&ch===')')d--; if(!q&&d===0&&ch===','){out.push(cur.trim()); cur=''} else cur+=ch } if(cur.trim())out.push(cur.trim()); return out}

export async function discoverAuditSchema(dir=migrationsDir){
  const files=(await readdir(dir)).filter(f=>f.endsWith('.sql')).sort().map(f=>join(dir,f))
  const schema={table_exists:false,table:'content_staging.migration_audit_events',source_migration:null,migrations_scanned:files,migrations_relevant:[],columns:[],primary_key:null,foreign_keys:[],unique_constraints:[],indexes:[],triggers:[],trigger_functions:[],rls_or_grants:{schema_revoked_from:[],table_grants_discovered:[]},later_schema_operations:[],unsupported_later_schema_changes:false}
  for(const f of files){
    const sql=await readFile(f,'utf8')
    const relevant=/migration_audit_events|revoke all on schema content_staging|grant .*content_staging|create\s+(or\s+replace\s+)?function|create\s+trigger|drop\s+trigger/i.test(sql)
    if(!relevant) continue
    schema.migrations_relevant.push(f)
    for(const role of ['public','anon','authenticated']) if(new RegExp(`revoke all on schema content_staging from ${role}`,'i').test(sql)) schema.rls_or_grants.schema_revoked_from.push(role)
    const creates=/create\s+table\s+if\s+not\s+exists\s+content_staging\.migration_audit_events/i.test(sql)
    if(creates){
      if(schema.table_exists) throw new Error('conflicting audit create-table authority')
      schema.table_exists=true; schema.source_migration=f
      const body=bodyOf(sql,/create\s+table\s+if\s+not\s+exists\s+content_staging\.migration_audit_events/i)
      for(const part of splitTop(body)){ const l=part.toLowerCase()
        if(l.startsWith('id ')){ schema.columns.push({name:'id',type:'bigint',nullable:!/not null/.test(l),default:/generated always as identity/.test(l)?'generated always as identity':null}); if(/primary key/.test(l))schema.primary_key=['id'] }
        else if(l.startsWith('run_id ')){ schema.columns.push({name:'run_id',type:'uuid',nullable:!/not null/.test(l),default:null}); if(/references\s+content_staging\.migration_runs\s*\(\s*id\s*\)/.test(l))schema.foreign_keys.push({columns:['run_id'],references:'content_staging.migration_runs(id)',on_delete:/on delete cascade/.test(l)?'cascade':null}) }
        else if(l.startsWith('event_type ')) schema.columns.push({name:'event_type',type:'text',nullable:!/not null/.test(l),default:null})
        else if(l.startsWith('details ')) schema.columns.push({name:'details',type:'jsonb',nullable:!/not null/.test(l),default:/default\s+'\{\}'::jsonb/.test(l)?"'{}'::jsonb":null})
        else if(l.startsWith('created_at ')) schema.columns.push({name:'created_at',type:'timestamptz',nullable:!/not null/.test(l),default:/default\s+now\(\)/.test(l)?'now()':null})
        else if(/unique\s*\(/.test(l)) schema.unique_constraints.push(part)
      }
    }
    const withoutCreate=creates?sql.replace(/create\s+table\s+if\s+not\s+exists\s+content_staging\.migration_audit_events[\s\S]*?;[\s\S]*/i,''):sql
    if(/alter\s+table[\s\S]*migration_audit_events/i.test(withoutCreate)){schema.later_schema_operations.push({file:f,operation:'alter-table'}); schema.unsupported_later_schema_changes=true}
    for(const m of sql.matchAll(/create\s+(unique\s+)?index[^;]*migration_audit_events[^;]*;/ig)) schema.indexes.push({file:f,unique:!!m[1],sql:m[0].replace(/\s+/g,' ').trim()})
    for(const m of sql.matchAll(/create\s+trigger[^;]*migration_audit_events[^;]*;/ig)) schema.triggers.push({file:f,sql:m[0].replace(/\s+/g,' ').trim()})
    for(const m of sql.matchAll(/create\s+or\s+replace\s+function\s+([^\s(]+)/ig)) if(/migration_audit_events/i.test(sql)||schema.triggers.length) schema.trigger_functions.push({file:f,name:m[1]})
  }
  if(!schema.table_exists) throw new Error('missing audit create-table authority')
  return schema
}

export async function deriveAuthority(){
  const plan=await readJson(historicalPaths.pr0053Plan), excl=await readJson(historicalPaths.pr0053Exclusions), auditSchema=await discoverAuditSchema()
  const records=[...plan.application_records].sort((a,b)=>a.decision_id.localeCompare(b.decision_id))
  if(records.length!==74) throw new Error('expected 74 targets')
  if(new Set(records.map(r=>`${r.expected_run_id}:${r.book_id}:${r.segment_key}:${r.decision_id}`)).size!==74) throw new Error('duplicate targets')
  const baselines=records.map(r=>({decision_id:r.decision_id,run_id:r.expected_run_id,book_id:r.book_id,segment_key:r.segment_key,segment_order:r.segment_order,expected_current_status:statuses.from,expected_replacement_status:statuses.to,stored_hash_field:'normalized_content_sha256',expected_stored_hash:null,stored_hash_authority_artifact:null,independent_content_hash:null,independent_hash_authority_artifact:null,normalization_algorithm:'repository normalized content algorithm for staged reading_segments.content; exact implementation not present for these targets',hash_algorithm:'sha256',expected_content_length:null,expected_word_count:null,locator_hash:canonicalJsonSha256FromValue({start_locator:r.start_locator??null,end_locator:r.end_locator??null,identity:r.target_row_identity}),baseline_completeness:false,exact_missing_evidence:['repository artifact containing target content is unavailable','expected stored normalized_content_sha256 unavailable without database snapshot','independent recomputation from authoritative source text cannot be performed without copying/accessing source text'],application_eligibility_under_execution_contract:false}))
  const missing=[{id:'audit-event-stable-identity',status:'blocking',requirement:'Add or authorize a stable uniqueness rule for one immutable event per decision; existing audit table has only identity id and no unique key over run_id/event_type/details.'},{id:'audit-conflict-behavior',status:'blocking',requirement:'Authorize exact duplicate event conflict behavior; ON CONFLICT cannot be repository-grounded without a unique constraint.'},{id:'rollback-downstream-gate',status:'blocking',requirement:'Define a repository-verifiable gate proving no downstream content-review work depends on these rows, or explicitly approve no rollback.'},{id:'content-integrity-baselines',status:'blocking',requirement:'Provide per-target stored normalized_content_sha256 and independently recomputable content artifacts for all 74 targets.'}]
  const policy={schema_version:'pr0054-reviewed-boundary-execution-authority-policy-v1',package_id:packageIds.pr0054,authority_for_package:packageIds.pr0053,execution_authority_approved:false,approval_result:'blocked',run_id:plan.run_id,target_table:plan.target_table,target_identity_columns:targetIdentityColumns,authorized_target_count:records.length,excluded_decision_count:excl.excluded_decision_count,authorized_transition:{column:'approval_status',from:statuses.from,to:statuses.to},changed_columns:changedColumns,preserved_columns:records[0].unchanged_columns,safety_assertions:safety}
  const audit={schema_version:'pr0054-reviewed-boundary-execution-audit-contract-v1',approved:false,exact_audit_table:auditSchema.table,event_granularity:'one event per authorized decision preferred but blocked by missing stable uniqueness',event_type:'reading-segment-reviewed-boundary.status-advanced',event_version:1,migration_package_id:policy.package_id,run_id:plan.run_id,event_identity:{database_primary_key:'id generated by database; not deterministic',required_stable_identity:'blocked; schema lacks unique deterministic event identity'},payload_schema:{details:{package_id:'text',event_version:'integer',decision_id:'text',book_id:'integer',segment_key:'text',before_state:{approval_status:statuses.from},after_state:{approval_status:statuses.to}}},timestamp_behavior:'created_at generated by database default now() at insert time',uniqueness_rule:'blocked: no table uniqueness constraint for event identity',duplicate_event_behavior:'blocked: duplicates cannot be prevented by schema',conflict_behavior:'blocked: ON CONFLICT target unavailable',transaction_success_relationship:'events must be inserted in same transaction as row updates only after all preconditions pass',rollback_event_behavior:'blocked until rollback gate and event identity are authorized'}
  const idempotency={schema_version:'pr0054-reviewed-boundary-execution-idempotency-contract-v1',approved:false,state_A_first_application:{accepted_when:['74 targets exist exactly once','all status boundary-review','zero matching audit events','package hashes match','content baselines match'],result:['74 rows content-review','74 audit events','exact row/event assertions']},state_B_complete_safe_repeat:{chosen_behavior:'verified no-op success would be safest, but remains blocked until stable audit identity exists'},state_C_partial_prior_application:'fail closed; no remaining-row-only updates',state_D_unexpected_state:'abort',error_categories:['TARGET_MISSING','TARGET_DUPLICATE','STATUS_UNEXPECTED','HASH_MISMATCH','EXCLUDED_DECISION_PRESENT','AUDIT_CONFLICT','PACKAGE_ID_MISMATCH','RUN_ID_MISMATCH','PARTIAL_APPLICATION']}
  const rollback={schema_version:'pr0054-reviewed-boundary-execution-rollback-contract-v1',approved:false,eligible_target_count:74,transition:{column:'approval_status',from:statuses.rollbackFrom,to:statuses.rollbackTo},preserved_columns:records[0].unchanged_columns,required_current_state:'all 74 content-review with matching application audit events and no downstream dependency evidence',rollback_event_semantics:'blocked by audit uniqueness and downstream gate',idempotency:'blocked; complete repeat and partial rollback must fail closed until gate exists',row_count_assertions:{targets:74,updated_rows:74},audit_count_assertions:{application_events:74,rollback_events:'blocked'},transaction_behavior:'single transaction, preconditions before mutation, rollback on any failure',migration_run_status_behavior:'blocked; no exact status transition authority for migration_runs',prohibition_conditions:['missing downstream gate','missing audit identity','partial state','unexpected row status']}
  const gate={schema_version:'pr0054-reviewed-boundary-execution-rollback-gate-v1',approved:false,result:'blocked',searched_for:['content-review downstream approval/edit/audit events','migration_runs.status downstream package registration','reader progress/session/bookmark/note/highlight dependencies'],repository_mechanism_found:false,required_gate:'prove no later content-review approval/edit/audit event or downstream package registration depends on these rows'}
  const baselinePlan={schema_version:'pr0054-reviewed-boundary-content-integrity-baselines-v1',approved:false,target_count:74,stored_hash_expected_count:0,independent_hash_expected_count:0,complete_baseline_count:0,missing_baseline_count:74,normalization_algorithm:'blocked: exact per-target content-normalization source artifact unavailable',hash_algorithm:'sha256',records:baselines}
  const preconditions={schema_version:'pr0054-reviewed-boundary-execution-preconditions-v1',approved:false,required:['exact 74 target membership','exact boundary-review current status','exact content baselines for all 74','zero duplicate audit events','package/hash authority matches'],blocking:['content baseline coverage','audit uniqueness/conflict authority','rollback gate']}
  const transaction={schema_version:'pr0054-reviewed-boundary-execution-transaction-contract-v1',approved:false,semantics:'single transaction; acquire deterministic lock if later authorized; perform all checks before mutation; assert 74 row updates and 74 audit inserts; abort rolls back all changes',mutation_before_checks_allowed:false,sql_generated:false}
  const failure={schema_version:'pr0054-reviewed-boundary-execution-failure-semantics-v1',approved:false,fail_closed:true,errors:idempotency.error_categories,partial_state_reconciliation:'not authorized',required_effect:'no partial database state after transaction failure'}
  const evidence={schema_version:'pr0054-reviewed-boundary-execution-authority-evidence-v1',execution_authority_approved:false,totals:{public_decisions:144,authorized_status_only_decisions:74,excluded_decisions:70},authorized_outcomes:dist(records,'final_outcome'),excluded_outcomes:dist(excl.exclusions,'final_outcome'),content_integrity:{target_count:74,stored_hashes:0,independent_hashes:0,complete:0,missing:74,matches:0,mismatches:0,null_or_missing:74},audit_schema:auditSchema,safety_assertions:safety,historical_hashes:{pr0053_plan:await canonicalJsonSha256(historicalPaths.pr0053Plan),pr0053_manifest:await canonicalJsonSha256(historicalPaths.pr0053Manifest),audit_migration:await textSha(auditSchema.source_migration)}}
  const missingArtifact={schema_version:'pr0054-reviewed-boundary-execution-missing-authority-v1',execution_authority_approved:false,missing_authority:missing,safety_assertions:safety}
  return {policy,auditSchema,audit,idempotency,state:{schema_version:'pr0054-reviewed-boundary-execution-state-machine-v1',approved:false,states:idempotency},rollback,gate,baselinePlan,baselineEvidence:{schema_version:'pr0054-reviewed-boundary-content-integrity-evidence-v1',records:baselines,source_text_included:false},preconditions,transaction,failure,missingArtifact,evidence}
}

export async function build(){
  await mkdir('content/migration/reports',{recursive:true}); await mkdir('docs/content-pipeline',{recursive:true})
  const a=await deriveAuthority(); const map={policy:a.policy,audit:a.audit,schema:a.auditSchema,idempotency:a.idempotency,state:a.state,rollback:a.rollback,gate:a.gate,baselinePlan:a.baselinePlan,baselineEvidence:a.baselineEvidence,preconditions:a.preconditions,transaction:a.transaction,failure:a.failure,missing:a.missingArtifact,evidence:a.evidence}
  for(const [k,v] of Object.entries(map)) await writeFile(paths[k],JSON.stringify(v,null,2)+'\n')
  const manifest={schema_version:'pr0054-reviewed-boundary-execution-authority-manifest-v1',package_id:packageIds.pr0054,execution_authority_approved:false,hash_algorithms:hashAlgorithms,artifact_hashes:Object.fromEntries(Object.entries(map).map(([k,v])=>[`${k}_sha256`,canonicalJsonSha256FromValue(v)])),safety_assertions:safety}
  await writeFile(paths.manifest,JSON.stringify(manifest,null,2)+'\n')
  const md=`# PR-0054 Reviewed-Boundary Execution Authority\n\nExecution authority approved: false.\n\nThe 74 PR-0053 status-only targets are reproduced exactly, but execution remains blocked because the repository audit table has no stable uniqueness rule, duplicate/conflict behavior is undefined, rollback lacks a downstream gate, and per-target content-integrity baselines cannot be recomputed from repository content artifacts without source text.\n\nSQL generated: false. SQL executed: false. Database modified: false.\n`
  await writeFile(paths.summary,md); await writeFile(paths.docs,md); return manifest
}
if(import.meta.url===`file://${process.argv[1]}`) console.log(JSON.stringify(await build(),null,2))
