import {createHash} from 'node:crypto'
import {readFile,writeFile} from 'node:fs/promises'
import {canonicalJsonSha256,canonicalJsonSha256FromValue} from './hash_utils.mjs'
import {eventKey} from './build_reviewed_boundary_audit_identity.mjs'
import {packageId,packageVersion,sources,names,paths} from './reviewed_boundary_application_rollback_constants.mjs'
const readJson=async p=>JSON.parse(await readFile(p,'utf8'))
const textHash=async p=>createHash('sha256').update((await readFile(p,'utf8')).replace(/\r\n?/g,'\n')).digest('hex')
const sourceHashes=async()=>Object.fromEntries(await Promise.all(Object.entries(sources).map(async([k,p])=>[k,p.endsWith('.json')?await canonicalJsonSha256(p):await textHash(p)])))
export async function derive(){
 const hashes=await sourceHashes(); const [plan,evidence,authority,status,identity,payload,auditConflict,targets,snapshot,drift,rollbackBase,compat,integrityManifest]=await Promise.all([sources.application_plan,sources.application_evidence,sources.execution_authority_manifest,sources.status_only_contract,sources.audit_identity_contract,sources.audit_payload_contract,sources.audit_conflict_contract,sources.integrity_targets,sources.integrity_snapshot,sources.integrity_drift,sources.rollback_baseline,sources.audit_compatibility,sources.integrity_manifest].map(readJson))
 if(evidence.totals?.public_decision_count!==144||drift.classifications?.MATCH?.permits_application!==true||rollbackBase.target_count!==74||compat.compatible!==true) throw Error('upstream package contract mismatch')
 if(plan.authorized_decision_count!==74||plan.application_records.length!==74||targets.target_count!==74||targets.records.length!==74) throw Error('TARGET_SET_MISMATCH: expected exactly 74')
 if(authority.execution_authority_approved!==false||integrityManifest.content_integrity_authority_approved!==false||snapshot.snapshot_complete!==false) throw Error('authority must remain blocked')
 if(status.status_only_contract_approved!==true||identity.event_key_algorithm!=='sha256-v1-length-delimited-reviewed-boundary-event-key'||!payload.details_jsonb_required_fields||!auditConflict.conflict_target) throw Error('authority contract mismatch')
 const p=new Map(plan.application_records.map(r=>[r.decision_id,r])); if(p.size!==74) throw Error('duplicate decision_id')
 const tuple=new Set(); for(const r of plan.application_records){const k=`${r.expected_run_id}:${r.book_id}:${r.segment_key}`; if(tuple.has(k))throw Error('duplicate target');tuple.add(k);if(r.changed_columns.join()!=='approval_status'||r.expected_current_approval_status!=='boundary-review'||r.authorized_replacement_approval_status!=='content-review'||r.application_ready!==true||/merge/.test(r.final_outcome))throw Error(`unauthorized operation ${r.decision_id}`)}
 if(new Set(targets.records.map(r=>r.decision_id)).size!==74)throw Error('duplicate integrity decision'); for(const t of targets.records){const r=p.get(t.decision_id);if(!r||t.run_id!==r.expected_run_id||t.book_id!==r.book_id||t.segment_key!==r.segment_key||t.segment_order!==r.segment_order)throw Error('integrity inventory disagreement')}
 const refs=Object.values(sources); const operations=targets.records.map(t=>{const base={package_id:'reading-segment-reviewed-boundary-execution',package_version:packageVersion,event_version:1,decision_id:t.decision_id,run_id:t.run_id,book_id:t.book_id,segment_key:t.segment_key};return {...base,event_action:'status-advanced',event_key:eventKey({...base,event_action:'status-advanced'}),previous_approval_status:t.current_approval_status,intended_approval_status:t.intended_resulting_approval_status,expected_identity_sha256:t.identity_sha256,expected_boundary_sha256:t.boundary_sha256,expected_content_sha256:t.content_sha256,expected_full_pre_application_sha256:t.full_pre_application_sha256,expected_stored_normalized_content_sha256:t.stored_normalized_content_sha256,expected_recomputed_normalized_content_sha256:t.recomputed_normalized_content_sha256,expected_digest_agreement:t.stored_digest_matches_recomputed,segment_order:t.segment_order,permitted_mutation_columns:['approval_status'],source_artifact_references:refs,source_artifact_hashes:hashes}}).sort((a,b)=>a.run_id.localeCompare(b.run_id)||a.book_id-b.book_id||a.segment_order-b.segment_order||a.segment_key.localeCompare(b.segment_key))
 const rollbacks=operations.map(a=>({package_id:a.package_id,package_version:a.package_version,event_version:1,decision_id:a.decision_id,run_id:a.run_id,book_id:a.book_id,segment_key:a.segment_key,segment_order:a.segment_order,event_action:'status-rollback',application_event_key:a.event_key,rollback_event_key:eventKey({...a,event_action:'status-rollback'}),original_approval_status:a.previous_approval_status,expected_applied_approval_status:a.intended_approval_status,identity_sha256:a.expected_identity_sha256,boundary_sha256:a.expected_boundary_sha256,content_sha256:a.expected_content_sha256,pre_application_sha256:a.expected_full_pre_application_sha256,expected_post_application_state:'status and matching immutable application audit event',matching_application_audit_event_required:true,unresolved_audit_conflict_must_be_absent:true,permitted_mutation_columns:['approval_status']}))
 const classes=['MATCH','STATUS_ALREADY_APPLIED','STATUS_UNEXPECTED','IDENTITY_MISSING','BOUNDARY_DRIFT','CONTENT_DRIFT','STORED_CONTENT_DIGEST_MISMATCH','METADATA_DRIFT','SOURCE_HASH_DRIFT','DUPLICATE_TARGET','UNAUTHORIZED_TARGET','INSUFFICIENT_BASELINE','AUDIT_EVENT_CONFLICT','AUDIT_IDENTITY_INVALID','PACKAGE_AUTHORITY_BLOCKED','TARGET_SET_MISMATCH']
 const policy={schema_version:'pr0057-application-rollback-policy-v1',package_id:packageId,package_version:packageVersion,target_table:'content_staging.reading_segments',target_count:74,only_permitted_mutation:['approval_status'],forbidden_explicit_mutations:['source_key','segment_order','segment_index','segment_count','boundary_version','start_locator','end_locator','display_title','content','word_count','normalized_content_sha256','created_at','updated_at'],default_execution_mode:'blocked',application_data_mutated:false,remote_connection_permitted:false}
 const states=['PACKAGE_BLOCKED','PREFLIGHT_REQUIRED','PREFLIGHT_FAILED','PREFLIGHT_PASSED','APPLICATION_READY','APPLICATION_STARTED','APPLICATION_COMMITTED','APPLICATION_NOOP_ALREADY_APPLIED','APPLICATION_FAILED','POSTFLIGHT_FAILED','ROLLBACK_REQUIRED','ROLLBACK_READY','ROLLBACK_STARTED','ROLLBACK_COMMITTED','ROLLBACK_FAILED','RECONCILED']
 const stateMachine={schema_version:'pr0057-execution-state-machine-v1',current_state:'PACKAGE_BLOCKED',states,allowed_transitions:[['PACKAGE_BLOCKED','PREFLIGHT_REQUIRED'],['PREFLIGHT_REQUIRED','PREFLIGHT_FAILED'],['PREFLIGHT_REQUIRED','PREFLIGHT_PASSED'],['PREFLIGHT_PASSED','APPLICATION_READY'],['APPLICATION_READY','APPLICATION_STARTED'],['APPLICATION_STARTED','APPLICATION_COMMITTED'],['APPLICATION_STARTED','APPLICATION_FAILED'],['APPLICATION_STARTED','POSTFLIGHT_FAILED'],['APPLICATION_COMMITTED','RECONCILED'],['APPLICATION_READY','APPLICATION_NOOP_ALREADY_APPLIED'],['APPLICATION_NOOP_ALREADY_APPLIED','RECONCILED'],['APPLICATION_FAILED','ROLLBACK_REQUIRED'],['POSTFLIGHT_FAILED','ROLLBACK_REQUIRED'],['ROLLBACK_REQUIRED','ROLLBACK_READY'],['ROLLBACK_READY','ROLLBACK_STARTED'],['ROLLBACK_STARTED','ROLLBACK_COMMITTED'],['ROLLBACK_STARTED','ROLLBACK_FAILED'],['ROLLBACK_COMMITTED','RECONCILED']],mandatory_guards:['preflight','audit conflict checks','content-integrity checks','transaction start','postflight','audit reconciliation']}
 const preflight={schema_version:'pr0057-preflight-contract-v1',normalization_algorithm:'reviewed-boundary-content-normalization-v1',runtime_content_rule:'load actual content; independently normalize and recompute digest, lengths, word count, stored digest agreement, and content projection hash; never trust stored digest alone',authority_checks:['package/version','exact 74 target set','execution authority','content integrity authority','snapshot complete and verified','application preflight ready','audit identity authority','rollback baseline ready for rollback'],identity_checks:['row exists exactly once','run_id/book_id/segment_key match','no duplicate or unauthorized target'],boundary_fields:['source_key','segment_order','segment_index','segment_count','boundary_version','start_locator','end_locator','display_title'],classifications:Object.fromEntries(classes.map(c=>[c,{application_allowed:c==='MATCH',idempotent_noop_allowed:c==='STATUS_ALREADY_APPLIED',rollback_allowed:c==='STATUS_ALREADY_APPLIED',manual_review_required:!['MATCH','STATUS_ALREADY_APPLIED'].includes(c),transaction_must_abort:!['MATCH','STATUS_ALREADY_APPLIED'].includes(c),audit_event_behavior:c==='MATCH'?'insert exactly once':c==='STATUS_ALREADY_APPLIED'?'verify semantic identity; do not insert':'do not insert; reconcile'}]))}
 const transaction={schema_version:'pr0057-transaction-contract-v1',atomicity:'one all-or-nothing transaction for all 74 targets; never per-row commits',ordering:['run_id','book_id','segment_order','segment_key'],lock_strategy:'pg_advisory_xact_lock derived deterministically from package_id, then SELECT FOR UPDATE in canonical order',application_steps:['BEGIN','acquire package advisory transaction lock','verify authority','load exact target set','lock rows deterministically','preflight all targets','abort before mutation on any blocker','update approval_status only','insert matching audits with predicate-bearing conflict target and equality verification','verify mutation count','postflight and reconcile','COMMIT; otherwise automatic ROLLBACK'],rollback_steps:['BEGIN','same package lock','validate later rollback authority','load and lock exact targets','verify matching application events and applied statuses','recompute integrity','abort on drift/conflict','restore approval_status only','insert rollback audits','verify count','rollback postflight','COMMIT; otherwise automatic ROLLBACK'],guarded_sql_templates:{preflight:'SELECT ... FROM content_staging.reading_segments WHERE (run_id, book_id, segment_key) IN (SELECT * FROM jsonb_to_recordset($1)) ORDER BY run_id, book_id, segment_order, segment_key FOR UPDATE',application:'UPDATE content_staging.reading_segments SET approval_status = $1 WHERE run_id = $2 AND book_id = $3 AND segment_key = $4 AND approval_status = $5',audit:'INSERT INTO content_staging.migration_audit_events (...) VALUES (...) ON CONFLICT (event_key) WHERE package_id = \'reading-segment-reviewed-boundary-execution\' AND event_version = 1 AND decision_id IS NOT NULL AND book_id IS NOT NULL AND segment_key IS NOT NULL AND event_key IS NOT NULL AND event_action IN (\'status-advanced\',\'status-rollback\') DO NOTHING',postflight:'SELECT ...; -- compare all immutable projections, status, audit payload and exact counts before COMMIT',rollback:'UPDATE content_staging.reading_segments SET approval_status = $1 WHERE run_id = $2 AND book_id = $3 AND segment_key = $4 AND approval_status = $5'},templates_are_non_executable:true}
 const idempotency={schema_version:'pr0057-idempotency-contract-v1',first_application:'MATCH: mutate status once and insert one application event',exact_retry:'STATUS_ALREADY_APPLIED plus semantically identical event and unchanged integrity: no mutation, no insert, idempotent success',inconsistent_states:['status applied/audit missing','audit present/status not applied','1..73 rows applied','missing row','conflict','post-application integrity drift'],inconsistent_result:'block automated continuation; rollback transaction and require reconciliation'}
 const audit={schema_version:'pr0057-application-audit-contract-v1',identity_fields:identity.logical_identity,event_key_algorithm:identity.event_key_algorithm,application_action:'status-advanced',rollback_action:'status-rollback',details_fields:['previous status','intended status','observed status','identity hash','boundary hash','content hash','full pre-application hash','stored normalized-content digest','recomputed normalized-content digest','digest agreement','preflight classification','source artifact hashes','package manifest hash','execution mode','transaction execution identifier','application or rollback result'],full_content_prohibited:true,created_at:'database generated; caller does not supply'}
 const conflict={schema_version:'pr0057-conflict-contract-v1',predicate_bearing_on_conflict_required:true,plain_on_conflict_event_key_invalid:true,cases:{exact_duplicate:'verified no-op',semantic_duplicate:'verify structured identity and canonical payload then no-op',identity_conflict:'abort and reconcile',payload_conflict:'abort and reconcile',application_versus_rollback:'distinct event_action and event_key',partial_state:'abort and reconcile'}}
 const postflight={schema_version:'pr0057-postflight-contract-v1',before_commit:true,assertions:['74 authoritative targets considered','each row exists exactly once','eligible statuses intended','boundary projections unchanged','content projections unchanged','stored/recomputed digest agrees','application events exactly once and payloads match','zero rollback events','zero unauthorized rows changed','affected row count equals MATCH count','reconciliation complete'],failure:'abort whole transaction'}
 const runtimeEvidence={schema_version:'pr0057-runtime-evidence-contract-v1',path:'tmp/reviewed-boundary-application-rollback-runtime-evidence.json',committed_passing_evidence:false,required_fields:['package_id','package_version','execution_identifier','database_engine_and_version','source_manifest_hashes','authority_state','target_count','preflight_classification_counts','application_mutation_count','idempotent_noop_count','audit_insert_count','conflict_count','postflight_result','rollback_result','zero_unauthorized_mutations','transaction_outcome','cleanup_outcome']}
 const gate={schema_version:'pr0057-execution-gate-v1',requirements:{audit_identity_authority_approved:false,content_integrity_authority_approved:false,source_snapshot_complete:false,source_snapshot_verified:false,application_preflight_ready:false,exact_target_count:74,zero_blocking_drift_classifications:true,zero_audit_conflicts:true,runtime_database_identity_explicitly_approved:false,execution_mode_explicitly_apply:false,operator_confirmation_token_present:false,package_manifest_hash_matches:false},application_execution_authorized:false,rollback_execution_authorized:false,rollback_additional_requirements:['rollback_baseline_ready','application execution confirmed','74 matching application events','later rollback authority explicitly granted']}
 const missingAuthority={schema_version:'pr0057-missing-authority-v1',missing:['74 complete actual-content baselines','verified source snapshot','content-integrity approval','execution authority','runtime database identity approval','operator confirmation','later rollback authority'],fail_closed:true}
 const readiness={schema_version:'pr0057-readiness-evidence-v1',authorized_decision_count:74,application_operation_count:74,rollback_operation_count:74,duplicate_target_count:0,source_snapshot_complete:false,source_snapshot_verified:false,application_preflight_ready:false,rollback_baseline_ready:false,content_integrity_authority_approved:false,execution_authority_approved:false,application_execution_authorized:false,rollback_execution_authorized:false,source_hashes:hashes,postgresql_validation_decision:'Required for future executor mechanics; PR-0057 commits non-executable parameterized templates only. PR-0055 PostgreSQL 15 workflow already proves partial-index semantics. No runtime success evidence is claimed.'}
 return {policy,stateMachine,applicationOperations:{schema_version:'pr0057-application-operations-v1',operation_count:74,canonical_order:transaction.ordering,operations},rollbackOperations:{schema_version:'pr0057-rollback-operations-v1',operation_count:74,canonical_order:transaction.ordering,operations:rollbacks},preflight,transaction,idempotency,audit,conflict,postflight,runtimeEvidence,gate,missingAuthority,readiness}
}
export async function build(){const artifacts=await derive();for(const n of names)await writeFile(paths[n],JSON.stringify(artifacts[n],null,2)+'\n');const manifest={schema_version:'pr0057-application-rollback-manifest-v1',package_id:packageId,package_version:packageVersion,application_execution_authorized:false,rollback_execution_authorized:false,source_hashes:artifacts.readiness.source_hashes,artifact_hashes:Object.fromEntries(names.map(n=>[`${n}_sha256`,canonicalJsonSha256FromValue(artifacts[n])]))};await writeFile(paths.manifest,JSON.stringify(manifest,null,2)+'\n');return manifest}
if(import.meta.url===`file://${process.argv[1]}`)console.log(JSON.stringify(await build(),null,2))
