import {createHash} from 'node:crypto';import {readFile,writeFile} from 'node:fs/promises'
import {canonicalJsonSha256,canonicalJsonSha256FromValue} from './hash_utils.mjs'
import {packageId,packageVersion,validityHours,modes,roles,classifications,outcomes,sources,artifacts,authorityFields,baselineFields} from './reviewed_boundary_staging_authorization_constants.mjs'
const json=async p=>JSON.parse(await readFile(p,'utf8'));const hash=async p=>p.endsWith('.json')?canonicalJsonSha256(p):createHash('sha256').update((await readFile(p,'utf8')).replace(/\r\n?/g,'\n')).digest('hex')
const canonical='recursive lexicographic object-key sorting; preserved array order; whitespace-free JSON; UTF-8; lowercase SHA-256; self-hash excluded; closed-world fields; null significant; undefined forbidden; JSON-finalize timestamps before hashing'
export async function build(){const source_hashes=Object.fromEntries(await Promise.all(Object.entries(sources).map(async([k,p])=>[k,await hash(p)])));const [targets,apps,rolls]=await Promise.all([json(sources.integrity_targets),json(sources.application_operations),json(sources.rollback_operations)]);const a=apps.operations,r=rolls.operations;if(targets.target_count!==74||targets.records.length!==74||a.length!==74||r.length!==74)throw Error('exact 74-target scope required');const key=x=>`${x.run_id}\0${x.book_id}\0${x.segment_key}`,sets=[targets.records,a,r].map(xs=>xs.map(key));if(sets.some(s=>new Set(s).size!==74)||sets.some(s=>s.slice().sort().join('\n')!==sets[0].slice().sort().join('\n')))throw Error('target sets disagree or contain duplicate');if(a.some(x=>x.permitted_mutation_columns.join(',')!=='approval_status')||r.some(x=>x.permitted_mutation_columns.join(',')!=='approval_status'))throw Error('operation is not status-only');
 const common={package_id:packageId,package_version:packageVersion,expected_target_count:74,source_hashes};const falseAuthority=Object.fromEntries(authorityFields.map(x=>[x,false]));
 const docs={
 policy:{schema_version:'pr0059-staging-evidence-admission-policy-v1',...common,modes,default_mode:'blocked',explicit_mode_required:true,production_review_rejected:true,fixture_maximum_classification:'EVIDENCE_ADMISSION_FIXTURE_ONLY',classifications:Object.fromEntries(classifications.map(c=>[c,{evidence_may_be_stored:!['EVIDENCE_ADMISSION_SECRET_LEAK','EVIDENCE_ADMISSION_CONTENT_LEAK'].includes(c),redacted_derivatives_only:true,manual_review_required:true,source_snapshot_complete_may_be_true:['EVIDENCE_ADMISSION_ELIGIBLE','EVIDENCE_ADMISSION_ATTESTED','EVIDENCE_ADMISSION_AUTHORIZED'].includes(c),source_snapshot_verified_may_be_true:['EVIDENCE_ADMISSION_ATTESTED','EVIDENCE_ADMISSION_AUTHORIZED'].includes(c),content_integrity_authority_approved_may_be_true:['EVIDENCE_ADMISSION_ATTESTED','EVIDENCE_ADMISSION_AUTHORIZED'].includes(c),application_preflight_ready_may_be_true:['EVIDENCE_ADMISSION_ATTESTED','EVIDENCE_ADMISSION_AUTHORIZED'].includes(c),rollback_baseline_ready_may_be_true:['EVIDENCE_ADMISSION_ATTESTED','EVIDENCE_ADMISSION_AUTHORIZED'].includes(c),application_execution_authorized_may_be_true:c==='EVIDENCE_ADMISSION_AUTHORIZED',execution_still_blocked:c!=='EVIDENCE_ADMISSION_AUTHORIZED'}]))},
 admission:{schema_version:'pr0059-admitted-evidence-hash-v1',...common,canonical_hashing:canonical,import_requirements:['explicit mode','regular non-symlink evidence file','maximum 10485760 bytes','duplicate-key-free JSON','expected evidence SHA-256','expected runtime manifest SHA-256','operator identity reference','deliberate confirmation'],independent_validation:['reviewed-boundary-runtime-evidence-hash-v1','closed-world top-level fields','lowercase SHA-256 and self-hash','source hashes and runtime manifest','74 observed and expected; zero missing, duplicate, unauthorized','exact PR-0057 target set','74 complete baselines and digest matches','zero digest mismatch, boundary drift, content drift, unexpected status, audit conflict','zero application, rollback, audit insertion, or unauthorized mutations','no full content or secret-like values','read-only transaction','staging-readonly for staging-review','STAGING_PREFLIGHT_MATCHED'],maximum_result_without_review:'EVIDENCE_ADMISSION_REVIEW_REQUIRED'},
 database:{schema_version:'pr0059-database-identity-attestation-hash-v1',...common,canonical_hashing:canonical,required_fields:['environment_class','redacted_project_database_fingerprint','postgresql_major_version','schema_fingerprint','required_migration_fingerprint','runtime_package_manifest_sha256','evidence_sha256','execution_identifier','collection_timestamp','collector_mode','target_count','operator_identity_reference','reviewer_identity_reference','attestation_version','database_attestation_sha256'],fixture_and_staging_structurally_distinct:true,forbidden_fields:['host','username','password','connection_string','supabase_key','access_token','raw_project_identifier']},
 baseline:{schema_version:'pr0059-staging-baseline-contract-v1',...common,record_count:74,record_fields:baselineFields,full_content_forbidden:true,derivations:['complete source snapshot','verified source snapshot','content-integrity baseline','rollback baseline','application preflight baseline'],all_derivations_require_real_valid_staging_evidence:true},
 attestation:{schema_version:'pr0059-human-attestation-hash-v1',...common,canonical_hashing:canonical,roles,required_fields:['attestation_version','role','identity_reference','admitted_package_sha256','evidence_sha256','runtime_manifest_sha256','database_attestation_sha256','confirmation_token_reference','attested_at','expires_at','claims','production_authorized','attestation_sha256'],separate_records_required:true,same_person_multiple_roles_permitted:true,separate_deliberate_confirmation_required:true,claims:{'collector-operator':['deliberate collection','staging-readonly','expected staging selected','no production connection','no application or rollback','no credentials or full content persisted'],'technical-reviewer':['validation passed','exact 74 reconciliation','database identity matched','no drift or audit conflict','baselines correct','reviewed evidence hash matches'],'execution-authorizer':['exact staging package enabled','approval_status only','PR-0057 guarded transaction required','expiry accepted','production unauthorized']}},
 expiry:{schema_version:'pr0059-authorization-expiry-v1',...common,validity_window_hours:validityHours,fail_closed:true,conditions:['evidence age exceeds maximum','application plan hash changes','PR-0057 manifest hash changes','PR-0058 manifest hash changes','target set changes','schema fingerprint changes','database identity changes','target row changes','target status changes','audit event changes','newer evidence supersedes']},
 revocation:{schema_version:'pr0059-authorization-revocation-v1',...common,fail_closed:true,conditions:['explicit revocation','application begins','application completes','rollback begins','rollback completes','any expiry condition'],revocation_record_required:true},
 decision:{schema_version:'pr0059-authorization-decision-hash-v1',...common,canonical_hashing:canonical,required_fields:['package_id','package_version','decision_id','admission_mode','evidence_sha256','source_manifest_hashes','database_identity_attestation_hash','operator_attestation_hash','reviewer_attestation_hash','execution_authorizer_attestation_hash','exact_target_count','qualifying_target_count','blocking_classification_count',...authorityFields.filter(x=>x!=='production_collection_authorized'),'authorization_issued_at','authorization_expires_at','authorization_state','revocation_state','revocation_reason','decision_sha256'],outcomes,default_decision:{decision_id:'repository-default-blocked',admission_mode:'blocked',evidence_sha256:null,database_identity_attestation_hash:null,operator_attestation_hash:null,reviewer_attestation_hash:null,execution_authorizer_attestation_hash:null,exact_target_count:74,qualifying_target_count:0,blocking_classification_count:1,...falseAuthority,authorization_issued_at:null,authorization_expires_at:null,authorization_state:'STAGING_EVIDENCE_REQUIRED',revocation_state:'NOT_REVOKED',revocation_reason:null}},
 token:{schema_version:'pr0059-staging-execution-token-hash-v1',...common,canonical_hashing:canonical,generated_by_default:false,credential_bearing:false,required_fields:['admitted_evidence_sha256','authorization_decision_sha256','pr0057_application_manifest_sha256','pr0058_runtime_manifest_sha256','database_identity_fingerprint','target_set_sha256','intended_execution_mode','issued_at','expires_at','unique_execution_identifier','operator_confirmation','token_state','execution_token_sha256'],mode:'staging-application',single_use:true,invalid_after_drift:true,invalid_after_source_hash_change:true,rollback_requires_distinct_token:true,production_authorized:false},
 storage:{schema_version:'pr0059-staging-storage-policy-v1',...common,temporary_evidence_location:'tmp/reviewed-boundary-staging-authorization/',secure_operator_review_boundary:'operator-controlled path supplied explicitly',committable:['redacted admitted baseline','redacted database attestation','separate human attestations','authorization decision','revocation record'],never_commit:['full segment content','credentials','connection strings','access tokens','unredacted database identity','raw temporary evidence with excess detail','fixture evidence as staging authority'],retention:'retain current redacted authority package; supersede and revoke older package; securely delete temporary raw evidence per operator policy'},
 gate:{schema_version:'pr0059-staging-authorization-gate-v1',...common,initial_outcome:'STAGING_EVIDENCE_REQUIRED',...falseAuthority,no_database_connection:true,no_application_or_rollback:true},missing:{schema_version:'pr0059-staging-missing-authority-v1',...common,real_staging_evidence_admitted:false,real_attestations_present:false,reason:'No real staging-readonly evidence has been deliberately admitted and reviewed.'},readiness:{schema_version:'pr0059-staging-readiness-v1',...common,...falseAuthority,admission_mode:'blocked',authorization_state:'STAGING_EVIDENCE_REQUIRED',application_mutation_count:0,rollback_mutation_count:0,audit_insertion_count:0,no_database_connection_occurred:true,no_application_or_rollback_occurred:true}
 };for(const [name,file] of Object.entries(artifacts))await writeFile(`content/migration/${file}`,JSON.stringify(docs[name],null,2)+'\n');const artifact_hashes=Object.fromEntries(Object.entries(artifacts).map(([n])=>[n,canonicalJsonSha256FromValue(docs[n])]));const manifest={schema_version:'pr0059-staging-authorization-manifest-v1',...common,artifact_hashes,authority:falseAuthority};await writeFile('content/migration/reading-segment-reviewed-boundary-staging-authorization-manifest.json',JSON.stringify(manifest,null,2)+'\n');return manifest}
if(import.meta.url===`file://${process.argv[1]}`)console.log(JSON.stringify(await build(),null,2))
