import {createHash} from 'node:crypto'; import {readFile,writeFile} from 'node:fs/promises'
import {canonicalJsonSha256,canonicalJsonSha256FromValue} from './hash_utils.mjs'
import {sources,paths,artifactNames,packageId,packageVersion,modes,classes,auditClasses,evidencePath,evidenceFields,evidenceHashContract,evidenceHashExcludedFields} from './reviewed_boundary_runtime_integrity_constants.mjs'
const json=async p=>JSON.parse(await readFile(p,'utf8')); const lf=async p=>createHash('sha256').update((await readFile(p,'utf8')).replace(/\r\n?/g,'\n')).digest('hex')
export async function sourceHashes(){return Object.fromEntries(await Promise.all(Object.entries(sources).map(async([k,p])=>[k,p.endsWith('.json')?await canonicalJsonSha256(p):await lf(p)])))}
export async function derive(){const before=await sourceHashes(); const [plan,targets,apps,rolls,exec,integrity]=await Promise.all([json(sources.application_plan),json(sources.integrity_targets),json(sources.application_operations),json(sources.rollback_operations),json(sources.execution_authority_manifest),json(sources.integrity_manifest)])
 const ar=plan.application_records;if(plan.authorized_decision_count!==74||ar.length!==74||targets.target_count!==74||targets.records.length!==74)throw Error('authority count must equal 74'); const ac=apps.operations??apps.records,rc=rolls.operations??rolls.records;if(!Array.isArray(ac)||ac.length!==74||!Array.isArray(rc)||rc.length!==74)throw Error('operation count must equal 74');
 const ids=ar.map(x=>x.decision_id), tuples=ar.map(x=>`${x.expected_run_id}\0${x.book_id}\0${x.segment_key}`);if(new Set(ids).size!==74||new Set(tuples).size!==74)throw Error('duplicate authority'); for(const x of ar)if(x.changed_columns?.length!==1||x.changed_columns[0]!=='approval_status')throw Error('non-status mutation'); if(exec.execution_authority_approved!==false||integrity.content_integrity_authority_approved!==false)throw Error('execution unexpectedly authorized'); if(targets.records.some(x=>x.baseline_complete))throw Error('fabricated complete baseline')
 const common={package_id:packageId,package_version:packageVersion,target_count:74,source_hashes:before,application_data_mutated:false,application_execution_authorized:false,rollback_execution_authorized:false,production_collection_authorized:false}
 const policy={schema_version:'pr0058-runtime-integrity-policy-v1',...common,modes,default_mode:'blocked',explicit_mode_required:true,read_only:true,full_content_persistence:false,actual_staging_evidence_committed:false}
 const databaseIdentity={schema_version:'pr0058-runtime-database-identity-v1',required:['environment_name','project_identifier_or_database_fingerprint','postgresql_server_version','database_name','schemas','required_tables','migration_version_or_schema_fingerprint','read_only_collector_mode','package_manifest_hash','target_count','operator_confirmation_token','runtime_execution_identifier'],production_under_staging_rejected:true,credentials_redacted:true,required_reading_segments_columns:['run_id','book_id','segment_key','source_key','segment_order','segment_index','segment_count','boundary_version','start_locator','end_locator','display_title','content','word_count','normalized_content_sha256','approval_status','created_at','updated_at'],required_audit_extension:true}
 const targetQuery={schema_version:'pr0058-runtime-target-query-v1',identity_fields:['run_id','book_id','segment_key'],strategy:'parameterized VALUES CTE inner joined on all stable identity fields; compare observed identities to exact expected closed world',parameterized:true,broad_query_forbidden:true,select_for_update:false,detects:['missing expected target','duplicate returned identity','unexpected returned target','malformed identity','target-set mismatch','segment-order mismatch','cross-run contamination']}
 const reconstruction={schema_version:'pr0058-runtime-reconstruction-v1',hash_algorithm:'sha256-canonical-json-v1',normalization_algorithm:'reviewed-boundary-content-normalization-v1',normalization_implementation:'scripts/content_pipeline/reviewed_boundary_content_normalization.mjs',identity_fields:['run_id','book_id','segment_key'],boundary_fields:['source_key','segment_order','segment_index','segment_count','boundary_version','start_locator','end_locator','display_title'],content_fields:['recomputed_normalized_content_sha256','recomputed_word_count','normalized_content_length','content_byte_length'],status_fields:['observed_approval_status','expected_previous_approval_status','intended_resulting_approval_status'],timestamps_excluded_from_hashes:['created_at','updated_at'],stored_digest_never_sufficient:true}
 const semantics=Object.fromEntries(classes.map(c=>[c,{matches_expected_pre_application_state:c==='MATCH',later_application_may_be_permitted:c==='MATCH',idempotent_no_op_may_be_permitted:c==='STATUS_ALREADY_APPLIED',rollback_may_be_permitted:c==='STATUS_ALREADY_APPLIED',manual_review_required:!['MATCH','STATUS_ALREADY_APPLIED'].includes(c),preflight_must_fail:!['MATCH','STATUS_ALREADY_APPLIED'].includes(c)}]))
 const classification={schema_version:'pr0058-runtime-classification-v1',classifications:semantics,runtime_ready_requirements:['identity matches','boundary fields complete','content present','recomputed digest exists','stored digest matches recomputed digest','word counts agree','observed status equals expected previous status','no audit conflict','no source-hash drift']}
 const auditReconciliation={schema_version:'pr0058-runtime-audit-reconciliation-v1',read_only:true,insert_events:false,classifications:auditClasses,valid_application_event_requires:['structured identity matches','event_key matches','event_action matches','payload semantics match','target status consistent'],partial_or_contradictory_state_blocks:true}
 const evidenceContract={schema_version:'pr0058-runtime-evidence-contract-v1',path:evidencePath,temporary_only:true,hash_contract:{name:evidenceHashContract,canonicalization:'recursively sort object keys lexicographically; preserve array order; whitespace-free JSON.stringify; UTF-8; lowercase SHA-256',included_fields:evidenceFields.filter(x=>!evidenceHashExcludedFields.includes(x)),excluded_fields:evidenceHashExcludedFields,closed_world:true,null_values_significant:true,undefined_values_forbidden:true},required_fields:evidenceFields,safety_values:{application_mutation_count:0,rollback_mutation_count:0,audit_insertion_count:0,full_content_persisted:false,unauthorized_mutation_count:0},forbidden:['password','access_token','connection_string','supabase_key','content','secret']}
 const gate={schema_version:'pr0058-staging-preflight-gate-v1',initial_result:'STAGING_PREFLIGHT_BLOCKED',outcomes:['STAGING_PREFLIGHT_BLOCKED','STAGING_PREFLIGHT_MATCHED','STAGING_PREFLIGHT_ALREADY_APPLIED','STAGING_PREFLIGHT_INCONSISTENT','STAGING_PREFLIGHT_ERROR'],application_preflight_ready:false,application_execution_authorized:false,rollback_execution_authorized:false}
 const missingAuthority={schema_version:'pr0058-runtime-missing-authority-v1',real_staging_evidence_available:false,reason:'Actual database-backed row content is not present in repository artifacts; fixture evidence proves mechanics only.',required_action:'Deliberate staging-readonly collection and independent evidence review'}
 const readiness={schema_version:'pr0058-runtime-readiness-v1',source_snapshot_complete:false,source_snapshot_verified:false,content_integrity_authority_approved:false,application_preflight_ready:false,rollback_baseline_ready:false,application_execution_authorized:false,rollback_execution_authorized:false,production_collection_authorized:false,staging_preflight_result:'STAGING_PREFLIGHT_BLOCKED',application_mutation_count:0,rollback_mutation_count:0,audit_insertion_count:0,full_content_persisted:false,no_application_or_rollback_occurred:true,no_production_connection_occurred:true}
 if(JSON.stringify(before)!==JSON.stringify(await sourceHashes()))throw Error('source changed');return {policy,databaseIdentity,targetQuery,reconstruction,auditReconciliation,classification,evidenceContract,gate,missingAuthority,readiness}}
export async function build(){const a=await derive();for(const n of artifactNames)await writeFile(paths[n],JSON.stringify(a[n],null,2)+'\n');const manifest={schema_version:'pr0058-runtime-integrity-manifest-v1',package_id:packageId,package_version:packageVersion,target_count:74,source_hashes:a.policy.source_hashes,artifact_hashes:Object.fromEntries(artifactNames.map(n=>[n,canonicalJsonSha256FromValue(a[n])])),authority:{source_snapshot_complete:false,source_snapshot_verified:false,content_integrity_authority_approved:false,application_preflight_ready:false,rollback_baseline_ready:false,application_execution_authorized:false,rollback_execution_authorized:false,production_collection_authorized:false}};await writeFile(paths.manifest,JSON.stringify(manifest,null,2)+'\n');return manifest}if(import.meta.url===`file://${process.argv[1]}`)console.log(JSON.stringify(await build(),null,2))
