import { mkdir, writeFile, readFile, readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { join } from 'node:path'
import { canonicalJsonSha256, canonicalJsonSha256FromValue } from './hash_utils.mjs'
import { artifactPaths as paths, historicalPaths, migrationsDir, migrationPath, packageIds, eventPackage, packageVersion, eventVersion, targetTable, identityColumns, eventActions, statuses, hashAlgorithms, safetyKeys, conflictTargetPredicate, eventKeyAlgorithm } from './reviewed_boundary_audit_identity_constants.mjs'

export const normalizedTextSha256FromText = (text) => createHash('sha256').update(text.replace(/\r\n?/g, '\n'), 'utf8').digest('hex')
export const normalizedTextSha256 = async (p) => normalizedTextSha256FromText(await readFile(p, 'utf8'))
const readJson = async (p) => JSON.parse(await readFile(p, 'utf8'))
const safety = Object.fromEntries(safetyKeys.map((k) => [k, k === 'audit_schema_migration_generated']))
Object.assign(safety, { audit_schema_migration_executed:false, executable_application_sql_generated:false, executable_rollback_sql_generated:false, application_sql_executed:false, rollback_sql_executed:false, database_modified:false, supabase_modified:false, staging_modified:false, production_modified:false, reading_segments_modified:false, audit_events_inserted:false, ui_modified:false, source_text_modified:false, user_progress_modified:false, reader_sessions_modified:false, bookmarks_modified:false, notes_modified:false, highlights_modified:false, cutover_enabled:false })

export async function enumerateMigrations(dir = migrationsDir) { return (await readdir(dir)).filter((f) => f.endsWith('.sql')).sort().map((f) => join(dir, f)) }
export const preMigrationAuditSchema = (source) => ({ table:'content_staging.migration_audit_events', source_migration:source, columns:[{name:'id',type:'bigint',nullable:false,default:'generated always as identity',logical_identity:false},{name:'run_id',type:'uuid',nullable:false,default:null,foreign_key:'content_staging.migration_runs(id) on delete cascade'},{name:'event_type',type:'text',nullable:false,default:null},{name:'details',type:'jsonb',nullable:false,default:"'{}'::jsonb",check:'jsonb_typeof(details) = object'},{name:'created_at',type:'timestamptz',nullable:false,default:'now()'}], primary_key:['id'], unique_constraints:[], unique_indexes:[], rls:'schema access revoked from public, anon, authenticated by foundation migration; no table RLS policy found', grants:'no content_staging.migration_audit_events table grants found' })
export const postMigrationAuditSchema = (source) => ({ ...preMigrationAuditSchema('supabase/migrations/20260803033000_content_staging_foundation.sql'), extension_migration:source, columns:[...preMigrationAuditSchema('').columns,{name:'package_id',type:'text',nullable:true,default:null},{name:'event_version',type:'integer',nullable:true,default:null},{name:'decision_id',type:'text',nullable:true,default:null},{name:'book_id',type:'integer',nullable:true,default:null},{name:'segment_key',type:'text',nullable:true,default:null},{name:'event_action',type:'text',nullable:true,default:null},{name:'event_key',type:'text',nullable:true,default:null}], check_constraints:['reviewed-boundary identity complete when package_id matches','reviewed-boundary action in status-advanced/status-rollback','reviewed-boundary event_version = 1','reviewed-boundary segment_key hex length','event_key equals canonical concat_ws identity','details contains and matches exact immutable payload fields'], unique_indexes:[{name:'migration_audit_events_reviewed_boundary_event_key_uidx',columns:['event_key'],unique:true,predicate:"package_id = 'reading-segment-reviewed-boundary-execution' and event_version = 1 and decision_id/book_id/segment_key/event_key are not null and event_action in ('status-advanced','status-rollback')"}] })
export const eventKeyMaterial = ({run_id, decision_id, book_id, segment_key, event_action, package_id = eventPackage, event_version = eventVersion}) => { const pairs = [['package_id', package_id], ['event_action', event_action], ['run_id', run_id], ['decision_id', decision_id], ['book_id', String(book_id)], ['segment_key', segment_key], ['event_version', String(event_version)]]; return eventKeyAlgorithm + pairs.map(([k,v]) => `|${k}=${String(v).length}:${v}`).join('') }
export const eventKey = (input) => createHash('sha256').update(eventKeyMaterial(input), 'utf8').digest('hex')

export async function build() {
  await mkdir('content/migration/reports', { recursive:true }); await mkdir('docs/content-pipeline', { recursive:true })
  const plan = await readJson(historicalPaths.pr0053Plan); const pr54 = await readJson(historicalPaths.pr0054Policy)
  const migrations = await enumerateMigrations(); const foundation = migrations.find((p) => p.endsWith('20260803033000_content_staging_foundation.sql'))
  const migrationSql = await readFile(migrationPath, 'utf8')
  const producerInventory = [{producer:'content_staging_foundation migration functions',files:[foundation],insert_compatibility:'unaffected; new columns nullable for legacy rows'},{producer:'repository code search',files:[],insert_compatibility:'no application code inserting migration_audit_events found outside migrations/tests/artifacts'}]
  const policy = { schema_version:'pr0055-reviewed-boundary-audit-identity-policy-v1', package_id:packageIds.pr0055, authority_for_package:packageIds.pr0054, audit_identity_authority_approved:true, approval_result:'approved', target_table:targetTable, run_id:plan.run_id, authorized_decision_count:74, excluded_decision_count:70, event_granularity:{application:'one event per authorized decision',rollback:'one event per authorized decision only after later rollback authority'}, safety_assertions:safety }
  const schemaContract = { schema_version:'pr0055-reviewed-boundary-audit-schema-extension-contract-v1', approved:true, design_decision:'extend existing audit table with nullable structured identity columns plus scoped partial unique index; details jsonb remains payload carrier for compatibility', repository_facts:['existing table has id/run_id/event_type/details/created_at only','details jsonb is existing payload convention','no existing stable unique identity exists','nullable columns preserve legacy inserts'], pre_migration_schema:preMigrationAuditSchema(foundation), post_migration_schema:postMigrationAuditSchema(migrationPath), migration_path:migrationPath, migration_executed:false, safety_assertions:safety }
  const identity = { schema_version:'pr0055-reviewed-boundary-audit-event-identity-contract-v1', approved:true, package_id:eventPackage, package_version:packageVersion, event_version:eventVersion, logical_identity:identityColumns, event_key_algorithm:eventKeyAlgorithm, deterministic_event_key:'lowercase hex sha256 of length-delimited canonical material over package_id, event_action, run_id, decision_id, book_id, segment_key, and event_version', canonical_material_fields:identityColumns, canonical_material_encoding:'sha256-v1 label followed by |field_name=decimal_length:value for each identity field in fixed order; nulls are prohibited by reviewed-boundary checks', collision_handling:'sha256 collision is treated as AUDIT_CONFLICT unless every immutable field and canonical payload also match' , rejects_identity_sources:['id','created_at','random uuid','details-only serialization'], application_event_action:eventActions.application, rollback_event_action:eventActions.rollback, rollback_distinction:'event_action and before/after statuses differ, so application and rollback event_key values differ' }
  const payloadFields = ['package_id','package_version','event_version','event_action','decision_id','run_id','book_id','segment_key','previous_approval_status','resulting_approval_status','target_table','target_identity','authority_manifest_hash','package_hash']
  const payload = { schema_version:'pr0055-reviewed-boundary-audit-event-payload-contract-v1', approved:true, details_jsonb_required_fields:payloadFields, prohibited_fields:['source_text','source_excerpt','content_excerpt','credentials','connection_string','created_at'], application:{event_action:eventActions.application, previous_approval_status:statuses.applicationBefore, resulting_approval_status:statuses.applicationAfter}, rollback:{event_action:eventActions.rollback, previous_approval_status:statuses.rollbackBefore, resulting_approval_status:statuses.rollbackAfter}, timestamp_behavior:'created_at remains database-generated default now(); callers must not supply timestamps' }
  const conflict = { schema_version:'pr0055-reviewed-boundary-audit-conflict-contract-v1', approved:true, first_run:'0 matching application events and 74 boundary-review rows: insert 74 immutable events in the same future transaction as status updates', conflict_target:`ON CONFLICT (event_key) WHERE ${conflictTargetPredicate} DO NOTHING`, duplicate_behavior:'Predicate-bearing ON CONFLICT may DO NOTHING only when followed by equality verification of every structured identity column, event_type, canonical details payload, run_id, before/after status, target identity, authority_manifest_hash, and package_hash; DO NOTHING alone never proves equality; exact match is verified no-op', conflicting_duplicate:'same logical identity or event_key with any immutable difference fails closed as AUDIT_CONFLICT', partial_state:'counts must be exactly 0 or 74 for applicable state; any 1..73 event count, event/status disagreement, or status without event fails closed', complete_repeat:'74 matching events plus 74 content-review rows is classified as complete verified no-op for application; rollback still requires later authority', rollback_not_authorized:'schema supports rollback event identity but does not authorize rollback execution' }
  const compatibility = { schema_version:'pr0055-reviewed-boundary-audit-compatibility-assessment-v1', approved:true, existing_producers:producerInventory, legacy_rows:'preserved with null new identity columns; partial unique index excludes them', existing_insert_compatibility:'existing inserts specifying run_id,event_type,details continue to satisfy nullable added columns and defaults', unrelated_namespaces:'unaffected because check constraints and unique index are scoped to reviewed-boundary package_id', producers_requiring_modification:[] }
  const migrationPlan = { schema_version:'pr0055-reviewed-boundary-audit-migration-plan-v1', approved:true, migration_path:migrationPath, deterministic:true, execute:false, operations:['add seven nullable identity columns','add scoped reviewed-boundary check constraints including length-delimited sha256 event_key equivalence','add scoped partial unique index on event_key'], forbidden_operations:['insert','update reading_segments','application sql','rollback sql','external connection'] }
  const migrationEvidence = { schema_version:'pr0055-reviewed-boundary-audit-migration-evidence-v1', approved:true, migrations_scanned:migrations, relevant_pre_existing_migrations:[foundation], proposed_migration:migrationPath, proposed_migration_sha256:normalizedTextSha256FromText(migrationSql), migration_sql_executed:false, safety_assertions:safety }
  const missing = { schema_version:'pr0055-reviewed-boundary-audit-missing-authority-v1', audit_identity_authority_approved:true, missing_authority:[], remaining_out_of_scope_blockers:['rollback downstream gate','complete content-integrity baselines'], safety_assertions:safety }

  const triageBaseline = { schema_version:'pr0055-reviewed-boundary-audit-triage-baseline-evidence-v1', validator_command:'npm run content:staging:segments:triage:validate', base_commit:'91e5a5f0041e1b8f5e8d06146338c9a7060d7b9e', base_result:'failed: source review queue checksum differs from triage input', pr0055_result:'failed unchanged: source review queue checksum differs from triage input', classification:'pre-existing base failure; PR-0055 does not alter consumed triage authority', consumed_files:[
    {path:'content/migration/reading-segment-review-policy.json', sha256:'a68243da1b380ba80efe03b2b3fc320949ff73dd23b0d058a78c7abc68f3927a', modified_by_pr0055:false},
    {path:'content/migration/reading-segment-design-manifest.json', sha256:'029eb8dfc2897b43388ab430eff82369a3b89453b7b070375b2d94a20ea98132', modified_by_pr0055:false},
    {path:'content/migration/reading-segment-review-queue.json', sha256:'3045ca47395bfa47fb883eddaaa6a0b048a4a68e9e80897e2bdba48bb7f3d505', modified_by_pr0055:false, actual_checksum:'3045ca47395bfa47fb883eddaaa6a0b048a4a68e9e80897e2bdba48bb7f3d505'},
    {path:'content/migration/reading-segment-application-evidence.json', sha256:'b756ae73ccad3dee7649e2d93e0802415366116f7e42b0efada7f523bf55829c', modified_by_pr0055:false},
    {path:'content/migration/reading-segment-review-triage.json', sha256:'74762f26cce60d2df87b6c662946f9b2697a6472c04b8b3dff96e2263e1d569d', modified_by_pr0055:false, expected_review_queue_checksum:'06d53501303eaca9aa8a1ba9f81aa10fed02801996eba90ba38f9e15b3440b66'},
    {path:'content/migration/reading-segment-active-review-queue.json', sha256:'5fda0aeae4552c61bc0dbfd77da2d601314aa7ef669e190935f15ebaf69ce704', modified_by_pr0055:false},
    {path:'content/migration/reading-segment-deferred-metadata.json', sha256:'64b44263d40f7c53a6f2ec2ca4985b675be64ab04986aa8401a607eb128bce5a', modified_by_pr0055:false},
    {path:'content/migration/reading-segment-review-batches.json', sha256:'2e6928c18819734f03283004690f86673e2f9c10b62fe41945bd6fdd98ee0864', modified_by_pr0055:false}
  ], pr0055_changes_consumed_files:false, schema_interpretation_changed:false, resolution_rule:'outcome 2: record pre-existing base failure unchanged and add regression coverage; do not claim all validators passed' }
  const evidence = { schema_version:'pr0055-reviewed-boundary-audit-authority-evidence-v1', audit_identity_authority_approved:true, pr0054_authority:{execution_authority_approved:pr54.execution_authority_approved, authorized_target_count:pr54.authorized_target_count}, hashes:{pr0053_manifest:await canonicalJsonSha256(historicalPaths.pr0053Manifest), pr0053_evidence:await canonicalJsonSha256(historicalPaths.pr0053Evidence), pr0054_manifest:await canonicalJsonSha256(historicalPaths.pr0054Manifest), pr0054_schema:await canonicalJsonSha256(historicalPaths.pr0054Schema), pre_existing_audit_migration:await normalizedTextSha256(foundation), proposed_migration:await normalizedTextSha256(migrationPath)}, safety_assertions:safety }
  const artifacts = { policy, schemaContract, identity, payload, conflict, compatibility, migrationPlan, migrationEvidence, missing, evidence, triageBaseline }
  for (const [k,v] of Object.entries(artifacts)) await writeFile(paths[k], JSON.stringify(v,null,2)+'\n')
  const manifest = { schema_version:'pr0055-reviewed-boundary-audit-authority-manifest-v1', package_id:packageIds.pr0055, audit_identity_authority_approved:true, hash_algorithms:hashAlgorithms, artifact_hashes:Object.fromEntries(Object.entries(artifacts).map(([k,v])=>[`${k}_sha256`, canonicalJsonSha256FromValue(v)])), migration_sha256:await normalizedTextSha256(migrationPath), safety_assertions:safety }
  await writeFile(paths.manifest, JSON.stringify(manifest,null,2)+'\n')
  const md = `# PR-0055 Reviewed-Boundary Audit Identity

Audit identity authority approved: true.

PR-0055 extends content_staging.migration_audit_events with nullable structured identity columns and a reviewed-boundary-only partial unique index on event_key. Legacy audit rows remain valid because new columns are nullable and constraints are scoped to package_id = '${eventPackage}'.

Logical identity: ${identityColumns.join(', ')}. Event keys are lowercase hex SHA-256 values over the fixed label ${eventKeyAlgorithm} followed by fixed-order length-delimited identity fields. Application action: ${eventActions.application} (${statuses.applicationBefore} -> ${statuses.applicationAfter}). Rollback action: ${eventActions.rollback} (${statuses.rollbackBefore} -> ${statuses.rollbackAfter}); rollback execution remains unauthorized. Event version: ${eventVersion}.

Future duplicate handling must use the predicate-bearing PostgreSQL conflict target: ON CONFLICT (event_key) WHERE ${conflictTargetPredicate} DO NOTHING. DO NOTHING alone is never equality proof; any conflict must be followed by exact structured-field, canonical-payload, authority-hash, and package-hash equality verification before classifying the event as a verified no-op.

Triage validator baseline: npm run content:staging:segments:triage:validate fails unchanged on PR-0054 base and PR-0055 with expected review_queue_sha256 06d53501303eaca9aa8a1ba9f81aa10fed02801996eba90ba38f9e15b3440b66 and actual 3045ca47395bfa47fb883eddaaa6a0b048a4a68e9e80897e2bdba48bb7f3d505; PR-0055 does not modify consumed triage files.

Migration generated: ${migrationPath}. Migration executed: false. Application SQL generated: false. Rollback SQL generated: false. Database modified: false.
`
  await writeFile(paths.summary, md); await writeFile(paths.docs, md)
  return manifest
}
if (import.meta.url === `file://${process.argv[1]}`) console.log(JSON.stringify(await build(), null, 2))
