import {sources as upstreamSources} from './reviewed_boundary_staging_authorization_constants.mjs'
export const packageId='reading-segment-reviewed-boundary-staging-execution-pr0060'
export const modes=['blocked','fixture-apply','staging-apply','fixture-reconcile','staging-reconcile','production-apply','production-reconcile']
export const applyModes=['fixture-apply','staging-apply']
export const classifications=['MATCH','STATUS_ALREADY_APPLIED','STATUS_UNEXPECTED','IDENTITY_MISSING','DUPLICATE_TARGET','UNAUTHORIZED_TARGET','TARGET_SET_MISMATCH','BOUNDARY_DRIFT','CONTENT_DRIFT','STORED_CONTENT_DIGEST_MISMATCH','METADATA_DRIFT','SOURCE_HASH_DRIFT','INSUFFICIENT_BASELINE','AUDIT_EVENT_CONFLICT','AUDIT_IDENTITY_INVALID','DATABASE_IDENTITY_MISMATCH','AUTHORIZATION_EXPIRED','AUTHORIZATION_REVOKED','EXECUTION_TOKEN_INVALID','EXECUTION_TOKEN_EXPIRED','EXECUTION_TOKEN_ALREADY_USED','PACKAGE_AUTHORITY_BLOCKED']
export const outcomes=['STAGING_EXECUTION_NOT_STARTED','STAGING_EXECUTION_READY','STAGING_EXECUTION_COMMITTED','STAGING_EXECUTION_ALREADY_COMPLETED','STAGING_EXECUTION_ROLLED_BACK','STAGING_EXECUTION_PARTIAL','STAGING_EXECUTION_INCONSISTENT','STAGING_EXECUTION_FAILED','STAGING_RECONCILIATION_COMPLETE','STAGING_RECONCILIATION_BLOCKED']
export const authorityInputs=['admitted-evidence','database-attestation','collector-attestation','technical-reviewer-attestation','execution-authorizer-attestation','authorization-decision','execution-token','application-manifest','runtime-manifest','staging-authorization-manifest','expected-database-identity','mode','execution-identifier','operator-confirmation']
export const sources={...upstreamSources,staging_admission_policy:'content/migration/reading-segment-reviewed-boundary-staging-evidence-admission-policy.json',staging_admission_contract:'content/migration/reading-segment-reviewed-boundary-staging-evidence-admission-contract.json',staging_database_attestation:'content/migration/reading-segment-reviewed-boundary-staging-database-attestation-contract.json',staging_baseline:'content/migration/reading-segment-reviewed-boundary-staging-baseline-contract.json',staging_attestation:'content/migration/reading-segment-reviewed-boundary-staging-attestation-contract.json',staging_expiry:'content/migration/reading-segment-reviewed-boundary-staging-authorization-expiry-contract.json',staging_revocation:'content/migration/reading-segment-reviewed-boundary-staging-authorization-revocation-contract.json',staging_decision:'content/migration/reading-segment-reviewed-boundary-staging-authorization-decision-contract.json',staging_token:'content/migration/reading-segment-reviewed-boundary-staging-execution-token-contract.json',staging_gate:'content/migration/reading-segment-reviewed-boundary-staging-authorization-gate.json',staging_readiness:'content/migration/reading-segment-reviewed-boundary-staging-readiness-evidence.json',staging_storage:'content/migration/reading-segment-reviewed-boundary-staging-storage-policy.json',staging_authorization_manifest:'content/migration/reading-segment-reviewed-boundary-staging-authorization-manifest.json'}
export const artifactNames=['policy','modes','authority-inputs','preconnection-gate','database-identity-gate','transaction-contract','locking-contract','preflight-contract','idempotency-contract','audit-contract','token-consumption-contract','postflight-contract','execution-evidence-contract','reconciliation-contract','rollback-distinction-contract','execution-gate','missing-authority','readiness-evidence']
export const prefix='content/migration/reading-segment-reviewed-boundary-staging-execution-'
export const evidencePath='tmp/reviewed-boundary-staging-application-execution-evidence.json'
export const receiptPath='tmp/reviewed-boundary-staging-execution-token-consumption-receipt.json'
