import {canonicalJsonSha256FromValue} from './hash_utils.mjs'
import {measureReviewedBoundaryContent} from './reviewed_boundary_content_normalization.mjs'
export const identityKey=x=>`${x.run_id}\0${x.book_id}\0${x.segment_key}`
export function validateMode({mode='blocked',environment,operatorConfirmation,packageManifestHash}){if(mode==='blocked'||!mode)throw Error('RUNTIME_MODE_BLOCKED: explicit mode required');if(!['fixture','staging-readonly','production-readonly'].includes(mode))throw Error('RUNTIME_MODE_BLOCKED: unapproved mode');if(mode==='production-readonly')throw Error('RUNTIME_MODE_BLOCKED: production collection is not authorized');if(!environment)throw Error('DATABASE_IDENTITY_MISMATCH: expected environment required');if(mode==='staging-readonly'&&environment!=='staging')throw Error('DATABASE_IDENTITY_MISMATCH: staging mode requires staging identity');if(mode==='fixture'&&environment!=='fixture')throw Error('DATABASE_IDENTITY_MISMATCH: fixture mode requires fixture identity');if(!operatorConfirmation)throw Error('operator confirmation required');if(!/^[a-f0-9]{64}$/.test(packageManifestHash??''))throw Error('package manifest hash required');return true}
export function reconstructRow(row,expected){const m=measureReviewedBoundaryContent(row.content,row.word_count);const identity={run_id:String(row.run_id),book_id:Number(row.book_id),segment_key:row.segment_key};const boundary={source_key:row.source_key,segment_order:Number(row.segment_order),segment_index:Number(row.segment_index),segment_count:Number(row.segment_count),boundary_version:Number(row.boundary_version),start_locator:row.start_locator,end_locator:row.end_locator,display_title:row.display_title};const content={recomputed_normalized_content_sha256:m.recomputed_normalized_content_sha256,recomputed_word_count:m.word_count,normalized_content_length:m.normalized_content_length,content_byte_length:m.content_byte_length};const status={observed_approval_status:row.approval_status,expected_previous_approval_status:expected.current_approval_status,intended_resulting_approval_status:expected.intended_resulting_approval_status};return {...identity,...boundary,stored_word_count:row.word_count,stored_normalized_content_sha256:row.normalized_content_sha256,...content,stored_digest_matches_recomputed:row.normalized_content_sha256===content.recomputed_normalized_content_sha256,...status,created_at:row.created_at,updated_at:row.updated_at,identity_sha256:canonicalJsonSha256FromValue(identity),boundary_sha256:canonicalJsonSha256FromValue(boundary),content_sha256:canonicalJsonSha256FromValue(content),full_pre_application_sha256:canonicalJsonSha256FromValue({identity_sha256:canonicalJsonSha256FromValue(identity),boundary_sha256:canonicalJsonSha256FromValue(boundary),content_sha256:canonicalJsonSha256FromValue(content),observed_pre_application_status:row.approval_status})}}
export function classifyTarget(actual,expected,audit=[]){if(!actual)return 'IDENTITY_MISSING';if(audit.some(x=>x.invalid_identity))return 'AUDIT_IDENTITY_INVALID';if(audit.some(x=>x.conflict))return 'AUDIT_EVENT_CONFLICT';if(!actual.source_key||!actual.start_locator||!actual.end_locator||!actual.display_title||actual.content_byte_length===null)return 'INSUFFICIENT_BASELINE';if(!actual.stored_digest_matches_recomputed)return 'STORED_CONTENT_DIGEST_MISMATCH';if(actual.stored_word_count!==actual.recomputed_word_count)return 'CONTENT_DRIFT';if(expected.segment_order!==actual.segment_order)return 'BOUNDARY_DRIFT';if(actual.observed_approval_status===expected.intended_resulting_approval_status)return 'STATUS_ALREADY_APPLIED';if(actual.observed_approval_status!==expected.current_approval_status)return 'STATUS_UNEXPECTED';return 'MATCH'}
export function reconcileAudit(events,status){const apps=events.filter(x=>x.event_action==='status-advanced'),rolls=events.filter(x=>x.event_action==='status-rollback');if(events.some(x=>x.invalid_identity))return 'INVALID_EVENT_IDENTITY';if(events.some(x=>x.invalid_payload))return 'INVALID_EVENT_PAYLOAD';if(apps.length>1||rolls.length>1)return 'DUPLICATE_SEMANTIC_EVENT';if(apps.some(x=>x.conflict))return 'CONFLICTING_APPLICATION_EVENT';if(apps.length&&rolls.length)return 'APPLICATION_AND_ROLLBACK_EXIST';if(rolls.length)return 'UNEXPECTED_ROLLBACK_EVENT';if(apps.length&&status!=='content-review')return 'APPLICATION_EVENT_STATUS_NOT_APPLIED';if(!apps.length&&status==='content-review')return 'APPLIED_STATUS_EVENT_ABSENT';return apps.length?'MATCHING_APPLICATION_EVENT':'NO_APPLICATION_EVENT'}
export function evidenceHash(e){const copy=structuredClone(e);delete copy.evidence_sha256;return canonicalJsonSha256FromValue(copy)}
export function containsForbidden(value){const text=JSON.stringify(value);return /(?:password|access[_-]?token|connection[_-]?string|supabase[_-]?key|postgres(?:ql)?:\/\/|"content"\s*:)/i.test(text)}
