export const packageId='reading-segment-reviewed-boundary-runtime-integrity-pr0058'
export const packageVersion='1.0.0'
export const evidencePath='tmp/reviewed-boundary-runtime-integrity-staging-preflight-evidence.json'
export const sources={
 application_plan:'content/migration/reading-segment-reviewed-boundary-consolidated-application-plan.json',application_evidence:'content/migration/reading-segment-reviewed-boundary-consolidated-application-evidence.json',execution_authority_manifest:'content/migration/reading-segment-reviewed-boundary-execution-authority-manifest.json',status_only_contract:'content/migration/reading-segment-source-review-status-only-contract.json',audit_identity_contract:'content/migration/reading-segment-reviewed-boundary-audit-event-identity-contract.json',audit_payload_contract:'content/migration/reading-segment-reviewed-boundary-audit-event-payload-contract.json',audit_conflict_contract:'content/migration/reading-segment-reviewed-boundary-audit-conflict-contract.json',integrity_policy:'content/migration/reading-segment-reviewed-boundary-content-integrity-policy.json',integrity_targets:'content/migration/reading-segment-reviewed-boundary-content-integrity-targets.json',integrity_snapshot:'content/migration/reading-segment-reviewed-boundary-content-integrity-snapshot.json',projection_contract:'content/migration/reading-segment-reviewed-boundary-content-integrity-projection-contract.json',drift_contract:'content/migration/reading-segment-reviewed-boundary-content-integrity-drift-contract.json',rollback_baseline:'content/migration/reading-segment-reviewed-boundary-content-integrity-rollback-baseline.json',audit_compatibility:'content/migration/reading-segment-reviewed-boundary-content-integrity-audit-compatibility.json',integrity_manifest:'content/migration/reading-segment-reviewed-boundary-content-integrity-manifest.json',application_operations:'content/migration/reading-segment-reviewed-boundary-application-rollback-application-operations.json',rollback_operations:'content/migration/reading-segment-reviewed-boundary-application-rollback-rollback-operations.json',preflight_contract:'content/migration/reading-segment-reviewed-boundary-application-rollback-preflight-contract.json',transaction_contract:'content/migration/reading-segment-reviewed-boundary-application-rollback-transaction-contract.json',execution_gate:'content/migration/reading-segment-reviewed-boundary-application-rollback-execution-gate.json',readiness_evidence:'content/migration/reading-segment-reviewed-boundary-application-rollback-application-readiness-evidence.json',application_rollback_manifest:'content/migration/reading-segment-reviewed-boundary-application-rollback-manifest.json',reading_segments_schema:'supabase/migrations/20260803033000_content_staging_foundation.sql',audit_schema_extension:'supabase/migrations/20260805005500_reviewed_boundary_audit_identity.sql'}
export const artifactNames=['policy','databaseIdentity','targetQuery','reconstruction','auditReconciliation','classification','evidenceContract','gate','missingAuthority','readiness']
const suffix={policy:'integrity-policy',databaseIdentity:'database-identity-contract',targetQuery:'target-query-contract',reconstruction:'integrity-reconstruction-contract',auditReconciliation:'audit-reconciliation-contract',classification:'classification-contract',evidenceContract:'evidence-contract',gate:'staging-preflight-gate',missingAuthority:'missing-authority',readiness:'readiness-evidence'}
export const paths=Object.fromEntries(artifactNames.map(n=>[n,`content/migration/reading-segment-reviewed-boundary-runtime-${suffix[n]}.json`]))
paths.manifest='content/migration/reading-segment-reviewed-boundary-runtime-integrity-manifest.json'
export const modes=['blocked','fixture','staging-readonly','production-readonly']
export const classes=['MATCH','STATUS_ALREADY_APPLIED','STATUS_UNEXPECTED','IDENTITY_MISSING','DUPLICATE_TARGET','UNAUTHORIZED_TARGET','TARGET_SET_MISMATCH','BOUNDARY_DRIFT','CONTENT_DRIFT','STORED_CONTENT_DIGEST_MISMATCH','METADATA_DRIFT','SOURCE_HASH_DRIFT','INSUFFICIENT_BASELINE','AUDIT_EVENT_CONFLICT','AUDIT_IDENTITY_INVALID','PACKAGE_AUTHORITY_BLOCKED','DATABASE_IDENTITY_MISMATCH','SCHEMA_MISMATCH','RUNTIME_MODE_BLOCKED']
export const auditClasses=['NO_APPLICATION_EVENT','MATCHING_APPLICATION_EVENT','APPLICATION_EVENT_STATUS_NOT_APPLIED','APPLIED_STATUS_EVENT_ABSENT','CONFLICTING_APPLICATION_EVENT','UNEXPECTED_ROLLBACK_EVENT','APPLICATION_AND_ROLLBACK_EXIST','DUPLICATE_SEMANTIC_EVENT','INVALID_EVENT_IDENTITY','INVALID_EVENT_PAYLOAD']
