import {createHash} from 'node:crypto'
import {lstat,readFile,writeFile,mkdir} from 'node:fs/promises'

export const TARGET_COUNT=74
export const OBSERVATION_HOURS=24
export const AUTHORIZATION_HOURS=4
export const lifecycle=['REPOSITORY_PACKAGE_DEFINED','STAGING_EVIDENCE_REQUIRED','STAGING_EVIDENCE_ADMITTED','STAGING_REVIEW_REQUIRED','STAGING_AUTHORIZED','STAGING_EXECUTION_STARTED','STAGING_EXECUTION_COMMITTED','STAGING_RECONCILIATION_COMPLETE','STAGING_OBSERVATION_WINDOW_ACTIVE','STAGING_VALIDATED','PRODUCTION_EVIDENCE_REQUIRED','PRODUCTION_REVIEW_REQUIRED','PRODUCTION_AUTHORIZATION_ELIGIBLE','PRODUCTION_AUTHORIZED','PRODUCTION_EXECUTION_STARTED','PRODUCTION_EXECUTION_COMMITTED','PRODUCTION_RECONCILIATION_COMPLETE','MIGRATION_CLOSURE_REVIEW_REQUIRED','MIGRATION_COMPLETED','MIGRATION_ROLLED_BACK','MIGRATION_BLOCKED','MIGRATION_INCONSISTENT','MIGRATION_REVOKED']
export const observationOutcomes=['STAGING_OBSERVATION_NOT_STARTED','STAGING_OBSERVATION_ACTIVE','STAGING_OBSERVATION_PASSED','STAGING_OBSERVATION_FAILED','STAGING_OBSERVATION_EXPIRED','STAGING_OBSERVATION_SUPERSEDED','STAGING_OBSERVATION_INCONSISTENT']
export const reconciliationOutcomes=['PRODUCTION_EXECUTION_NOT_STARTED','PRODUCTION_EXECUTION_READY','PRODUCTION_EXECUTION_COMMITTED','PRODUCTION_EXECUTION_ALREADY_COMPLETED','PRODUCTION_EXECUTION_PARTIAL','PRODUCTION_EXECUTION_INCONSISTENT','PRODUCTION_EXECUTION_FAILED','PRODUCTION_ROLLBACK_STARTED','PRODUCTION_ROLLBACK_COMMITTED','PRODUCTION_ROLLBACK_INCONSISTENT','PRODUCTION_RECONCILIATION_COMPLETE','PRODUCTION_RECONCILIATION_BLOCKED']
export const authorityFields=['source_snapshot_complete','source_snapshot_verified','content_integrity_authority_approved','application_preflight_ready','rollback_baseline_ready','application_execution_authorized','rollback_execution_authorized','staging_application_executed','staging_reconciliation_complete','staging_observation_passed','staging_validation_approved','production_collection_authorized','production_evidence_admitted','production_integrity_verified','production_preflight_ready','production_rollback_ready','production_execution_authorized','production_application_executed','production_reconciliation_complete','production_rollback_execution_authorized','migration_closure_approved','migration_completed']
export const authority=Object.fromEntries(authorityFields.map(k=>[k,false]))
export function finalized(value){return JSON.parse(JSON.stringify(value))}
export function canonical(value){if(value===undefined)throw Error('undefined forbidden');value=finalized(value);if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])]));return value}
export function digest(value,selfField){const v=structuredClone(finalized(value));if(selfField)delete v[selfField];return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex')}
export function observe({reconciliation_complete,commit_time,evaluation_time,drift=false,rollback=false,defect=false}){if(!reconciliation_complete)return 'STAGING_OBSERVATION_NOT_STARTED';if(drift||rollback||defect)return 'STAGING_OBSERVATION_FAILED';const elapsed=Date.parse(evaluation_time)-Date.parse(commit_time);if(!Number.isFinite(elapsed)||elapsed<0)return 'STAGING_OBSERVATION_INCONSISTENT';return elapsed>=OBSERVATION_HOURS*3600000?'STAGING_OBSERVATION_PASSED':'STAGING_OBSERVATION_ACTIVE'}
export function evaluateProduction(input={}){const real=input.mode==='production-review';const roles=['production-collection-operator','production-technical-reviewer','production-execution-authorizer'];const ok=real&&input.staging_observation_outcome==='STAGING_OBSERVATION_PASSED'&&input.staging_validation_approved===true&&input.production_collector_mode==='production-readonly'&&input.environment_class==='production'&&input.target_count===74&&input.integrity_verified===true&&input.expected_statuses_verified===true&&input.audit_compatible===true&&roles.every(r=>input.attestation_roles?.includes(r));return {...authority,production_collection_authorized:ok,production_evidence_admitted:ok,production_integrity_verified:ok,production_preflight_ready:ok,production_rollback_ready:ok,production_execution_authorized:ok,lifecycle_state:ok?'PRODUCTION_AUTHORIZED':'STAGING_EVIDENCE_REQUIRED'} }
export async function safeJson(path,max=2_000_000){const s=await lstat(path);if(s.isSymbolicLink()||!s.isFile())throw Error('input must be a regular non-symlink file');if(s.size>max)throw Error('input oversized');const raw=await readFile(path,'utf8');if(/"(?:password|connection_string|access_token|api_key|raw_database_host|full_content)"\s*:/i.test(raw))throw Error('secret-like or full-content field rejected');return JSON.parse(raw)}
export function exactFields(value,fields){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join()!==[...fields].sort().join())throw Error('closed-world field violation')}
export async function writeTemporary(name,value,path=`tmp/${name}.json`){await mkdir('tmp',{recursive:true});await writeFile(path,JSON.stringify(value,null,2)+'\n',{mode:0o600});return path}
