import { readFile } from 'node:fs/promises'
import { canonicalJsonSha256, canonicalJsonSha256FromValue, sha256Raw } from './hash_utils.mjs'
import { deriveStructuralHeadingMergeContract, paths, safetyAssertions, requiredMissing } from './build_source_review_structural_heading_merge_contract.mjs'
const readJson=async p=>JSON.parse(await readFile(p,'utf8'))
const fail=(e,m)=>e.push(m); const sort=v=>[...v].sort((a,b)=>String(a).localeCompare(String(b))); const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b)
const counts=a=>a.reduce((m,x)=>(m.set(x,(m.get(x)??0)+1),m),new Map())
const keyset=o=>sort(Object.keys(o??{})); const values=o=>Object.values(o??{})
const setEq=(a,b)=>same(sort(a),sort(b)); const assertSet=(e,name,a,b)=>{if(!setEq(a,b)) fail(e,`${name} set mismatch; missing ${sort(b.filter(x=>!new Set(a).has(x))).join(', ')} extra ${sort(a.filter(x=>!new Set(b).has(x))).join(', ')}`)}
const forbidden=/\b(update\s+|insert\s+into|delete\s+from|merge\s+into|truncate|alter\s+|drop\s+|create\s+function|do\s+\$|begin;|commit;|rollback;|psql|createClient|supabase\.co|service_role|postgres:)\b/i
const leakage=/"(?:source_text|source_excerpt|private_evidence|database_change_applied|migration_applied|database_modified|supabase_modified|production_modified|cutover_enabled)"\s*:\s*(?:"[^"]+"|true)/i
export const inputHashFieldToPath={ immutable_historical_progress_sha256:paths.historicalProgress, archived_pr0045_pr0046_progress_snapshot_sha256:paths.pr0045Current, current_cumulative_progress_sha256:paths.progress, pr0048_readiness_policy_sha256:paths.readinessPolicy, pr0048_readiness_plan_sha256:paths.readinessPlan, pr0049_status_only_contract_sha256:paths.statusOnlyContract, pr0049_status_only_plan_sha256:paths.statusOnlyPlan, pr0050_locator_contract_sha256:paths.locatorContract, pr0050_locator_plan_sha256:paths.locatorPlan, pr0050_locator_evidence_sha256:paths.locatorEvidence, pr0050_locator_missing_authority_sha256:paths.locatorMissingAuthority, staging_schema_sha256:paths.stagingSchema, source_inspection_packets_sha256:paths.sourceInspectionPackets, mechanical_application_policy_sha256:paths.mechanicalPolicy, mechanical_application_plan_sha256:paths.mechanicalPlan, mechanical_application_evidence_sha256:paths.mechanicalEvidence, reconstruction_authority_sha256:paths.reconstructionPlan, editorial_node_authority_sha256:paths.editorialNodePlan, reader_reference_authority_sha256:paths.readerReferenceAuthority, ...Object.fromEntries(paths.decisionInputs.map(p=>[`${p.split('/').at(-1).replace('.json','').replaceAll('-','_')}_sha256`,p])), recovery_consolidation_sha256:paths.recoveryConsolidation, book_3_manual_adjudication_sha256:paths.book3Manual, remaining_manual_adjudication_sha256:paths.remainingManual }
const expectedOutcome={'adjust-successor-start':6,'confirm-successor-start':73,'exclude-structural-heading':53,'retain-intro-segment':1,unresolved:11}
const expectedModels=['A-soft-exclusion','B-status-based-exclusion','C-logical-merge-without-text-mutation','D-physical-segment-merge','E-editorial-node-only-exclusion']
const expectedPreserved=['source text','heading segment key','successor segment key when repository-provided','segment order','start locator','end locator','book identity','source-page identity','user progress','reader sessions','bookmarks','notes','highlights']
const expectedTotals={public_decision_count:144,exclude_structural_heading_decisions:53,application_ready_merge_decisions:0,complete_operation_records:0,incomplete_operation_records:53}
const planFields=['book_id','book_slug','packet_id','current_heading_segment_key','heading_segment_order','predecessor_segment_key','predecessor_segment_order','successor_segment_key','successor_segment_order','final_outcome','review_status','reviewer_confidence','source_artifact','resolution_artifact','heading_row_identity','successor_row_identity','predecessor_row_identity','authorized_operation_type','operation_model','target_tables','changed_fields','unchanged_fields','source_text_preservation','locator_behavior','segment_order_behavior','segment_key_behavior','editorial_node_behavior','active_disabled_status_behavior','user_progress_remapping_behavior','reader_session_behavior','bookmark_note_highlight_behavior','audit_event_identity','idempotency_identity','rollback_requirements','operation_completeness_status','missing_authority','application_ready']
const dupes=a=>sort([...counts(a)].filter(([,c])=>c>1).map(([x])=>x))
const reasonSetFor=r=>r.successor_segment_key?requiredMissing:['successor_segment_key',...requiredMissing]
export async function validateArtifacts({contract,plan,evidence,missing,operationModels,summary,docs}){
 const errors=[]; const d=await deriveStructuralHeadingMergeContract(); const expected=new Map(d.records.map(r=>[r.decision_id,r])); const records=plan.records??[]; const ids=records.map(r=>r.decision_id); const idsSet=new Set(ids)
 if(d.readiness.records.length!==144) fail(errors,'wrong public-decision count'); if(d.records.length!==53) fail(errors,'wrong merge-decision count')
 if(records.length!==53) fail(errors,`plan record count must be 53, found ${records.length}`); if(idsSet.size!==53) fail(errors,`unique decision count must be 53, found ${idsSet.size}`)
 const dupIds=dupes(ids); if(dupIds.length) fail(errors,`duplicate decision IDs: ${dupIds.join(', ')}`); assertSet(errors,'plan decision IDs',[...idsSet],[...expected.keys()])
 const headingTuples=records.map(r=>`${r.book_id}:${r.current_heading_segment_key}:${r.heading_segment_order}`); const headingDup=dupes(headingTuples); if(headingDup.length) fail(errors,`duplicate heading targets: ${headingDup.join(', ')}`)
 for(const r of records){ const x=expected.get(r.decision_id); if(!x) continue; for(const k of planFields) if(!same(r[k],x[k])) fail(errors,`${r.decision_id}: ${k} mismatch`); if(r.operation_completeness_status!=='incomplete') fail(errors,`${r.decision_id}: completeness must be incomplete`); if(r.application_ready!==false) fail(errors,`${r.decision_id}: application_ready must be false`); if(!r.heading_row_identity) fail(errors,`${r.decision_id}: missing heading identity`) }
 const incomplete=records.filter(r=>r.operation_completeness_status==='incomplete'); const incompleteById=new Map(incomplete.map(r=>[r.decision_id,r])); const miss=missing.records??[]; const missIds=miss.map(r=>r.decision_id); const missUnique=new Set(missIds)
 if(incomplete.length!==53) fail(errors,`incomplete plan records must be 53, found ${incomplete.length}`); if(miss.length!==53) fail(errors,`missing-authority record count must be 53, found ${miss.length}`); if(missUnique.size!==53) fail(errors,`missing-authority unique IDs must be 53, found ${missUnique.size}`)
 const missDup=dupes(missIds); if(missDup.length) fail(errors,`duplicate missing-authority IDs: ${missDup.join(', ')}`); assertSet(errors,'missing-authority IDs',[...missUnique],[...incompleteById.keys()])
 for(const m of miss){ const r=incompleteById.get(m.decision_id); if(!r) continue; const comparisons={decision_id:r.decision_id,book_id:r.book_id,book_slug:r.book_slug,packet_id:r.packet_id,heading_segment_key:r.current_heading_segment_key,heading_segment_order:r.heading_segment_order,predecessor_segment_key:r.predecessor_segment_key,predecessor_segment_order:r.predecessor_segment_order,successor_segment_key:r.successor_segment_key,successor_segment_order:r.successor_segment_order,predecessor_row_identity:r.predecessor_row_identity,successor_row_identity:r.successor_row_identity,operation_completeness_status:r.operation_completeness_status,application_ready:r.application_ready}
  for(const [k,v] of Object.entries(comparisons)) if(!same(m[k],v)) fail(errors,`${m.decision_id}: missing-authority ${k} mismatch`)
  const reasons=m.missing_authority??[]; const rd=dupes(reasons); if(rd.length) fail(errors,`${m.decision_id}: duplicate missing-authority reasons ${rd.join(', ')}`); assertSet(errors,`${m.decision_id} missing-authority reasons`,reasons,reasonSetFor(r)); if(m.operation_completeness_status!=='incomplete') fail(errors,`${m.decision_id}: missing-authority completeness must be incomplete`); if(m.application_ready!==false) fail(errors,`${m.decision_id}: missing-authority application_ready must be false`)
 }
 const succTargets=records.filter(r=>r.successor_row_identity).map(r=>({r,k:`${r.successor_row_identity.run_id}:${r.successor_row_identity.book_id}:${r.successor_row_identity.segment_key}:${r.successor_row_identity.segment_order}`})); const succDup=dupes(succTargets.map(x=>x.k)); if(succDup.length) fail(errors,`duplicate/conflicting successor target tuples: ${succDup.join(', ')}`)
 const headingSet=new Set(headingTuples); for(const {r} of succTargets){ if(r.successor_row_identity.book_id!==r.book_id) fail(errors,`${r.decision_id}: successor is in a different book`); if(r.successor_segment_key===r.current_heading_segment_key) fail(errors,`${r.decision_id}: heading targets itself`); if(!(r.successor_segment_order>r.heading_segment_order)) fail(errors,`${r.decision_id}: successor order must be after heading order`); if(!(r.predecessor_segment_order<r.heading_segment_order)) fail(errors,`${r.decision_id}: predecessor order must be before heading order`); if(headingSet.has(`${r.book_id}:${r.successor_segment_key}:${r.successor_segment_order}`)) fail(errors,`${r.decision_id}: successor is also a heading target`) }
 if(!same(evidence.outcome_distribution,expectedOutcome)) fail(errors,'outcome distribution mismatch')
 for(const [k,v] of Object.entries(expectedTotals)){ if(evidence.totals?.[k]!==v) fail(errors,`evidence total ${k} mismatch`); if(k!=='public_decision_count'&&contract.result?.[k]!==undefined&&contract.result[k]!==v) fail(errors,`contract total ${k} mismatch`); if(plan[k]!==undefined&&plan[k]!==v) fail(errors,`plan total ${k} mismatch`) }
 if(plan.complete_operation_records!==0||plan.incomplete_operation_records!==53||plan.application_ready_merge_decisions!==0) fail(errors,'plan totals mismatch'); if(contract.result?.complete_operation_records!==0||contract.result?.incomplete_operation_records!==53||contract.result?.application_ready_merge_decisions!==0) fail(errors,'contract result totals mismatch')
 if(contract.structural_heading_merge_contract_approved!==false||plan.structural_heading_merge_contract_approved!==false||evidence.structural_heading_merge_contract_approved!==false) fail(errors,'incorrect contract approval'); if(contract.rights_status!=='credited-source-edition') fail(errors,'rights status mismatch'); if(contract.authorized_mutation!==null) fail(errors,'authorized_mutation must be null')
 if(!same(contract.changed_fields,[])) fail(errors,'changed_fields must be empty'); if(!same(contract.preconditions,[])) fail(errors,'preconditions must be empty'); if(!same(contract.postconditions,[])) fail(errors,'postconditions must be empty'); if(contract.idempotency?.approved!==false) fail(errors,'idempotency.approved must be false'); if(contract.rollback?.approved!==false) fail(errors,'rollback.approved must be false')
 const preserved=contract.preserved_fields??[]; const preservedDup=dupes(preserved); if(preservedDup.length) fail(errors,`duplicate preserved fields: ${preservedDup.join(', ')}`); assertSet(errors,'preserved fields',preserved,expectedPreserved)
 const supported=operationModels.supported_operation_models??[]; if(!same(supported,[])) fail(errors,'supported_operation_models must be exactly empty')
 const rejected=operationModels.rejected_operation_models??[]; const rejectedIds=rejected.map(m=>m.model); const modelDup=dupes(rejectedIds); if(modelDup.length) fail(errors,`duplicate rejected models: ${modelDup.join(', ')}`); assertSet(errors,'rejected model IDs',rejectedIds,expectedModels)
 for(const m of rejected){ if(m.approved!==false) fail(errors,`${m.model}: model approved must be false`); if(m.application_ready===true) fail(errors,`${m.model}: model application_ready must not be true`); if(typeof m.reason!=='string'||m.reason.trim().length===0) fail(errors,`${m.model}: rejection reason is required`) }
 assertSet(errors,'contract rejected model IDs',contract.rejected_operation_models??[],expectedModels); if(!same(contract.supported_operation_models??[],supported)) fail(errors,'contract supported model list mismatch'); if(!setEq(contract.rejected_operation_models??[],rejectedIds)) fail(errors,'contract rejected model list mismatch')
 if(!same(evidence.input_hash_field_to_path,inputHashFieldToPath)) fail(errors,'input hash field-to-path mapping mismatch'); const actualKeys=keyset(evidence.input_hashes); const expectedKeys=keyset(inputHashFieldToPath); if(!same(actualKeys,expectedKeys)) fail(errors,'input hash key set mismatch')
 const pathDup=sort([...counts(values(inputHashFieldToPath))].filter(([,c])=>c>1).map(([p])=>p)); if(pathDup.length) fail(errors,`duplicate input hash paths are not expected: ${pathDup.join(', ')}`)
 for(const [k,p] of Object.entries(inputHashFieldToPath)){ const h=p.endsWith('.sql')||p.endsWith('.ts')?await sha256Raw(p):await canonicalJsonSha256(p); if(evidence.input_hashes?.[k]!==h) fail(errors,`${k}: stale hash`) }
 if(evidence.artifact_hashes?.contract_sha256!==canonicalJsonSha256FromValue(contract)) fail(errors,'contract hash mismatch'); if(evidence.artifact_hashes?.plan_sha256!==canonicalJsonSha256FromValue(plan)) fail(errors,'plan hash mismatch'); if(evidence.artifact_hashes?.missing_authority_sha256!==canonicalJsonSha256FromValue(missing)) fail(errors,'missing hash mismatch'); if(evidence.artifact_hashes?.operation_models_sha256!==canonicalJsonSha256FromValue(operationModels)) fail(errors,'operation-model hash mismatch')
 for(const [k,v] of Object.entries(safetyAssertions)) if(contract.safety_assertions?.[k]!==v||evidence.assertions?.[k]!==v||v!==false) fail(errors,`${k}: safety assertion must be present and false`)
 for(const text of [JSON.stringify(contract),JSON.stringify(plan),JSON.stringify(evidence),JSON.stringify(missing),JSON.stringify(operationModels),summary,docs]){ if(forbidden.test(text)) fail(errors,'mutating SQL or DB/Supabase code detected'); if(leakage.test(text)) fail(errors,'source/private/applied-state leakage detected') }
 if(errors.length) throw new Error(errors.join('\n'))
 return {decision_count:53, approved:false, exact_set_equality:true, missing_authority_exact_equality:true, operation_models_exact_equality:true, hash_mapping_exact_equality:true, successor_conflicts:false, incomplete:53, outcome_distribution:expectedOutcome}
}
if(import.meta.url===`file://${process.argv[1]}`){const a={contract:await readJson(paths.contract),plan:await readJson(paths.plan),evidence:await readJson(paths.evidence),missing:await readJson(paths.missingAuthority),operationModels:await readJson(paths.operationModels),summary:await readFile(paths.summary,'utf8'),docs:await readFile(paths.docs,'utf8')}; console.log(JSON.stringify(await validateArtifacts(a),null,2))}
