import { readFile } from 'node:fs/promises'
import { canonicalJsonSha256, canonicalJsonSha256FromValue, sha256Raw } from './hash_utils.mjs'
import { deriveLocatorAdjustmentContract, paths, requiredMissing, safetyAssertions } from './build_source_review_successor_locator_adjustment_contract.mjs'
const readJson=async p=>JSON.parse(await readFile(p,'utf8'))
const fail=(e,m)=>e.push(m)
const sort=(v)=>[...v].sort((a,b)=>String(a).localeCompare(String(b)))
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b)
const count=(items)=>items.reduce((m,x)=>(m.set(x,(m.get(x)??0)+1),m),new Map())
const forbiddenSql=/\b(update\s+|insert\s+into|delete\s+from|merge\s+into|truncate|alter\s+table|drop\s+table|create\s+function|do\s+\$|begin;|commit;|rollback;|psql|createClient|supabase\.co|service_role|postgres:)\b/i
const leakageKeys=/"(?:source_text|source_excerpt|source_text_included|source_excerpt_included|private_evidence|database_change_applied|migration_applied|database_modified|cutover_enabled)"\s*:\s*(?:"[^"]+"|true)/i
export const inputHashFieldToPath = { immutable_historical_progress_sha256:paths.historicalProgress, archived_pr0045_pr0046_progress_snapshot_sha256:paths.pr0045Current, current_cumulative_progress_sha256:paths.progress, pr0048_readiness_policy_sha256:paths.readinessPolicy, pr0048_readiness_plan_sha256:paths.readinessPlan, pr0049_status_only_contract_sha256:paths.statusOnlyContract, pr0049_status_only_plan_sha256:paths.statusOnlyPlan, staging_schema_sha256:paths.stagingSchema, source_inspection_packets_sha256:paths.sourceInspectionPackets, mechanical_application_policy_sha256:paths.mechanicalPolicy, mechanical_application_plan_sha256:paths.mechanicalPlan, mechanical_application_evidence_sha256:paths.mechanicalEvidence, ...Object.fromEntries(paths.decisionInputs.map(p=>[`${p.split('/').at(-1).replace('.json','').replaceAll('-','_')}_sha256`,p])) }
const expectedOutcomeDistribution = {'adjust-successor-start':6,'confirm-successor-start':73,'exclude-structural-heading':53,'retain-intro-segment':1,unresolved:11}
const requiredMissingSorted = sort(requiredMissing)
const expectedFor = (r) => ({ decision_id:r.decision_id, book_id:r.book_id, book_slug:r.book_slug, packet_id:r.packet_id, current_segment_key:r.current_segment_key, current_segment_order:r.current_segment_order, successor_segment_key:r.successor_segment_key, successor_segment_order:r.successor_segment_order, final_outcome:r.final_outcome, review_status:r.review_status, reviewer_confidence:r.reviewer_confidence, source_artifact:r.source_artifact, resolution_artifact:r.resolution_artifact, target:{ table:'content_staging.reading_segments', row_identity:{ run_id:r.target.row_identity.run_id, book_id:r.book_id, segment_key:r.successor_segment_key, segment_order:r.successor_segment_order }, target_column:null, target_json_path:null }, expected_current_locator:null, approved_replacement_locator:null, unchanged_locator_fields:['end_locator'], expected_previous_approval_status:'boundary-review', resulting_approval_status:null, ordering_preconditions:[], non_overlap_preconditions:[], reconstruction_preconditions:[], audit_event_identity:null, idempotency_identity:null, rollback_requirements:[], application_ready:false, contract_completeness_status:'incomplete', missing_authority:requiredMissing })
export async function validateArtifacts({contract,plan,evidence,missing,summary,docs}){
 const errors=[]; const d=await deriveLocatorAdjustmentContract(); const expectedById=new Map(d.records.map(r=>[r.decision_id,expectedFor(r)])); const planRecords=plan.records??[]; const planIds=planRecords.map(r=>r.decision_id); const expectedIds=[...expectedById.keys()]
 const planCounts=count(planIds), dupIds=sort([...planCounts].filter(([,c])=>c>1).map(([id])=>id)); const uniqueIds=new Set(planIds); const missingIds=sort(expectedIds.filter(id=>!uniqueIds.has(id))); const extraIds=sort([...uniqueIds].filter(id=>!expectedById.has(id)))
 if (d.readiness.records.length!==144) fail(errors,'wrong public-decision count'); if (d.records.length!==6) fail(errors,'wrong adjust-decision count')
 if (uniqueIds.size!==6) fail(errors,`expected six unique decision IDs, found ${uniqueIds.size}`); if(missingIds.length) fail(errors,`missing decision IDs: ${missingIds.join(', ')}`); if(extraIds.length) fail(errors,`extra decision IDs: ${extraIds.join(', ')}`); if(dupIds.length) fail(errors,`duplicate decision IDs: ${dupIds.join(', ')}`)
 const tupleCounts=count(planRecords.map(r=>`${r.book_id}:${r.successor_segment_key}:${r.successor_segment_order}`)); const dupTuples=sort([...tupleCounts].filter(([,c])=>c>1).map(([t])=>t)); if(dupTuples.length) fail(errors,`duplicate target-row tuples: ${dupTuples.join(', ')}`)
 for (const r of planRecords) { const exp=expectedById.get(r.decision_id); if(!exp) continue; for (const [k,v] of Object.entries(exp)) if(!same(r[k],v)) fail(errors,`${r.decision_id}: ${k} mismatch`) }
 const incompletePlan=planRecords.filter(r=>r.contract_completeness_status==='incomplete'); const missingRecords=missing.records??[]; const missIds=missingRecords.map(r=>r.decision_id); const missCounts=count(missIds); const missUnique=new Set(missIds); const missDup=sort([...missCounts].filter(([,c])=>c>1).map(([id])=>id)); const incompleteIds=new Set(incompletePlan.map(r=>r.decision_id)); const missMissing=sort([...incompleteIds].filter(id=>!missUnique.has(id))); const missExtra=sort([...missUnique].filter(id=>!incompleteIds.has(id)))
 if (missingRecords.length!==6) fail(errors,'missing-authority register must contain six records'); if(missDup.length) fail(errors,`duplicate missing-authority IDs: ${missDup.join(', ')}`); if(missMissing.length) fail(errors,`missing-authority IDs missing: ${missMissing.join(', ')}`); if(missExtra.length) fail(errors,`extra missing-authority IDs: ${missExtra.join(', ')}`)
 for (const mr of missingRecords) { const pr=planRecords.find(r=>r.decision_id===mr.decision_id); if(!pr) continue; if(mr.book_id!==pr.book_id) fail(errors,`${mr.decision_id}: missing-authority book mismatch`); if(mr.packet_id!==pr.packet_id) fail(errors,`${mr.decision_id}: missing-authority packet mismatch`); if(!same(sort(mr.missing_authority??[]),requiredMissingSorted)) fail(errors,`${mr.decision_id}: missing-authority reasons mismatch`); if(pr.contract_completeness_status!=='incomplete') fail(errors,`${mr.decision_id}: plan record is not incomplete`); if(pr.application_ready!==false) fail(errors,`${mr.decision_id}: partial approval claimed`) }
 const expectedHashKeys=sort(Object.keys(inputHashFieldToPath)), actualHashKeys=sort(Object.keys(evidence.input_hashes??{})); if(!same(actualHashKeys,expectedHashKeys)) fail(errors,`input hash key set mismatch; expected ${expectedHashKeys.join(', ')}, found ${actualHashKeys.join(', ')}`)
 for (const [k,p] of Object.entries(inputHashFieldToPath)) { const h=p.endsWith('.sql')?await sha256Raw(p):await canonicalJsonSha256(p); if(evidence.input_hashes?.[k]!==h) fail(errors,`${k}: stale or wrong-artifact hash`) }
 if (evidence.artifact_hashes?.contract_sha256!==canonicalJsonSha256FromValue(contract)) fail(errors,'contract hash mismatch'); if(evidence.artifact_hashes?.plan_sha256!==canonicalJsonSha256FromValue(plan)) fail(errors,'plan hash mismatch'); if(evidence.artifact_hashes?.missing_authority_sha256!==canonicalJsonSha256FromValue(missing)) fail(errors,'missing-authority hash mismatch')
 if(!same(evidence.outcome_distribution,expectedOutcomeDistribution)) fail(errors,'outcome distribution mismatch'); if(!same(evidence.totals,{public_decision_count:144,adjust_successor_start_decisions:6,application_ready_locator_decisions:0,complete_contract_records:0,incomplete_contract_records:6})) fail(errors,'evidence totals mismatch')
 if(contract.locator_mutation_contract_approved!==false||plan.locator_mutation_contract_approved!==false||evidence.locator_mutation_contract_approved!==false) fail(errors,'incorrect contract approval'); if(plan.application_ready_locator_decisions!==0||contract.result?.application_ready_locator_decisions!==0) fail(errors,'application-ready count must be zero'); if(plan.complete_contract_records!==0||contract.result?.complete_contract_records!==0) fail(errors,'complete count must be zero'); if(plan.incomplete_contract_records!==6||contract.result?.incomplete_contract_records!==6) fail(errors,'incomplete count must be six')
 if(contract.authorized_mutation!==null) fail(errors,'authorized_mutation must be null'); if(contract.target_contract?.target_locator_column!=='not approved; repository does not provide approved successor locator values') fail(errors,'target locator column must remain not approved'); if(contract.target_contract?.target_json_path!=='not approved') fail(errors,'target JSON path must remain not approved'); if(!same(contract.preconditions,[])||!same(contract.postconditions,[])) fail(errors,'contract pre/postconditions must be empty'); if(contract.idempotency?.approved!==false) fail(errors,'idempotency must not be approved'); if(contract.rollback?.approved!==false) fail(errors,'rollback must not be approved'); if(contract.rights_status!=='credited-source-edition') fail(errors,'rights status mismatch')
 for (const [k,v] of Object.entries(safetyAssertions)) if (evidence.assertions?.[k]!==v || contract.safety_assertions?.[k]!==v) fail(errors,`${k}: safety assertion must be false`)
 for (const text of [JSON.stringify(contract),JSON.stringify(plan),JSON.stringify(evidence),JSON.stringify(missing),summary,docs]) { if(forbiddenSql.test(text)) fail(errors,'mutating SQL or database/Supabase connection code detected'); if(leakageKeys.test(text)) fail(errors,'structured leakage/applied-state flag detected') }
 if (errors.length) throw new Error(errors.join('\n'))
 return { decision_count:6, approved:false, exact_set_equality:true, incomplete:6, outcome_distribution:expectedOutcomeDistribution }
}
if (import.meta.url===`file://${process.argv[1]}`) { const a={contract:await readJson(paths.contract),plan:await readJson(paths.plan),evidence:await readJson(paths.evidence),missing:await readJson(paths.missingAuthority),summary:await readFile(paths.summary,'utf8'),docs:await readFile(paths.docs,'utf8')}; console.log(JSON.stringify(await validateArtifacts(a),null,2)) }
