import {createHash} from 'node:crypto'
import {readFile} from 'node:fs/promises'
import {canonicalJsonSha256,canonicalJsonSha256FromValue} from './hash_utils.mjs'
import {sources,names,paths,packageId,packageVersion} from './reviewed_boundary_application_rollback_constants.mjs'
const json=async p=>JSON.parse(await readFile(p,'utf8'))
const textHash=async p=>createHash('sha256').update((await readFile(p,'utf8')).replace(/\r\n?/g,'\n')).digest('hex')
const key=x=>{const fields=[['package_id',x.package_id],['event_action',x.event_action],['run_id',x.run_id],['decision_id',x.decision_id],['book_id',String(x.book_id)],['segment_key',x.segment_key],['event_version',String(x.event_version)]];return createHash('sha256').update('sha256-v1-length-delimited-reviewed-boundary-event-key'+fields.map(([k,v])=>`|${k}=${String(v).length}:${v}`).join('')).digest('hex')}
const assert=(v,m)=>{if(!v)throw Error(m)}
export async function validate(){
 const [plan,targets,identity,snapshot,rollbackBase,authority,integrityManifest,manifest,...artifacts]=await Promise.all([sources.application_plan,sources.integrity_targets,sources.audit_identity_contract,sources.integrity_snapshot,sources.rollback_baseline,sources.execution_authority_manifest,sources.integrity_manifest,paths.manifest,...names.map(n=>paths[n])].map(json))
 assert(plan.authorized_decision_count===74&&plan.application_records.length===74,'authorized count');assert(targets.target_count===74&&targets.records.length===74,'target count')
 const ids=plan.application_records.map(x=>x.decision_id), tuples=plan.application_records.map(x=>`${x.expected_run_id}:${x.book_id}:${x.segment_key}`);assert(new Set(ids).size===74,'duplicate decision');assert(new Set(tuples).size===74,'duplicate target')
 for(const r of plan.application_records)assert(r.changed_columns.length===1&&r.changed_columns[0]==='approval_status'&&r.expected_current_approval_status==='boundary-review'&&r.authorized_replacement_approval_status==='content-review'&&r.application_ready&&!/merge/.test(r.final_outcome),'unauthorized authority record')
 const p=new Map(plan.application_records.map(x=>[x.decision_id,x]));for(const t of targets.records){const r=p.get(t.decision_id);assert(r&&r.expected_run_id===t.run_id&&r.book_id===t.book_id&&r.segment_key===t.segment_key&&r.segment_order===t.segment_order,'integrity target mismatch')}
 const by=Object.fromEntries(names.map((n,i)=>[n,artifacts[i]])), apps=by.applicationOperations.operations, rolls=by.rollbackOperations.operations
 assert(apps.length===74&&rolls.length===74,'operation count');assert(JSON.stringify([...apps].sort((a,b)=>a.run_id.localeCompare(b.run_id)||a.book_id-b.book_id||a.segment_order-b.segment_order||a.segment_key.localeCompare(b.segment_key)))===JSON.stringify(apps),'application ordering')
 assert(new Set(apps.map(x=>x.decision_id)).size===74&&new Set(apps.map(x=>x.event_key)).size===74&&new Set(rolls.map(x=>x.rollback_event_key)).size===74,'operation/event uniqueness')
 for(let i=0;i<74;i++){const a=apps[i],r=rolls[i],t=targets.records.find(x=>x.decision_id===a.decision_id);assert(a.event_key===key(a)&&r.rollback_event_key===key({...a,event_action:'status-rollback'}),'event key');assert(a.event_key!==r.rollback_event_key,'action key distinction');assert(r.decision_id===a.decision_id&&r.application_event_key===a.event_key&&r.original_approval_status===a.previous_approval_status&&r.expected_applied_approval_status===a.intended_approval_status,'rollback symmetry');assert(a.expected_identity_sha256===t.identity_sha256&&a.expected_boundary_sha256===t.boundary_sha256&&a.expected_content_sha256===t.content_sha256,'integrity reference');assert(a.permitted_mutation_columns.join()==='approval_status'&&r.permitted_mutation_columns.join()==='approval_status','mutation columns');assert(!JSON.stringify(a).includes('"content":'),'content leakage')}
 assert(identity.event_key_algorithm==='sha256-v1-length-delimited-reviewed-boundary-event-key','audit identity');assert(snapshot.snapshot_complete===false&&rollbackBase.rollback_execution_authorized===false&&authority.execution_authority_approved===false&&integrityManifest.content_integrity_authority_approved===false,'upstream authority unexpectedly true')
 assert(by.stateMachine.current_state==='PACKAGE_BLOCKED'&&by.stateMachine.states.length===16,'state machine');assert(by.transaction.atomicity.includes('all-or-nothing')&&by.transaction.lock_strategy.includes('pg_advisory_xact_lock')&&by.transaction.templates_are_non_executable,'transaction guards');assert(by.preflight.normalization_algorithm==='reviewed-boundary-content-normalization-v1'&&Object.keys(by.preflight.classifications).length===16,'preflight');assert(by.postflight.before_commit&&by.postflight.failure.includes('abort whole'),'postflight');assert(by.idempotency.exact_retry.includes('no mutation'),'idempotency')
 assert(by.gate.application_execution_authorized===false&&by.gate.rollback_execution_authorized===false&&by.policy.default_execution_mode==='blocked','execution gate');assert(by.runtimeEvidence.path.startsWith('tmp/')&&!by.runtimeEvidence.committed_passing_evidence,'runtime evidence');assert(!JSON.stringify(by).match(/postgres(?:ql)?:\/\/|supabase\.co|service_role|anon_key/i),'remote credential/connection')
 assert(manifest.package_id===packageId&&manifest.package_version===packageVersion&&!manifest.application_execution_authorized&&!manifest.rollback_execution_authorized,'manifest authority')
 for(const [n,pth] of Object.entries(sources)){const actual=pth.endsWith('.json')?await canonicalJsonSha256(pth):await textHash(pth);assert(manifest.source_hashes[n]===actual,`stale source hash ${n}`)}
 for(const n of names)assert(manifest.artifact_hashes[`${n}_sha256`]===canonicalJsonSha256FromValue(by[n]),`stale artifact hash ${n}`)
 assert(by.readiness.source_snapshot_complete===false&&by.readiness.source_snapshot_verified===false&&!by.readiness.application_preflight_ready&&!by.readiness.rollback_baseline_ready,'readiness must fail closed')
 return {valid:true,authorized_decisions:74,application_operations:74,rollback_operations:74,duplicate_targets:0,application_execution_authorized:false,rollback_execution_authorized:false}
}
if(import.meta.url===`file://${process.argv[1]}`)console.log(JSON.stringify(await validate(),null,2))
