import { readFile } from 'node:fs/promises'
import { canonicalJsonSha256, canonicalJsonSha256FromValue, sha256Raw } from './hash_utils.mjs'
import { deriveStructuralHeadingMergeContract, paths, safetyAssertions } from './build_source_review_structural_heading_merge_contract.mjs'
const readJson=async p=>JSON.parse(await readFile(p,'utf8'))
const fail=(e,m)=>e.push(m); const sort=v=>[...v].sort((a,b)=>String(a).localeCompare(String(b))); const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b)
const count=a=>a.reduce((m,x)=>(m.set(x,(m.get(x)??0)+1),m),new Map())
const forbidden=/\b(update\s+|insert\s+into|delete\s+from|merge\s+into|truncate|alter\s+|drop\s+|create\s+function|do\s+\$|begin;|commit;|rollback;|psql|createClient|supabase\.co|service_role|postgres:)\b/i
const leakage=/"(?:source_text|source_excerpt|private_evidence|database_change_applied|migration_applied|database_modified|supabase_modified|production_modified|cutover_enabled)"\s*:\s*(?:"[^"]+"|true)/i
export const inputHashFieldToPath={ immutable_historical_progress_sha256:paths.historicalProgress, archived_pr0045_pr0046_progress_snapshot_sha256:paths.pr0045Current, current_cumulative_progress_sha256:paths.progress, pr0048_readiness_policy_sha256:paths.readinessPolicy, pr0048_readiness_plan_sha256:paths.readinessPlan, pr0049_status_only_contract_sha256:paths.statusOnlyContract, pr0049_status_only_plan_sha256:paths.statusOnlyPlan, pr0050_locator_contract_sha256:paths.locatorContract, pr0050_locator_plan_sha256:paths.locatorPlan, pr0050_locator_evidence_sha256:paths.locatorEvidence, pr0050_locator_missing_authority_sha256:paths.locatorMissingAuthority, staging_schema_sha256:paths.stagingSchema, source_inspection_packets_sha256:paths.sourceInspectionPackets, mechanical_application_policy_sha256:paths.mechanicalPolicy, mechanical_application_plan_sha256:paths.mechanicalPlan, mechanical_application_evidence_sha256:paths.mechanicalEvidence, reconstruction_authority_sha256:paths.reconstructionPlan, editorial_node_authority_sha256:paths.editorialNodePlan, reader_reference_authority_sha256:paths.readerReferenceAuthority, ...Object.fromEntries(paths.decisionInputs.map(p=>[`${p.split('/').at(-1).replace('.json','').replaceAll('-','_')}_sha256`,p])), recovery_consolidation_sha256:paths.recoveryConsolidation, book_3_manual_adjudication_sha256:paths.book3Manual, remaining_manual_adjudication_sha256:paths.remainingManual }
const expectedOutcome={'adjust-successor-start':6,'confirm-successor-start':73,'exclude-structural-heading':53,'retain-intro-segment':1,unresolved:11}
export async function validateArtifacts({contract,plan,evidence,missing,operationModels,summary,docs}){
 const errors=[]; const d=await deriveStructuralHeadingMergeContract(); const expected=new Map(d.records.map(r=>[r.decision_id,r])); const records=plan.records??[]; const ids=records.map(r=>r.decision_id); const idsSet=new Set(ids)
 if(d.readiness.records.length!==144) fail(errors,'wrong public-decision count'); if(d.records.length!==53) fail(errors,'wrong merge-decision count')
 const dupIds=sort([...count(ids)].filter(([,c])=>c>1).map(([id])=>id)); if(dupIds.length) fail(errors,`duplicate decision IDs: ${dupIds.join(', ')}`)
 const missingIds=sort([...expected.keys()].filter(id=>!idsSet.has(id))); const extraIds=sort([...idsSet].filter(id=>!expected.has(id))); if(missingIds.length) fail(errors,`missing decisions: ${missingIds.join(', ')}`); if(extraIds.length) fail(errors,`extra decisions: ${extraIds.join(', ')}`)
 const headingDup=sort([...count(records.map(r=>`${r.book_id}:${r.current_heading_segment_key}:${r.heading_segment_order}`))].filter(([,c])=>c>1).map(([t])=>t)); if(headingDup.length) fail(errors,`duplicate heading targets: ${headingDup.join(', ')}`)
 for(const r of records){ const x=expected.get(r.decision_id); if(!x) continue; for(const k of ['book_id','book_slug','packet_id','current_heading_segment_key','heading_segment_order','predecessor_segment_key','predecessor_segment_order','successor_segment_key','successor_segment_order','final_outcome','review_status','reviewer_confidence','source_artifact','resolution_artifact','heading_row_identity','successor_row_identity','predecessor_row_identity','authorized_operation_type','operation_model','target_tables','changed_fields','unchanged_fields','locator_behavior','segment_order_behavior','segment_key_behavior','editorial_node_behavior','user_progress_remapping_behavior','reader_session_behavior','bookmark_note_highlight_behavior','audit_event_identity','idempotency_identity','rollback_requirements','operation_completeness_status','missing_authority','application_ready']) if(!same(r[k],x[k])) fail(errors,`${r.decision_id}: ${k} mismatch`); if(r.final_outcome!=='exclude-structural-heading') fail(errors,`${r.decision_id}: wrong outcome included`); if(r.operation_completeness_status!=='incomplete'||r.application_ready!==false) fail(errors,`${r.decision_id}: partial approval claimed`); if(!r.heading_row_identity) fail(errors,`${r.decision_id}: missing heading identity`); if(!r.successor_row_identity && !r.missing_authority.includes('successor_segment_key')) fail(errors,`${r.decision_id}: missing successor identity not recorded`) }
 const miss=missing.records??[]; const missIds=new Set(miss.map(r=>r.decision_id)); if(miss.length!==53) fail(errors,'missing-authority register must contain 53 records'); for(const r of records) if(!missIds.has(r.decision_id)) fail(errors,`${r.decision_id}: missing-authority record absent`); for(const m of miss){ const r=records.find(x=>x.decision_id===m.decision_id); if(!r) fail(errors,`${m.decision_id}: extra missing-authority record`); else if(!same(m.missing_authority,r.missing_authority)) fail(errors,`${m.decision_id}: missing-authority drift`) }
 if(!same(evidence.outcome_distribution,expectedOutcome)) fail(errors,'outcome distribution mismatch'); if(!same(evidence.totals,{public_decision_count:144,exclude_structural_heading_decisions:53,application_ready_merge_decisions:0,complete_operation_records:0,incomplete_operation_records:53})) fail(errors,'evidence totals mismatch')
 if(contract.structural_heading_merge_contract_approved!==false||plan.structural_heading_merge_contract_approved!==false||evidence.structural_heading_merge_contract_approved!==false) fail(errors,'incorrect contract approval'); if(contract.authorized_mutation!==null) fail(errors,'authorized mutation must be null'); if(plan.application_ready_merge_decisions!==0||contract.result?.application_ready_merge_decisions!==0) fail(errors,'application-ready count must be zero')
 if((operationModels.supported_operation_models??[]).length!==0) fail(errors,'unsupported model approved'); if((operationModels.rejected_operation_models??[]).length!==5) fail(errors,'expected five rejected operation models')
 const actualKeys=sort(Object.keys(evidence.input_hashes??{})); const expectedKeys=sort(Object.keys(inputHashFieldToPath)); if(!same(actualKeys,expectedKeys)) fail(errors,'input hash key set mismatch')
 for(const [k,p] of Object.entries(inputHashFieldToPath)){ const h=p.endsWith('.sql')||p.endsWith('.ts')?await sha256Raw(p):await canonicalJsonSha256(p); if(evidence.input_hashes?.[k]!==h) fail(errors,`${k}: stale hash`) }
 if(evidence.artifact_hashes?.contract_sha256!==canonicalJsonSha256FromValue(contract)) fail(errors,'contract hash mismatch'); if(evidence.artifact_hashes?.plan_sha256!==canonicalJsonSha256FromValue(plan)) fail(errors,'plan hash mismatch'); if(evidence.artifact_hashes?.missing_authority_sha256!==canonicalJsonSha256FromValue(missing)) fail(errors,'missing hash mismatch'); if(evidence.artifact_hashes?.operation_models_sha256!==canonicalJsonSha256FromValue(operationModels)) fail(errors,'operation-model hash mismatch')
 for(const [k,v] of Object.entries(safetyAssertions)) if(contract.safety_assertions?.[k]!==v||evidence.assertions?.[k]!==v) fail(errors,`${k}: safety assertion mismatch`)
 for(const text of [JSON.stringify(contract),JSON.stringify(plan),JSON.stringify(evidence),JSON.stringify(missing),JSON.stringify(operationModels),summary,docs]){ if(forbidden.test(text)) fail(errors,'mutating SQL or DB/Supabase code detected'); if(leakage.test(text)) fail(errors,'source/private/applied-state leakage detected') }
 if(errors.length) throw new Error(errors.join('\n'))
 return {decision_count:53, approved:false, exact_set_equality:true, incomplete:53, outcome_distribution:expectedOutcome}
}
if(import.meta.url===`file://${process.argv[1]}`){const a={contract:await readJson(paths.contract),plan:await readJson(paths.plan),evidence:await readJson(paths.evidence),missing:await readJson(paths.missingAuthority),operationModels:await readJson(paths.operationModels),summary:await readFile(paths.summary,'utf8'),docs:await readFile(paths.docs,'utf8')}; console.log(JSON.stringify(await validateArtifacts(a),null,2))}
