export const GUIDED_STUDY_VERSION = 1

export const GUIDED_STUDY_PATHS = [
  {
    key: 'livro-dos-espiritos',
    title: 'O Livro dos Espíritos',
    aliases: ['livro dos espíritos', 'livro dos espiritos'],
    subtitle: 'Fundamentos para compreender a visão espírita sobre Deus, o Espírito, a vida e as leis morais.',
    sessions: [
      session('le-01', 'Deus e as causas primeiras', 12, ['Deus', 'causa primeira'],
        'Observe como a obra começa pelas perguntas mais fundamentais antes de avançar para a vida espiritual.',
        'Leia procurando distinguir o que é pergunta, o que é resposta e como os conceitos são construídos em sequência. Não é necessário resolver todas as questões de uma vez.',
        'Que ideia deste trecho muda ou organiza melhor a forma como você entende a origem das coisas?',
        connection('A Gênese', 'ciência, criação e revelação'), ['Deus', 'causas primeiras']),
      session('le-02', 'Espírito e matéria', 12, ['espírito e matéria', 'matéria'],
        'Neste encontro, acompanhe as distinções que a obra estabelece entre princípio espiritual, matéria e vida.',
        'Evite transformar os termos em definições isoladas. Observe como uma resposta prepara a pergunta seguinte e como os conceitos ganham sentido pelo conjunto.',
        'Como você explicaria, com suas próprias palavras, a diferença que o texto apresenta entre Espírito e matéria?',
        connection('A Gênese', 'gênese espiritual'), ['Espírito', 'matéria']),
      session('le-03', 'Origem e natureza dos Espíritos', 12, ['origem dos espíritos', 'espíritos'],
        'A leitura agora passa da existência do princípio espiritual para questões sobre os Espíritos e seu desenvolvimento.',
        'Procure identificar o que o texto afirma diretamente e o que permanece como limite do conhecimento apresentado na própria obra.',
        'Qual pergunta deste encontro você gostaria de continuar investigando em outras partes do livro?',
        connection('O Livro dos Médiuns', 'natureza dos Espíritos e comunicações'), ['Espíritos', 'progresso']),
      session('le-04', 'Encarnação e reencarnação', 14, ['reencarnação', 'encarnação dos espíritos'],
        'Leia esta parte como uma investigação sobre a finalidade e a continuidade da experiência corporal.',
        'Compare as respostas próximas entre si. Em vez de guardar uma frase solta, tente perceber qual raciocínio a sequência de perguntas está construindo.',
        'Que relação você percebe entre experiência, aprendizado e responsabilidade?',
        connection('O Evangelho segundo o Espiritismo', 'renascimento e vida moral'), ['encarnação', 'reencarnação']),
      session('le-05', 'A vida espiritual', 14, ['vida espírita', 'mundo dos espíritos'],
        'Neste encontro, o foco está na vida do Espírito para além da experiência corporal.',
        'Observe especialmente as diferenças de condição, percepção e progresso apresentadas no texto, sem tentar reduzir toda a vida espiritual a uma única imagem.',
        'O que este trecho acrescenta à sua compreensão sobre continuidade da vida?',
        connection('O Céu e o Inferno', 'destino da alma e vida futura'), ['vida espiritual', 'mundo espiritual']),
      session('le-06', 'Livre-arbítrio e responsabilidade', 12, ['livre-arbítrio', 'livre arbítrio'],
        'A proposta é observar como liberdade e responsabilidade aparecem juntas, e não como ideias independentes.',
        'Enquanto lê, marque as condições e limites que o próprio texto associa à liberdade de escolha.',
        'Em que situação do cotidiano a ideia de responsabilidade apresentada aqui pode ser examinada com mais cuidado?',
        connection('O Evangelho segundo o Espiritismo', 'responsabilidade moral e escolhas'), ['livre-arbítrio', 'responsabilidade']),
      session('le-07', 'As leis morais', 14, ['lei divina ou natural', 'leis morais'],
        'Aqui a obra organiza uma parte extensa de seu estudo em torno das leis morais.',
        'Use este encontro para perceber a estrutura geral antes de tentar memorizar categorias. Pergunte a si mesma o que cada lei procura esclarecer sobre a vida em relação aos outros.',
        'Qual dessas ideias parece mais concreta para ser observada na sua vida esta semana?',
        connection('O Evangelho segundo o Espiritismo', 'aplicação moral dos ensinamentos de Jesus'), ['lei natural', 'leis morais']),
      session('le-08', 'Esperanças e consolações', 12, ['esperanças e consolações', 'penas e gozos futuros'],
        'O fechamento da obra reúne questões sobre consequências, futuro e esperança.',
        'Leia observando como responsabilidade e consolação são colocadas lado a lado. Diferencie imagens tradicionais das explicações desenvolvidas pelo próprio texto.',
        'Depois deste percurso, que conceito você sente que merece uma segunda leitura?',
        connection('O Céu e o Inferno', 'justiça divina, futuro e consolação'), ['esperança', 'vida futura']),
    ],
  },
  {
    key: 'livro-dos-mediuns',
    title: 'O Livro dos Médiuns',
    aliases: ['livro dos médiuns', 'livro dos mediuns'],
    subtitle: 'Um percurso de estudo sobre mediunidade, comunicações, discernimento e responsabilidade.',
    sessions: [
      session('lm-01', 'Por que estudar os fenômenos?', 12, ['há espíritos', 'manifestações espíritas'],
        'Comece observando o método: antes de falar de prática mediúnica, a obra discute premissas, objeções e critérios de exame.',
        'Procure identificar quais argumentos são apresentados e quais perguntas o autor considera necessárias antes de avançar.',
        'Que diferença você percebe entre curiosidade sobre fenômenos e estudo sistemático?',
        connection('O Livro dos Espíritos', 'natureza dos Espíritos'), ['fenômenos', 'método']),
      session('lm-02', 'O que é mediunidade?', 12, ['médiuns', 'mediunidade'],
        'Neste encontro, acompanhe como a obra delimita o fenômeno mediúnico e a variedade de suas manifestações.',
        'Não tente decorar classificações. Primeiro identifique a ideia central e depois observe como os exemplos ajudam a diferenciá-la.',
        'Como você explicaria o propósito do estudo da mediunidade a alguém que nunca leu a obra?',
        connection('O Livro dos Espíritos', 'relações entre o mundo corporal e espiritual'), ['mediunidade', 'comunicação']),
      session('lm-03', 'Diferentes formas de mediunidade', 14, ['médiuns especiais', 'médiuns sensitivos'],
        'A obra apresenta diferentes formas de percepção e comunicação. O objetivo deste encontro é reconhecer diversidade sem transformar classificações em rótulos rígidos.',
        'Compare as descrições e repare nos critérios usados para distingui-las. O foco é compreender, não classificar pessoas.',
        'Qual distinção desta leitura ajudou você a evitar uma simplificação sobre mediunidade?',
        connection('A Gênese', 'fluidos e fenômenos'), ['faculdades mediúnicas', 'diversidade']),
      session('lm-04', 'O papel do médium', 12, ['influência moral do médium', 'médium'],
        'Agora o foco passa do fenômeno para a participação humana no processo.',
        'Observe como condições pessoais, intenção e responsabilidade são discutidas. Separe capacidade mediúnica de valor moral sempre que o próprio texto fizer essa distinção.',
        'Que responsabilidade aparece como mais importante para quem participa de uma prática mediúnica?',
        connection('O Evangelho segundo o Espiritismo', 'vigilância e transformação moral'), ['médium', 'responsabilidade']),
      session('lm-05', 'Influência moral e discernimento', 14, ['influência moral', 'bons e maus espíritos'],
        'Este encontro trata da necessidade de discernimento diante das comunicações.',
        'Procure os critérios apresentados pelo texto para avaliar conteúdo e influência. Evite tomar uma comunicação como verdadeira apenas por sua forma ou origem alegada.',
        'Que critério de discernimento você gostaria de lembrar antes de aceitar uma afirmação espiritual?',
        connection('O Livro dos Espíritos', 'escala e diversidade dos Espíritos'), ['discernimento', 'influência moral']),
      session('lm-06', 'Identidade e conteúdo das comunicações', 14, ['identidade dos espíritos', 'evocações'],
        'A questão agora é como examinar identidade, linguagem e conteúdo das comunicações.',
        'Observe as cautelas metodológicas. Dê mais peso aos critérios que o próprio texto recomenda do que à impressão produzida por nomes, estilos ou afirmações de autoridade.',
        'O que torna uma comunicação digna de exame cuidadoso, segundo o que você acabou de ler?',
        connection('O Céu e o Inferno', 'comunicações e relatos da vida espiritual'), ['identidade', 'comunicações']),
      session('lm-07', 'Obsessão e prudência', 14, ['obsessão', 'perigos da mediunidade'],
        'Leia esta etapa com atenção especial à prudência, aos sinais de influência persistente e às orientações preventivas da obra.',
        'Evite transformar o tema em medo. O exercício é reconhecer critérios, limites e medidas de cuidado tal como aparecem na fonte.',
        'Qual atitude de prudência deste trecho parece mais aplicável ao estudo responsável da mediunidade?',
        connection('O Evangelho segundo o Espiritismo', 'prece, vigilância e caridade'), ['obsessão', 'prudência']),
      session('lm-08', 'Método, prática e responsabilidade', 12, ['sociedades espíritas', 'reuniões espíritas'],
        'No fechamento, observe como estudo, método, convivência e finalidade moral se conectam.',
        'Releia o percurso pensando menos em fenômenos isolados e mais nas condições que a obra considera necessárias para uma prática séria.',
        'Que princípio você levaria para qualquer grupo de estudo ou prática mediúnica?',
        connection('O Evangelho segundo o Espiritismo', 'caridade e vida em comunidade'), ['método', 'responsabilidade']),
    ],
  },
  {
    key: 'evangelho-segundo-espiritismo',
    title: 'O Evangelho segundo o Espiritismo',
    aliases: ['evangelho segundo o espiritismo', 'o evangelho segundo o espiritismo'],
    subtitle: 'Uma leitura guiada dos ensinamentos morais do Evangelho sob a perspectiva espírita.',
    sessions: [
      session('ese-01', 'Por que um estudo moral do Evangelho?', 12, ['não vim destruir a lei', 'lei'],
        'Comece percebendo o recorte da obra: o foco está nos ensinamentos morais e em sua aplicação.',
        'Observe como os capítulos aproximam texto evangélico, explicação e instruções. Mantenha essas camadas distintas durante a leitura.',
        'O que significa, para você, estudar um ensinamento moral em vez de apenas conhecê-lo?',
        connection('O Livro dos Espíritos', 'leis morais'), ['Evangelho', 'vida moral']),
      session('ese-02', 'Bem-aventuranças e consolação', 12, ['bem-aventurados', 'aflitos'],
        'Neste encontro, leia as bem-aventuranças como ponto de partida para compreender sofrimento, esperança e transformação.',
        'Repare como a obra relaciona os ensinamentos evangélicos a uma perspectiva mais ampla da existência, sem perder de vista a experiência humana concreta.',
        'Qual expressão deste trecho oferece uma nova maneira de olhar uma dificuldade?',
        connection('O Céu e o Inferno', 'consolação e futuro da alma'), ['bem-aventuranças', 'consolação']),
      session('ese-03', 'Caridade como prática', 14, ['fora da caridade não há salvação', 'caridade'],
        'A proposta é examinar caridade como atitude concreta, não apenas como ideia abstrata.',
        'Observe os exemplos, contrastes e consequências morais apresentados. Pergunte como o princípio se traduz em relação com outras pessoas.',
        'Que forma de caridade, além da ajuda material, aparece com mais força para você nesta leitura?',
        connection('O Livro dos Espíritos', 'lei de justiça, amor e caridade'), ['caridade', 'amor ao próximo']),
      session('ese-04', 'Perdão e reconciliação', 12, ['perdoai', 'reconciliai-vos'],
        'Leia procurando distinguir perdão, reconciliação e responsabilidade.',
        'Não procure uma regra automática para situações pessoais complexas. Observe o princípio moral da fonte e reflita sobre sua aplicação com prudência.',
        'O que esta leitura sugere sobre a diferença entre perdoar e ignorar uma responsabilidade?',
        connection('O Livro dos Espíritos', 'responsabilidade e relações humanas'), ['perdão', 'reconciliação']),
      session('ese-05', 'Família e vínculos espirituais', 12, ['laços de família', 'parentesco corporal'],
        'Neste encontro, acompanhe como a obra amplia a discussão sobre família para além dos vínculos corporais.',
        'Compare cuidadosamente o que o texto diz sobre afeto, dever e continuidade dos vínculos. Evite generalizar uma passagem para toda situação familiar.',
        'Que responsabilidade nos vínculos familiares fica mais clara depois desta leitura?',
        connection('O Livro dos Espíritos', 'família, reencarnação e simpatias'), ['família', 'vínculos']),
      session('ese-06', 'Prece e intenção', 12, ['pedi e obtereis', 'prece'],
        'A leitura agora convida a observar finalidade, intenção e efeitos da prece.',
        'Preste atenção à diferença entre pedir resultados específicos e cultivar disposição interior. Deixe a própria fonte definir seus limites e possibilidades.',
        'Depois de ler, como você descreveria a finalidade da prece com suas próprias palavras?',
        connection('O Livro dos Médiuns', 'recolhimento, influência e vigilância'), ['prece', 'intenção']),
      session('ese-07', 'Justiça, misericórdia e julgamento', 14, ['não julgueis', 'misericórdia'],
        'Este encontro reúne princípios sobre julgamento, indulgência e misericórdia nas relações.',
        'Procure os limites e nuances do texto. A ideia não é abolir discernimento, mas examinar a postura moral com que avaliamos pessoas e situações.',
        'Que hábito de julgamento esta leitura convida você a observar em si mesma?',
        connection('O Céu e o Inferno', 'justiça e responsabilidade'), ['misericórdia', 'indulgência']),
      session('ese-08', 'Levar o estudo para a vida', 12, ['sede perfeitos', 'homem de bem'],
        'No fechamento, a pergunta é prática: como transformar leitura em observação de si e ação cotidiana?',
        'Releia os critérios morais apresentados sem buscar perfeição instantânea. Escolha uma ideia pequena o bastante para ser praticada e observada.',
        'Qual atitude concreta você quer experimentar antes de voltar a este estudo?',
        connection('O Livro dos Espíritos', 'aperfeiçoamento moral e progresso'), ['prática', 'transformação moral']),
    ],
  },
  {
    key: 'ceu-e-inferno',
    title: 'O Céu e o Inferno',
    aliases: ['céu e o inferno', 'ceu e o inferno', 'o céu e o inferno', 'o ceu e o inferno'],
    subtitle: 'Um estudo sobre justiça divina, morte, vida futura, responsabilidade e diferentes condições espirituais.',
    sessions: [
      session('ci-01', 'Justiça divina e vida futura', 12, ['justiça divina', 'vida futura'],
        'Comece observando a pergunta central da obra: como compreender justiça, consequências e destino da alma?',
        'Diferencie os argumentos da primeira parte dos relatos e exemplos posteriores. Nesta etapa, concentre-se na estrutura das ideias.',
        'Que pergunta sobre justiça e vida futura você traz para esta leitura?',
        connection('O Livro dos Espíritos', 'penas e gozos futuros'), ['justiça divina', 'vida futura']),
      session('ci-02', 'Céu, inferno e purgatório', 14, ['céu', 'purgatório'],
        'Este encontro examina conceitos tradicionais e a forma como a obra os discute.',
        'Observe quais imagens são questionadas, quais argumentos são apresentados e como a ideia de condição espiritual é construída.',
        'Qual diferença entre lugar e estado/condição parece importante nesta leitura?',
        connection('O Livro dos Espíritos', 'estado dos Espíritos após a morte'), ['céu', 'inferno', 'purgatório']),
      session('ci-03', 'Por que tememos a morte?', 12, ['temor da morte', 'morte'],
        'A leitura agora se aproxima de uma experiência humana concreta: o medo da morte.',
        'Procure as causas que o texto apresenta e compare-as com suas próprias perguntas, sem transformar o estudo em uma obrigação de sentir de determinada forma.',
        'Que aspecto do medo da morte fica mais compreensível depois deste trecho?',
        connection('O Evangelho segundo o Espiritismo', 'consolação diante das aflições'), ['morte', 'temor', 'consolação']),
      session('ci-04', 'Consequências e responsabilidade', 14, ['penas futuras', 'código penal da vida futura'],
        'Neste encontro, examine como a obra relaciona consequências futuras, consciência e responsabilidade.',
        'Evite ler apenas em termos de punição externa. Observe cuidadosamente os princípios e relações de causa e consequência formulados no texto.',
        'Como a noção de responsabilidade apresentada aqui se relaciona com suas escolhas presentes?',
        connection('O Livro dos Espíritos', 'livre-arbítrio e responsabilidade'), ['consequências', 'responsabilidade']),
      session('ci-05', 'A passagem para a vida espiritual', 12, ['passagem', 'separação da alma'],
        'O foco agora é a transição da experiência corporal para a espiritual.',
        'Leia os trechos como parte de uma investigação da obra sobre percepções e condições após a morte. Diferencie princípios gerais de exemplos particulares.',
        'Qual ideia deste encontro você gostaria de comparar com O Livro dos Espíritos?',
        connection('O Livro dos Espíritos', 'retorno à vida espiritual'), ['desencarnação', 'vida espiritual']),
      session('ci-06', 'Aprender com relatos sem generalizar', 14, ['espíritos felizes', 'espíritos em condições medianas'],
        'A segunda parte reúne comunicações e exemplos. Use-os como casos apresentados pela obra, não como fórmulas universais.',
        'Pergunte em cada relato: qual princípio ele pretende ilustrar? Evite concluir que todos os Espíritos ou todas as mortes seguem exatamente o mesmo roteiro.',
        'Que princípio, e não apenas detalhe do relato, ficou mais evidente para você?',
        connection('O Livro dos Médiuns', 'critério e exame das comunicações'), ['relatos', 'discernimento']),
      session('ci-07', 'Consciência e transformação', 12, ['espíritos sofredores', 'arrependimento'],
        'Neste encontro, observe como consciência, arrependimento e mudança aparecem nos casos estudados.',
        'Compare diferentes relatos procurando elementos recorrentes e diferenças individuais. Mantenha o foco no princípio moral que a obra procura evidenciar.',
        'O que esta leitura sugere sobre a possibilidade de transformação?',
        connection('O Evangelho segundo o Espiritismo', 'arrependimento, perdão e transformação'), ['consciência', 'arrependimento']),
      session('ci-08', 'Consolação, responsabilidade e esperança', 12, ['esperança', 'expiações terrestres'],
        'Feche o percurso reunindo três fios da obra: responsabilidade, diversidade de condições e possibilidade de progresso.',
        'Revisite uma passagem anterior que tenha mudado sua compreensão. O objetivo não é encerrar o tema, mas identificar o que merece aprofundamento.',
        'Qual ideia desta obra oferece mais esperança sem eliminar a responsabilidade pessoal?',
        connection('O Livro dos Espíritos', 'esperanças e consolações'), ['esperança', 'progresso']),
    ],
  },
  {
    key: 'a-genese',
    title: 'A Gênese',
    aliases: ['a gênese', 'a genese', 'gênese', 'genese'],
    subtitle: 'Um percurso por ciência, criação, gênese espiritual, fluidos, milagres, predições e progresso.',
    sessions: [
      session('ag-01', 'Ciência e revelação', 14, ['caráter da revelação espírita', 'revelação espírita'],
        'Comece observando como a obra apresenta a relação entre investigação, conhecimento e revelação.',
        'Procure os limites que o próprio texto estabelece. Repare onde argumenta, onde interpreta e onde deixa espaço para avanço do conhecimento.',
        'Que critério desta leitura ajuda você a pensar a relação entre fé e investigação?',
        connection('O Livro dos Espíritos', 'causas primeiras e limites do conhecimento'), ['ciência', 'revelação']),
      session('ag-02', 'Deus e criação', 12, ['Deus', 'criação'],
        'Neste encontro, acompanhe a passagem das questões de método para as perguntas sobre Deus, criação e leis naturais.',
        'Leia em sequência para perceber o raciocínio, evitando retirar frases do contexto argumentativo em que aparecem.',
        'Que pergunta sobre criação ficou mais bem formulada depois desta leitura?',
        connection('O Livro dos Espíritos', 'Deus e elementos gerais do universo'), ['Deus', 'criação']),
      session('ag-03', 'Gênese orgânica e transformação', 14, ['gênese orgânica', 'formação dos seres vivos'],
        'A obra dialoga com conhecimentos científicos de sua época. Leia esta parte distinguindo princípio doutrinário, explicação histórica e conhecimento científico revisável.',
        'Quando encontrar uma afirmação científica, trate-a no contexto histórico da publicação e não como substituto da ciência contemporânea.',
        'O que muda na sua leitura quando você separa conteúdo histórico-científico de princípios espirituais?',
        connection('O Livro dos Espíritos', 'formação dos seres vivos'), ['gênese orgânica', 'contexto histórico']),
      session('ag-04', 'Gênese espiritual', 14, ['gênese espiritual', 'princípio espiritual'],
        'Agora o foco é a dimensão espiritual da gênese e sua relação com a experiência corporal.',
        'Observe conceitos recorrentes e compare-os com os fundamentos de O Livro dos Espíritos. Use a conexão entre obras para esclarecer termos, não para misturar passagens.',
        'Qual conceito desta etapa ficou mais claro quando comparado com outra obra?',
        connection('O Livro dos Espíritos', 'Espírito, matéria e encarnação'), ['gênese espiritual', 'princípio espiritual']),
      session('ag-05', 'O que a obra chama de milagres?', 12, ['milagres', 'caracteres dos milagres'],
        'Este encontro examina a forma como a obra discute acontecimentos chamados de milagrosos.',
        'Procure a definição operacional usada pelo texto e acompanhe como fenômenos são relacionados a leis naturais, sem antecipar conclusões antes de ler o argumento completo.',
        'Como você explicaria a diferença entre desconhecer uma causa e afirmar que não existe causa natural?',
        connection('O Livro dos Médiuns', 'fenômenos e investigação'), ['milagres', 'leis naturais']),
      session('ag-06', 'Fluidos e fenômenos', 14, ['fluidos', 'natureza e propriedades dos fluidos'],
        'A leitura aborda uma linguagem e conceitos próprios do contexto da obra. O objetivo é compreender como são usados no sistema explicativo apresentado.',
        'Evite equiparar automaticamente termos históricos a conceitos científicos atuais. Observe função, relação e limites dentro do próprio texto.',
        'Que cuidado de linguagem você considera importante ao conversar sobre este tema hoje?',
        connection('O Livro dos Médiuns', 'fenômenos mediúnicos e condições de manifestação'), ['fluidos', 'fenômenos']),
      session('ag-07', 'Predições e leitura responsável', 12, ['predições', 'teoria da presciência'],
        'Neste encontro, examine o que a obra entende por predição e quais limites apresenta para interpretar conhecimento do futuro.',
        'Leia procurando critérios e cautelas. Evite transformar imagens, previsões ou hipóteses em calendários ou certezas que o texto não estabelece.',
        'Que limite desta leitura parece essencial para interpretar predições com prudência?',
        connection('O Livro dos Médiuns', 'discernimento diante de comunicações'), ['predições', 'prudência']),
      session('ag-08', 'Sinais dos tempos e progresso', 14, ['sinais dos tempos', 'geração nova'],
        'No fechamento, acompanhe como a obra relaciona transformação coletiva, progresso e responsabilidade humana.',
        'Evite buscar datas ou acontecimentos específicos onde a fonte trabalha com processos. Compare o final com os princípios morais estudados nas outras obras.',
        'Que responsabilidade individual aparece quando pensamos em progresso coletivo?',
        connection('O Evangelho segundo o Espiritismo', 'transformação moral na vida cotidiana'), ['progresso', 'transformação coletiva']),
    ],
  },
]

function session(id, title, minutes, sourceTerms, beforeReading, understand, reflectionPrompt, crossConnection, concepts) {
  return {
    id,
    title,
    minutes,
    sourceTerms,
    beforeReading,
    understand,
    reflectionPrompt,
    connection: crossConnection,
    concepts,
  }
}

function connection(work, theme) {
  return { work, theme }
}

export function normalizeGuidedTitle(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

export function matchGuidedPath(book) {
  if (!book) return null
  const title = normalizeGuidedTitle(book.title)
  return GUIDED_STUDY_PATHS.find((path) =>
    path.aliases.some((alias) => title.includes(normalizeGuidedTitle(alias)))
  ) || null
}

export function getGuidedPath(pathKey) {
  return GUIDED_STUDY_PATHS.find((path) => path.key === pathKey) || null
}

export function getGuidedSession(pathKey, sessionId) {
  return getGuidedPath(pathKey)?.sessions.find((sessionItem) => sessionItem.id === sessionId) || null
}

export function getNextGuidedSession(pathKey, sessionId) {
  const path = getGuidedPath(pathKey)
  if (!path) return null
  const index = path.sessions.findIndex((sessionItem) => sessionItem.id === sessionId)
  return index >= 0 ? path.sessions[index + 1] || null : null
}
