import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const home = readFileSync('src/pages/HomePage.jsx', 'utf8')
const library = readFileSync('src/pages/LibraryPage.jsx', 'utf8')
const reader = readFileSync('src/pages/ReaderPage.jsx', 'utf8')
const reflection = readFileSync('src/pages/ReflectionPage.jsx', 'utf8')
const favorites = readFileSync('src/pages/FavoritesPage.jsx', 'utf8')
const community = readFileSync('src/pages/CommunityPage.jsx', 'utf8')
const bottomNav = readFileSync('src/components/ui/BottomNav.jsx', 'utf8')

describe('Vereda North Star canonical screens', () => {
  it('keeps Home focused on a personalized next action without duplicating progress', () => {
    expect(home).toContain('Continue seu caminho de estudo espírita.')
    expect(home).toContain('getGreeting(profile?.name)')
    expect(home).toContain('A maior caridade que podemos fazer pela Doutrina Espírita é a sua divulgação.')
    expect(home).toContain('Continuar estudando')
    expect(home).toContain('O que você quer fazer agora?')
    expect(home).toContain('Livros')
    expect(home).toContain('Reflexões')
    expect(home).toContain('Resumos')
    expect(home).toContain('Audiobooks')
    expect(home).not.toContain('Plano de estudo')
    expect(home).not.toContain('Estudo Sistematizado')
    expect(home).not.toContain('Comunidade Vereda')
  })

  it('keeps Biblioteca focused on one connected five-work journey with progress', () => {
    expect(library).toContain('Biblioteca')
    expect(library).toContain('Básicas')
    expect(library).toContain('Complementares')
    expect(library).toContain('aria-labelledby="all-books-heading"')
    expect(library).toContain('BOOK_ACCENT_COLORS')
    expect(library).toContain('showMenu &&')
    expect(library).toContain('Uma jornada pelas obras básicas')
    expect(library).toContain('Caminho sugerido pelas obras básicas')
    expect(library).toContain('Seu progresso')
    expect(library).not.toContain('Caminho sugerido · opcional')
    expect(library).not.toContain('Etapa {sequence} de {totalBooks}')
    expect(library).toContain('Trechos salvos')
    expect(library).toContain('Sugerir uma obra')
    expect(library).toContain('Sugerir uma obra complementar')
    expect(library).toContain("navigate('/sugerir-obra')")
  })

  it('keeps Reader hierarchy explicit while making navigation controls quieter', () => {
    expect(reader).toContain('MoreHorizontal')
    expect(reader).toContain("[currentSection.part_title, currentSection.chapter_label]")
    expect(reader).toContain('Nesta parte')
    expect(reader).toContain('extractChapterOverview')
    expect(reader).toContain('grid-cols-[2.75rem_1fr_2.75rem]')
    expect(reader).toContain('justify-self-start disabled:opacity-25')
    expect(reader).toContain('justify-self-end disabled:opacity-35')
    expect(reader).toContain('className="northstar-reader-control"')
    expect(reader).toContain('A−')
    expect(reader).toContain('A+')
    expect(reader).toContain('Salvar este trecho')
    expect(reader).toContain('BookIndexPanel')
    expect(reader).not.toContain('> Anterior')
  })

  it('makes personal reflection saving explicit and removes ambiguous actions', () => {
    expect(reflection).toContain('Reflexão do dia')
    expect(reflection).toContain('Ninguém está bastante adiantado na vida para não aprender, nem tão simples e ignorante que não possa ensinar alguma coisa.')
    expect(reflection).toContain('Emmanuel')
    expect(reflection).toContain('Minha reflexão')
    expect(reflection).toContain('Escreva sua reflexão...')
    expect(reflection).toContain('Salvar minha reflexão')
    expect(reflection).toContain('Minhas reflexões salvas')
    expect(reflection).toContain('salvas somente neste dispositivo')
    expect(reflection).toContain('Compartilhar reflexão do dia')
    expect(reflection).not.toContain('Heart')
    expect(reflection).not.toContain('MoreHorizontal')
  })

  it('keeps Favorites as one collection view instead of duplicate summaries', () => {
    expect(favorites).toContain('Favoritos')
    expect(favorites).toContain('Trechos das obras')
    expect(favorites).toContain('Minhas reflexões')
    expect(favorites).toContain('CollectionCard')
    expect(favorites).not.toContain('Para revisitar')
    expect(favorites).not.toContain('SummaryCard')
  })

  it('keeps Comunidade as the clean canonical future shell for now', () => {
    expect(community).toContain('Comunidade')
    expect(community).toContain('Discussões')
    expect(community).toContain('Meus grupos')
    expect(community).toContain('Estudo Sistematizado')
    expect(community).toContain('Grupo da Caridade')
    expect(community).toContain('Família Espírita')
    expect(community).toContain('Jovens Espíritas')
    expect(community).toContain('Estudo dos Médiuns')
  })

  it('keeps the canonical five-item primary navigation until groups discovery is decided', () => {
    expect(bottomNav).toContain("label: 'Início'")
    expect(bottomNav).toContain("label: 'Estudos'")
    expect(bottomNav).toContain("label: 'Comunidade'")
    expect(bottomNav).toContain("label: 'Favoritos'")
    expect(bottomNav).toContain("label: 'Perfil'")
    expect(bottomNav).not.toContain("label: 'Reflexões'")
  })
})
