begin;

-- ============================================================
-- VEREDA — Community book requests and voting
-- ============================================================

create or replace function public.normalize_book_candidate_title(p_title text)
returns text
language sql
immutable
strict
set search_path = public
as $$
  select regexp_replace(
    trim(
      regexp_replace(
        lower(
          translate(
            p_title,
            'áàâãäéèêëíìîïóòôõöúùûüç',
            'aaaaaeeeeiiiiooooouuuuc'
          )
        ),
        '[^a-z0-9]+',
        ' ',
        'g'
      )
    ),
    '^(o|a|os|as|um|uma)[[:space:]]+',
    ''
  );
$$;

comment on function public.normalize_book_candidate_title(text) is
  'Normalizes candidate titles for duplicate prevention without changing the displayed title.';

create table if not exists public.book_candidates (
  id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) between 2 and 160),
  normalized_title text not null,
  author text check (author is null or length(trim(author)) between 1 and 160),
  submitted_by uuid references auth.users(id) on delete set null,
  status text not null default 'candidate'
    check (status in ('candidate', 'under_review', 'planned', 'declined', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_title)
);

comment on table public.book_candidates is
  'Community requests for future Vereda books. Votes express demand but do not imply editorial approval.';

create table if not exists public.book_candidate_votes (
  candidate_id bigint not null references public.book_candidates(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (candidate_id, user_id)
);

comment on table public.book_candidate_votes is
  'One authenticated vote per user and candidate.';

create index if not exists idx_book_candidates_status_created
  on public.book_candidates (status, created_at desc);

create index if not exists idx_book_candidate_votes_user
  on public.book_candidate_votes (user_id, created_at desc);

create or replace function public.set_book_candidate_normalized_title()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.title := trim(new.title);
  new.author := nullif(trim(coalesce(new.author, '')), '');
  new.normalized_title := public.normalize_book_candidate_title(new.title);
  new.updated_at := now();

  if length(new.normalized_title) < 2 then
    raise exception 'Candidate title is too short after normalization';
  end if;

  return new;
end;
$$;

create trigger set_book_candidate_normalized_title
before insert or update of title, author on public.book_candidates
for each row execute function public.set_book_candidate_normalized_title();

alter table public.book_candidates enable row level security;
alter table public.book_candidate_votes enable row level security;

create policy "authenticated users can read book candidates"
on public.book_candidates
for select
to authenticated
using (true);

create policy "authenticated users can submit book candidates"
on public.book_candidates
for insert
to authenticated
with check (
  submitted_by = auth.uid()
  and status = 'candidate'
);

create policy "users can read their own candidate votes"
on public.book_candidate_votes
for select
to authenticated
using (user_id = auth.uid());

create policy "users can add their own candidate vote"
on public.book_candidate_votes
for insert
to authenticated
with check (user_id = auth.uid());

create policy "users can remove their own candidate vote"
on public.book_candidate_votes
for delete
to authenticated
using (user_id = auth.uid());

create or replace function public.get_book_candidates()
returns table (
  id bigint,
  title text,
  author text,
  status text,
  created_at timestamptz,
  vote_count bigint,
  user_has_voted boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  return query
  select
    bc.id,
    bc.title,
    bc.author,
    bc.status,
    bc.created_at,
    count(bcv.user_id)::bigint as vote_count,
    bool_or(bcv.user_id = auth.uid()) as user_has_voted
  from public.book_candidates bc
  left join public.book_candidate_votes bcv
    on bcv.candidate_id = bc.id
  where bc.status in ('candidate', 'under_review', 'planned')
  group by bc.id
  order by count(bcv.user_id) desc, bc.created_at asc, bc.id asc;
end;
$$;

create or replace function public.submit_book_candidate(
  p_title text,
  p_author text default null
)
returns table (
  candidate_id bigint,
  created boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_title text := trim(coalesce(p_title, ''));
  v_author text := nullif(trim(coalesce(p_author, '')), '');
  v_normalized text;
  v_candidate_id bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if length(v_title) < 2 or length(v_title) > 160 then
    raise exception 'Candidate title must have between 2 and 160 characters';
  end if;

  if v_author is not null and length(v_author) > 160 then
    raise exception 'Candidate author must have at most 160 characters';
  end if;

  v_normalized := public.normalize_book_candidate_title(v_title);

  select bc.id
    into v_candidate_id
  from public.book_candidates bc
  where bc.normalized_title = v_normalized
  limit 1;

  if v_candidate_id is not null then
    return query select v_candidate_id, false;
    return;
  end if;

  begin
    insert into public.book_candidates (
      title,
      normalized_title,
      author,
      submitted_by,
      status
    )
    values (
      v_title,
      v_normalized,
      v_author,
      v_user_id,
      'candidate'
    )
    returning id into v_candidate_id;
  exception
    when unique_violation then
      select bc.id
        into v_candidate_id
      from public.book_candidates bc
      where bc.normalized_title = v_normalized
      limit 1;

      return query select v_candidate_id, false;
      return;
  end;

  insert into public.book_candidate_votes (candidate_id, user_id)
  values (v_candidate_id, v_user_id)
  on conflict (candidate_id, user_id) do nothing;

  return query select v_candidate_id, true;
end;
$$;

revoke all on function public.get_book_candidates() from public;
revoke all on function public.get_book_candidates() from anon;
grant execute on function public.get_book_candidates() to authenticated;

revoke all on function public.submit_book_candidate(text, text) from public;
revoke all on function public.submit_book_candidate(text, text) from anon;
grant execute on function public.submit_book_candidate(text, text) to authenticated;

commit;
