-- APPLIED TO PRODUCTION — Vereda 1.1 study journal
-- Supabase project: Vereda
-- Applied through the Supabase management migration path.
-- Ledger:
--   20260908042626 study_journal_foundation
--   20260908042732 study_journal_privilege_hardening
--
-- This operational record remains outside supabase/migrations because the
-- reviewed-boundary closed-world migration manifest is intentionally frozen.

begin;

create table if not exists public.study_journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_key text not null,
  entry_type text not null check (entry_type in ('reflection', 'note')),
  text text not null check (length(btrim(text)) > 0),
  entry_date date,
  book_id bigint references public.books(id) on delete set null,
  section_id bigint references public.sections(id) on delete set null,
  source_title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, entry_key)
);

create index if not exists idx_study_journal_user_updated
  on public.study_journal_entries (user_id, updated_at desc);

create index if not exists idx_study_journal_user_type
  on public.study_journal_entries (user_id, entry_type, entry_date desc);

alter table public.study_journal_entries enable row level security;

drop policy if exists study_journal_select_own on public.study_journal_entries;
create policy study_journal_select_own
  on public.study_journal_entries
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists study_journal_insert_own on public.study_journal_entries;
create policy study_journal_insert_own
  on public.study_journal_entries
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists study_journal_update_own on public.study_journal_entries;
create policy study_journal_update_own
  on public.study_journal_entries
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists study_journal_delete_own on public.study_journal_entries;
create policy study_journal_delete_own
  on public.study_journal_entries
  for delete to authenticated
  using (auth.uid() = user_id);

-- Supabase default grants are broader than this feature needs. Revoke first so
-- TRUNCATE/REFERENCES/TRIGGER cannot bypass the intended owner-only boundary.
revoke all on table public.study_journal_entries from public, anon, authenticated;
grant select, insert, update, delete on table public.study_journal_entries to authenticated;

revoke all on sequence public.study_journal_entries_id_seq from public, anon, authenticated;
grant usage on sequence public.study_journal_entries_id_seq to authenticated;

commit;
